### ISSUE TITLE
RES 2.0: event_store_events table new primary key is integer rather than bigint

### ISSUE THREAD

**Issue by haines** [RailsEventStore/rails_event_store#1001]
I'm working on upgrading to RES 2.0 and the generated migration sets the new `id` type to `serial` on PostgreSQL - I think this should be `bigserial` (which is the default in Rails 5.1+: https://github.com/rails/rails/pull/26266), otherwise we're going to have problems when we hit 2^31 events.

**Comment by pawelpacana** [comment]
1. Yes, `bigserial` over `serial` should be favored
2. You can change that in your generated migration to benefit from it, there should be no drawback in RES form such change

We'd gladly welcome such serial-to-bigserial contribution in RES, so that new migrations already start with bigserial. This needs to work across all supported Rails versions (5.0–6.1) and ideally we'd include an example migration to perform such change on existing installation.

**Comment by haines** [comment]
Oh right - I see now that it also affects the existing `event_store_events_in_streams` table.

I'll have a look at creating a PR!

**Comment by pawelpacana** [comment]
Not to expand scope but to give overview of loosely-related issues:
* https://github.com/RailsEventStore/rails_event_store/issues/947 (on changing migration version to new const and possible testing change)
* https://github.com/RailsEventStore/rails_event_store/pull/208 (on going with Rails-specific version number, provided we have better tests to verify that schema DSL results in precisely the SQL structure we want)

**Comment by pawelpacana** [comment]
Not to expand scope but to give overview of loosely-related issues:
* https://github.com/RailsEventStore/rails_event_store/issues/947 (on changing migration version to new const and possible testing change)
* https://github.com/RailsEventStore/rails_event_store/pull/208 (on going with Rails-specific version number, provided we have better tests to verify schema-dsl-to-sql-structure translation)

**Comment by kennethkalmer** [comment]
Since we're no longer defaulting to using `gen_random_uuid()` for `event_id`, can the inclusion of the `pgcrypto` extension be dropped from the migration? It took me quite a while to figure out this has been used since #514 got merged.

**Comment by pawelpacana** [comment]
> Since we're no longer defaulting to using gen_random_uuid() for event_id, can the inclusion of the pgcrypto extension be dropped from the migration? It took me quite a while to figure out this has been used since #514 got merged.

Good catch — there is no reason to keep `pgcrypto` any longer.

**Comment by pawelpacana** [comment]
I wish we had migration templates per database system. It is a duplication that contributes to greater clarity as opposed to  navigating around conditionals in a single template for all 3 possible systems.

**Comment by lukaszreszke** [comment]
Mentioned issues were done as part of https://github.com/RailsEventStore/rails_event_store/issues/947
Besides template per database system. This one was addressed in here https://github.com/RailsEventStore/rails_event_store/pull/1566
