### ISSUE TITLE
NoMethodError - undefined method `each_with_object' 

### ISSUE THREAD

**Issue by howmuchcomputer** [RailsEventStore/rails_event_store#1019]
Data is being loaded as a string. This is what I am getting as an argument to 
`RubyEventStore::TransformKeys.deep_transform `when I try to load an event:
`"{:remote_ip=>"::1", :request_id=>"23aa42d6-f39b-489c-8592-fff8a08f46cb", :correlation_id=>"db3dfb0c-6728-4114-9571-478282881ee9"}"`

(note: when data is saved, it is passed to `deep_transform` as an object)

which throws this error: 
`NoMethodError - undefined method `each_with_object' for #<String:0x00007f8d63e3a920>`

and the stack starts here:
`ruby_event_store-browser-2.1.0/lib/ruby_event_store/browser/app.rb`

I am using version 2.1.0

Issue occurs when I attempt to view an event in the RES browser

Here is the initializer code I am using:
```
require 'rails_event_store'
require 'aggregate_root'
require 'arkency/command_bus'

Rails.configuration.to_prepare do
  repository =
      RailsEventStoreActiveRecord::EventRepository.new(serializer: RubyEventStore::NULL)

  Rails.configuration.event_store =
      RailsEventStore::Client.new(repository: repository)

  Rails.configuration.command_bus =
      Arkency::CommandBus.new

  Configuration.new.call(
      Rails.configuration.event_store,
      Rails.configuration.command_bus
  )
end
```

**Comment by pawelpacana** [comment]
Can you please show me your `schema.rb` fragment that describes `data` and `metadata` of `event_store_events`?

**Comment by howmuchcomputer** [comment]
@pawelpacana this is my entire schema.rb:

```
ActiveRecord::Schema.define(version: 2021_03_06_093344) do

  # These are extensions that must be enabled in order to support this database
  enable_extension "pgcrypto"
  enable_extension "plpgsql"

  create_table "event_store_events", id: :serial, force: :cascade do |t|
    t.uuid "event_id", null: false
    t.string "event_type", null: false
    t.binary "metadata"
    t.binary "data", null: false
    t.datetime "created_at", null: false
    t.datetime "valid_at"
    t.index ["created_at"], name: "index_event_store_events_on_created_at"
    t.index ["event_id"], name: "index_event_store_events_on_event_id", unique: true
    t.index ["event_type"], name: "index_event_store_events_on_event_type"
    t.index ["valid_at"], name: "index_event_store_events_on_valid_at"
  end

  create_table "event_store_events_in_streams", id: :serial, force: :cascade do |t|
    t.string "stream", null: false
    t.integer "position"
    t.uuid "event_id", null: false
    t.datetime "created_at", null: false
    t.index ["created_at"], name: "index_event_store_events_in_streams_on_created_at"
    t.index ["stream", "event_id"], name: "index_event_store_events_in_streams_on_stream_and_event_id", unique: true
    t.index ["stream", "position"], name: "index_event_store_events_in_streams_on_stream_and_position", unique: true
  end

end
```

**Comment by pawelpacana** [comment]
ok, got it

in https://github.com/RailsEventStore/cqrs-es-sample-with-res we use JSONB (https://github.com/RailsEventStore/cqrs-es-sample-with-res/blob/master/db/schema.rb#L27-L28) to store event data and this influences RailsEventStore configuration (https://github.com/RailsEventStore/cqrs-es-sample-with-res/blob/master/config/initializers/rails_event_store.rb#L7)


here are two options to proceed:

1. go with JSONB for data and metadata, this is how we migrated sample app:

```
class BinaryToJsonb < ActiveRecord::Migration[5.2]
   def change
     execute "ALTER TABLE event_store_events ALTER COLUMN data     TYPE jsonb USING convert_from(data, 'UTF-8')::jsonb"
     execute "ALTER TABLE event_store_events ALTER COLUMN metadata TYPE jsonb USING convert_from(metadata, 'UTF-8')::jsonb"
   end
 end
 ```
 
2. change repository serializer to default one, that is YAML

```
RailsEventStoreActiveRecord::EventRepository.new(serializer: YAML)
```
in which case you can even go simpler and define while client as:

```
Rails.configuration.event_store =
    RailsEventStore::Client.new
```

**Comment by howmuchcomputer** [comment]
Thanks so much! Everything works now
