### ISSUE TITLE
Support only and exactly qualifiers in publish matcher

### ISSUE THREAD

**Issue by pawelpacana** [RailsEventStore/rails_event_store#1028]
On `HavePublished` matcher we support restricting message counts:

https://github.com/RailsEventStore/rails_event_store/blob/master/ruby_event_store-rspec/lib/ruby_event_store/rspec/have_published.rb#L227-L249

We do not have that on `Publish`:
https://github.com/RailsEventStore/rails_event_store/blob/master/ruby_event_store-rspec/lib/ruby_event_store/rspec/publish.rb

There's no reason not to have it

**Comment by swistak35** [comment]
Done in #1033
