### ISSUE TITLE
Update broken code in contrib/sidekiq_scheduler README 

### ISSUE THREAD

**Issue by QQism** [RailsEventStore/rails_event_store#1030]
The current sidekiq_scheduler's README is showing a broken code

https://github.com/RailsEventStore/rails_event_store/blob/master/contrib/ruby_event_store-sidekiq_scheduler/README.md

```ruby
event_store = RailsEventStore::Client.new(
  dispatcher: RailsEventStore::AfterCommitAsyncDispatcher.new(scheduler: RubyEventStore::SidekiqScheduler.new),
)
```

However, initializing a scheduler requires a `serializer` argument, so it should be as below

```ruby
event_store = RailsEventStore::Client.new(
  dispatcher: RailsEventStore::AfterCommitAsyncDispatcher.new(scheduler: RubyEventStore::SidekiqScheduler.new(serializer: YAML),
)
```

**Comment by swistak35** [comment]
Good catch, thank you :)
