### ISSUE TITLE
rails/generators as an explicit dependency

### ISSUE THREAD

**Issue by fidel** [RailsEventStore/rails_event_store#104]
While trying to use rails_event_store outside rails `rails/generators` dependency is missing. I think that it should be explicitly required to prevent people from adding it as a dev_dependency in libraries which could be potentially created within an RES ecosystem.

```
 c/R/rails_event_store-rspec $$ make test
Running basic tests - beware: this won't guarantee build pass

An error occurred while loading ./spec/rails_event_store/rspec/event_matcher_spec.rb.
Failure/Error: require "rails_event_store"

LoadError:
  cannot load such file -- rails/generators
# ./spec/rails_event_store/rspec/event_matcher_spec.rb:2:in `require'
# ./spec/rails_event_store/rspec/event_matcher_spec.rb:2:in `<top (required)>'
No examples found.

Randomized with seed 40509

Finished in 0.00031 seconds (files took 0.09792 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples

Randomized with seed 40509

make: *** [test] Error 1
```

**Comment by pawelpacana** [comment]
Perhaps we could load rails-dependent parts conditionaly (i.e. https://github.com/RailsEventStore/rails_event_store/blob/master/rails_event_store_active_record/lib/rails_event_store_active_record.rb#L1 or https://github.com/RailsEventStore/rails_event_store/blob/master/rails_event_store/lib/rails_event_store/all.rb#L5) with `require 'something' if defined?(Rails)`

**Comment by paneq** [comment]
Related #205
