### ISSUE TITLE
Consider automating RSpec configuration

### ISSUE THREAD

**Issue by fidel** [RailsEventStore/rails_event_store#120]
Posted originally by @pawelpacana 

Right now there's a manual process for adding matchers into the project besides plain gem install. It's good when you consciously decided to control every aspect of a depedency being added to the project. Yet most of the time I'd imagine there's not much to tweak.

Let's have a look how Capybara does it: https://github.com/teamcapybara/capybara#using-capybara-with-rspec

So when you want matchers, you require them:
```
require `capybara/rspec`
```

Same could work for RES matchers. 
```
require `rails_event_store/rspec`
```

Since the matchers live in a separate gem named `rails_event_store-rspec`, bundler should require it automatically by mere presence in `Gemfile` (or should we advise to `require: 'rails_event_store/rspec'` there?). As a "pro" user, you could add `require: false` to disable it and proceed manually. For the rest, good enough default would kick in. 

This is what happens after require: https://github.com/teamcapybara/capybara/blob/master/lib/capybara/rspec.rb. Basically all we advise to do yourself. 

Finally, Capybara does not depend on RSpec: https://github.com/teamcapybara/capybara/blob/master/capybara.gemspec#L24-L29

If we drop this runtime dependency as well, maybe `rails_event_store` could have matchers as a dependency without making your project depend on rspec when you don't have it.

**Comment by fidel** [comment]
Autoconfiguration is done in e800030.

Still, the dependency from RSpec should be discussed.

**Comment by paneq** [comment]
Let's think about it:

## Solution 1 (Current)

```
gem 'rails_event_store-rspec', group: :test
```

1 line of code

## Solution 2 (proposed)

```
require `rails_event_store/rspec`
```

1 line needs to be added to `rspec_helper` or somewhere else.

## Conclusion

Not much of a difference and a separate gem gives us better isolation. Capybara is a testing tool and so is rspec. RES is not so they don't land in the same group in Gemfile.

I think it would cause more issues than it is worth. e800030 was a sufficient enough change imho.
