### ISSUE TITLE
Publish ruby_event_store-rom 2.3.0 version

### ISSUE THREAD

**Issue by mayesa** [RailsEventStore/rails_event_store#1203]
hello guys! In https://rubygems.org/gems/ruby_event_store-rom I see 1.3.1 which I think is incompatible with  ruby_event_store 2.3.0. Is it possible to publish ruby_event_store-rom 2.3.0 to rubygems?

**Comment by pawelpacana** [comment]
Hey, I've pushed version 2.0.0 which was already prepared  some time ago. 
This version of ROM repository is intended to work with `ruby_event_store  >= 2.0.0, < 3.0.0` 

If you're using it for new RES project/install there's nothing more to do than to set up:
https://railseventstore.org/docs/v2/without_rails/#rom-sequel-setup


In case you're migrating from previous version:
- there were substantial changes in database structure from 1.x to 2.x documented in [changelog](https://github.com/RailsEventStore/rails_event_store/blob/master/contrib/ruby_event_store-rom/CHANGELOG.md#200)
- ROM gem has [moved to "contrib"](https://github.com/RailsEventStore/rails_event_store/tree/master/contrib#contrib), which means that its release cycle is now different from Ruby/RailsEventStore release cycle; it is still tested against the very same set of examples that the ActiveRecord-based EventRepository has to pass but it may sometimes lag with new releases without a maintainer invested in keeping up with ROM ecosystem — https://github.com/RailsEventStore/rails_event_store/issues/834
