### ISSUE TITLE
Allow to verify events generated in a block of code

### ISSUE THREAD

**Issue by fidel** [RailsEventStore/rails_event_store#121]
Posted originally by @paneq 

Imagine that you test an AggregateRoot and you use commands to set up its state but you never publish them.

You would like to verify events generated by a particular action but without the need to care about events generated by previous actions.

your choices:

```
product = Product.new
product.register(store_id: 1, sku: "BOOK")
product.unpublished_events.clear # unpublished_events is private right now inAggregateRoot but it should be public

expect(product).to have_applied(
  an_event(ProductSupplied).with_data(
    store_id: 1,
    sku: "BOOK",
    quantity: 30,
  ).strict
).only # `only` from https://github.com/RailsEventStore/rails_event_store-rspec/issues/5
```

What if instead we could do:

```
    expect do
      product.supply(20)
    end.to have_applied(an_event(ProductSupplied).with_data(
      store_id: 1,
      sku: "BOOK",
      quantity: 30,
    ).strict).only.on(product)
```

or something similar?

or maybe everything would be easier if we had

```
product = Product.new
product.register(store_id: 1, sku: "BOOK")
events = product.supply(30)
expect(events).to include(...)
```

**Comment by pawelpacana** [comment]
Done in #370 and released in v0.31.0

What's more — an aggregate (AggregateRoot) action returns now applied events. One can take advantage of that in testing.
