### ISSUE TITLE
Cannot install v2.0.1 with RubyGems v3.2.30+

### ISSUE THREAD

**Issue by haines** [RailsEventStore/rails_event_store#1236]
Prior to https://github.com/RailsEventStore/rails_event_store/pull/968, the mutant configuration was symlinked from the root of the repo into the individual gem directories. It was also included in the packaged gems, which means that installing the gems causes creation of a symlink to a (non-existent) file in the parent of the gem installation directory.

RubyGems forbids this for security reasons, so as of v3.2.30 the v2.0.1 gems fail to install:

```console
$ docker run --rm -it ruby:2.6-alpine sh
# gem update --system 3.2.30 >/dev/null
# gem install ruby_event_store --version 2.0.1
Fetching ruby_event_store-2.0.1.gem
Fetching concurrent-ruby-1.1.9.gem
Successfully installed concurrent-ruby-1.1.9
ERROR:  While executing gem ... (Gem::Package::SymlinkError)
    installing symlink '.mutant.yml' pointing to parent path /usr/local/bundle/gems/.mutant.yml of /usr/local/bundle/gems/ruby_event_store-2.0.1 is not allowed
```

I was hoping you might consider publishing a v2.0.2 release to fix this (we still haven't completed the upgrade from v1 so we need to install a v2.0.x before going to the latest version 😓).

I think it would be sufficient to add `.mutant.yml` to the excluded files in the gemspecs (e.g. [here](https://github.com/RailsEventStore/rails_event_store/blob/v2.0.1/ruby_event_store/ruby_event_store.gemspec#L23)) because I don't think there's any reason to include it in the packaged gem anyway.

Note that this affects all the gems (it just fails on `ruby_event_store` because that is the first dependency in the tree).

**Comment by foolem** [comment]
This issue is blocking me too, +1

**Comment by pawelpacana** [comment]
> I was hoping you might consider publishing a v2.0.2 release to fix this (we still haven't completed the upgrade from v1 so we need to install a v2.0.x before going to the latest version 😓).

Ok, I'll push 2.0.2 with that symlink excluded. 

Later gemspecs have been revised already: https://github.com/RailsEventStore/rails_event_store/blob/a37e4adc3d6a65f7f5fe018f4c2e99cdef99aa47/ruby_event_store/ruby_event_store.gemspec#L17

**Comment by pawelpacana** [comment]
https://github.com/RailsEventStore/rails_event_store/releases/tag/v2.0.2

**Comment by haines** [comment]
Thanks @pawelpacana, 2.0.2 is working perfectly for me.

**Comment by swistak35** [comment]
@haines Hey, if you are still on 2.0.x release then there is a new release :) https://github.com/RailsEventStore/rails_event_store/releases/tag/v2.0.3
