### ISSUE TITLE
Upgrade activerecord-import to resolve: Rails 7 raw_filter method removed 

### ISSUE THREAD

**Issue by jkwuc89** [RailsEventStore/rails_event_store#1248]
See https://github.com/zdennis/activerecord-import/issues/736. Because of this issue, using `rails_event_store` inside Rails 7 results in this error:

```
NoMethodError: undefined method `raw_filter' for #<ActiveSupport::Callbacks::Callback:0x00007fad95e054f8
@chain_config={:scope=>:name, :terminator=>#<Proc:0x00007fadc5daa550
/Users/kwedinger/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/activesupport-7.0.0/lib/active_support/callbacks.rb:684>}, @name=:validate, @kind=:before, @filter=:cant_modify_encrypted_attributes_when_frozen,
@if=[#<Proc:0x00007fad95e05ae8 /Users/kwedinger/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/activerecord-7.0.0/lib/active_record/encryption/encryptable_record.rb:13 (lambda)>], @unless=[]>
Did you mean?  filter
```

In Rails 7, the `raw_filter` method was removed from `ActiveSupport::Callbacks::Callback`. 

https://github.com/zdennis/activerecord-import/pull/749 fixes this inside activerecord-import. It should be possible to upgrade the version of activerecord_import to pick up this Rails 7 fix.

**Comment by pawelpacana** [comment]
Thanks for the tip! 

We'll consider bumping minimal required `activerecord-import` on next release, provided there's new gem release of `activerecord-import` too.

Is it somehow blocking you in the meantime? We currently have very permissive version policy on this dependency, and you could bump gem version on your side in `Gemfile`: 

```ruby
  spec.add_dependency "activerecord-import", ">= 1.0.2"
```

On [discord](https://discord.gg/qjPr9ZBpX6) we've also been discussing the possibility to drop `activerecord-import` for some Rails versions.

<img width="935" alt="Zrzut ekranu 2021-12-16 o 15 14 47" src="https://user-images.githubusercontent.com/116740/146388097-1bff8492-c67e-4d2a-b69a-1b4bfe93d9a0.png">

**Comment by jkwuc89** [comment]
Using `gem "activerecord-import", git: "https: //github.com/zdennis/activerecord-import"` inside my Gemfile allows me to work around this.

**Comment by pawelpacana** [comment]
https://rubygems.org/gems/activerecord-import/versions/1.3.0 has been just released

**Comment by jkwuc89** [comment]
With the release of active record-import, I can now use this in my Gemfile to prevent the `raw_filter` error.

```ruby
gem "activerecord-import", '~> 1.3'
```

**Comment by pawelpacana** [comment]
The `activerecord-import` has been dropped as a dependency since `2.4.0` release. It became possible because we stopped officially supporting Rails 5.x from this release. Rails 5.2 reaches end-of-life on 1.06.2022, which is in 4 days from now.
