### ISSUE TITLE
Migration to new DB schema

### ISSUE THREAD

**Issue by paneq** [RailsEventStore/rails_event_store#129]
* [ ] Verify data migrated
  * [x] positions
  * [ ] created_at
* [x] Check on all DBs
  * [x] postgres
  * [x] mysql
  * [x] sqlite
* [x] Verify proper schema at the end
* [x] v1-v2 migration generator by calling `rake res:v1tov2schema_migration`
* [x] Fix random with SQL

**Comment by paneq** [comment]
Should we have a new gem for upgrades that would just have this migration?

I think that ideal steps to verify correctness would include

* filling DB with data via older gem write API
* install new gem version
* run migration
* run queries against API using newer read API and make sure they give the same results
* write new data and make sure everything works correctly

Sounds pretty much complicated

**Comment by paneq** [comment]
@mlomnicki any ideas?

**Comment by paneq** [comment]
Alternatively, we ship rails_event_store_active_record_single_table adapter which still handles race conditions incorrectly but does not require migrating schema of events.

**Comment by paneq** [comment]
It's not writing to `all` or `__global__` ... Damn.

**Comment by pawelpacana** [comment]
> Alternatively, we ship rails_event_store_active_record_single_table adapter which still handles race conditions incorrectly but does not require migrating schema of events.

I think that would be interesting option -- it would give some time to prepare to migration. We could issue deprecation warning that you still use old schema and that there's new one.

**Comment by pawelpacana** [comment]
```ruby
# This migration is not intended for live migration
# It assumes no data is added at that time.
# Make sure you have a backup before running on production

# 10_000_000 distinct stream names
# can cause around 2GB of usage
# make sure you can run this migration on your production system
streams = {}

RailsEventStoreActiveRecord::Event.find_each do |ev|
  position = nil
  if preserve_positions?(ev.stream)
    streams[ev.stream] ||= -1
    position = streams[ev.stream] += 1
  end

  RailsEventStoreActiveRecord::EventInStream.create!(
    stream: "all",
    event_id: ev.id,
    created_at: ev.created_at,
  )

  unless ev.stream == "all"
    RailsEventStoreActiveRecord::EventInStream.create!(
      stream: ev.stream,
      position: position,
      event_id: ev.id,
      created_at: ev.created_at,
    ) 
  end
end

add_index :event_store_events_in_streams, [:stream, :position], unique: true
add_index :event_store_events_in_streams, [:stream, :event_id], unique: true
add_index :event_store_events_in_streams, [:created_at]

remove_column :event_store_events, :stream
remove_column :event_store_events, :id
rename_column :event_store_events, :event_id, :id
change_column :event_store_events, :id, :uuid

def preserve_positions?(stream_name)
  # return true if you use given stream for event sourcing
  # return true if you need to have a deterministic order of events
  # in that stream
  # return true if only one thread is supposed to be writing in that stream
  #
  # return false if this stream is for purely technical purposes
  # and multiple threads/processes can be publishing at given time
  # and you don't care about the exact order when reading from it
  false
end
```
