### ISSUE TITLE
link_events_to_stream API

### ISSUE THREAD

**Issue by paneq** [RailsEventStore/rails_event_store#134]
It would copy/link events to new streams but without triggering handlers again.

So for the first time you would publish_event which would save it in `all` stream, provided stream and then later (maybe in a handler) you could use link_events_to_stream to append to another stream.

I believe 1 stream at a time should be allowed as different stream can use different strategies for appending.

**Comment by vbyno** [comment]
@paneq , could you please specify an API you expect to see here?
Right now in our project we use something like
```
publish(UserAssignedToCompany.strict(metadata: { streams_to_append: ["company-#{ company.id }", 'other_stream'], data: {...} }))
```

**Comment by paneq** [comment]
@vbyno I imagine

```ruby
link_events_to_stream(event_id, stream_name: expected_version:)
```

so it is similar to `publish_event`.

* We need `event_id` instead of a full `event` because the `data` and `metadata` is going to be the same.
* We need one `stream_name` because the `expected_version` can apply to one `stream_name` at a time.
* And we need `expected_version` to handle optimistic locking http://railseventstore.org/docs/expected_version/

**Comment by paneq** [comment]
This similarity to `publish_events` would make the implementation in repositories much easier IMHO and similar to what they already do when the event is published the 1st time.
