### ISSUE TITLE
missing expected_version on store?

### ISSUE THREAD

**Issue by pawelpacana** [RailsEventStore/rails_event_store#136]
_From @andrzejsliwa on April 13, 2017 14:58_

I wonder if in: 

```ruby  
def store(stream_name = loaded_from_stream_name, event_store: default_event_store)
    unpublished_events.each do |event|
      event_store.publish_event(event, stream_name: stream_name)
    end
    @unpublished_events = nil
  end
```

there is a missing usage of expected_version param handled by event_store.publish_event.

I think loading of same aggregate on multiple instances/workers should be somehow prevented (using distributed actors or locking for ex). If we are not able to do so, at least we should be able to detect conflict on expected_version (for ex. last event_id) to keep event log consistent in case of double submit or case when two instances of same aggregate_root will run at the same time and update its state by accepting commands in short timespan.

Even if events are handled in synchronous way, multiple web workers by handling requests can run concurrently few copies of same aggregate_root, right?

_Copied from original issue: RailsEventStore/aggregate_root#10_

**Comment by pawelpacana** [comment]
_From @andrzejsliwa on April 13, 2017 15:4_

looks like its related to https://github.com/arkency/aggregate_root/pull/1

**Comment by pawelpacana** [comment]
_From @paneq on April 13, 2017 15:45_

@andrzejsliwa  and a duplicate of #8  :)

**Comment by pawelpacana** [comment]
_From @paneq on April 13, 2017 15:47_

@andrzejsliwa you are very much correct. We have not yet had the time to fix it. It would require changing the underlying schema of the table storing the events so it's quite a big change.

**Comment by pawelpacana** [comment]
_From @andrzejsliwa on April 13, 2017 16:1_

so how you dealing with such problems on production? 

here is example solution (with versioning) done in Elixir: https://github.com/slashdotdash/commanded/blob/master/lib/commanded/aggregates/aggregate.ex 
https://github.com/slashdotdash/eventstore/blob/master/lib/event_store/streams/stream.ex

in case of Elixir version recommended solution of avoiding conflict is just clustering, and ensuring that only one process of aggregate_root is running in whole system, which is not difficult in Erlang/Elixir because of Actors/Processes and builtin clustering. Handling conflict via exception (and maybe with retry strategy) in case of Ruby is just simplest workaround.

**Comment by pawelpacana** [comment]
_From @paneq on April 23, 2017 10:35_

@andrzejsliwa in our biggest system we use non open source event store implementation with a bit different design.

The overall goal is to fix this problem in aggregate_root/rails_event_store in upcoming months to have optimistic locking but i can't promise a timeline.

The workaround is to use your database existing pessimistic locking solutions.

**Comment by pawelpacana** [comment]
_From @andrzejsliwa on April 24, 2017 6:40_

@paneq I wonder if "non open source event store" is a product of Arkency? Please understand me correctly, I'm observing you guys and I see that you are advocate of DDD & CQRS/ES, you are doing lots of presentations and open discussion about it. I'm really grateful for all of it, but in many of examples you are referring to your gems, which looks like not production ready at all. So I see here huge dissonance. I know that you are provider of DDD training. To be honest what is missing for me is a clear message from you guys, about:
- what exactly are your products (training and/or propertiary solution)?
- if your open source gems are only toys/show cases or rather demo?
- if with training we will get some close source examples (this looks like that based on your blog posts and tweets)?
- if source examples from training will base on your open source gems (which looks like not production ready yet)?
- if rails_event_store, aggregate_root, etc... are just advertisement of your close solutions and trainings? 
- what is your bigger plan about all of this topics? (in training you are touching event storming, ddd, cqrs/es and some coding exercises related to refactoring)

answering such questions helps me and more people like me, who listening you, adjust expectations about your training, software and services you are providing.

**Comment by paneq** [comment]
I believe this is fixed on master
