### ISSUE TITLE
Mutation testing and database engines/ORMs

### ISSUE THREAD

**Issue by pawelpacana** [RailsEventStore/rails_event_store#139]
Once in a time we're hit by this and similar failures:
<img width="618" alt="zrzut ekranu 2017-10-11 o 16 57 22" src="https://user-images.githubusercontent.com/116740/31448707-6c8bce24-aea5-11e7-8453-c59af826b5a1.png">

Any ideas how to improve?

**Comment by paneq** [comment]
Use `ActiveSupport::Notifications` and test generated SQL query.

Do it in non-shared repository tests.

Thanks @mlomnicki for the idea.

I now remember what Marcus once said. That not always you can test something relatively (is A different than B). Sometimes you need to test specifically. I believe that is the case. We want to test our explicit query even though non-explicit would give the same result usually. But we cannot trigger easily the non-usual cases so we can test our semantics and that's good enough.

**Comment by pawelpacana** [comment]
I didn't manage to reproduce this -- when manually mutating the code as above, at least two units fail. Let's reopen when it occurs again. `AS::Notifications` approach seems like a good solution.

**Comment by paneq** [comment]
Just happened to me on localhost and CI. Should be fixed in: 0030f823c44f5446649ddab6b481beeb9cf2ff14 and 093bcee5a20c1cfcf447158afcffd8e3354dbb81

**Comment by pawelpacana** [comment]
Happened again after #144 merge, https://travis-ci.org/RailsEventStore/rails_event_store/jobs/292126438
