### ISSUE TITLE
Unexpected handling of empty array when link-ing using AR repo 

### ISSUE THREAD

**Issue by mpokrywka** [RailsEventStore/rails_event_store#1417]
While using InMemoryRepository, client.link([], stream_name: "test") works as expected:
`
RubyEventStore::Client.new(repository:RubyEventStore::InMemoryRepository.new).link([],stream_name:"Test")
`

but when using RailsEventStoreActiveRecord::EventRepository, client.link([], stream_name: "test") raises exception.
`
RubyEventStore::Client.new(repository:RailsEventStoreActiveRecord::EventRepository.new(serializer:RubyEventStore::NULL)).link([],stream_name:"Test")
`

Same for nil parameter - works with InMemoryRepo.

Probably RailsEventStoreActiveRecord::EventRepository#link_to_stream should check for empty event_ids similar like in "append_to_stream"

**Comment by mpokrywka** [comment]
Change of behavior happened after [Replace ActiveRecord::Import#import for Rails 6 bulk insert](https://github.com/RailsEventStore/rails_event_store/commit/81953087ab6e518e3df1e1a3401363e34d5ee601)

**Comment by pawelpacana** [comment]
Definitely missed change, thank for pointing this out!
