### ISSUE TITLE
Legacy - single table schema adapter

### ISSUE THREAD

**Issue by paneq** [RailsEventStore/rails_event_store#143]
So that you can migrate to higher RES versions without migrating data

* [x] adapter
* [x] adapter documentation
* [x] when using new version and having an exception from missing schema, point to this adapter or tell to run the migration
* [x] raise exception when using unsupported `:auto` mode
* [x] decide if `false` or exception in the migration.

**Comment by pawelpacana** [comment]
>  adapter documentation

What kind of documentation have you imagined on this checklist item?

**Comment by paneq** [comment]
@fidel @pawelpacana I see the documentation for upgrade to `0.19` is available in the draft of a new release https://github.com/RailsEventStore/rails_event_store/releases/tag/untagged-ec27172c30c3c81d7197

Is there anything else we want to do here?

Or can we close the issue?

**Comment by pawelpacana** [comment]
Describe `def preserve_positions?(stream_name)` from the migration and strategy one should take.

**Comment by paneq** [comment]
@pawelpacana got it, doing

**Comment by paneq** [comment]
@pawelpacana do you think we should leave `false` as default or raise an exception?

**Comment by pawelpacana** [comment]
As the order in which events were persisted will be preserved and that in no way it was easy to use `expected_version` other than default `:any` I'd probably leave it as is.

I'd suggest refining the description about cases when yout return true -- from the perspective of 0.18 API,  for example:

> return true if you use given stream for event sourcing
There's a hidden assumption that you were betting on optimistic concurrency and passed `expected_version` in form of `uuid`. If not then this hint is not very useful.

**Comment by paneq** [comment]
@pawelpacana I changed to

```
  def preserve_positions?(stream_name)
    # http://railseventstore.org/docs/expected_version/
    #
    # return true if you use given stream for event sourcing
    # return true if you use an Integer or :none as
    # expected_version when publishing in this stream
    #
    # return false if use use :any (the default) as expected_version
    # when publishing to this stream
    false
  end
```

**Comment by paneq** [comment]
Does that make sense?

**Comment by paneq** [comment]
Notice that if someone used RES for Event Sourcing then they must provide `true` sometimes otherwise the position will be `NULL` and things won't work correctly

**Comment by pawelpacana** [comment]
It still feels as we're talking in terms of 0.19 API to migrate 0.18 data.

> Integer or :none as expected_version
- `Integer` wasn't a thing back then 
-  `:none` doesn't make sense to me in the context of migration as it usefull only for first event in stream

I'd change the wording to:
- return `true` if you used previous event_id as expected_version when publishing in this stream

**Comment by pawelpacana** [comment]
> Notice that if someone used RES for Event Sourcing then they must provide true sometimes otherwise the position will be NULL and things won't work correctly

Because of the change in `aggregate_root`?

**Comment by pawelpacana** [comment]
return `true` if you use given stream for event sourcing with `aggregate_root` -- this would be clearer for me

**Comment by paneq** [comment]
> Because of the change in aggregate_root

Hmmm. Because off all the changes together in ActiveRecord Adapter, RubyEventStore and AggregateRoot especially because it now can fail on concurrent updates, indeed.

> return true if you use given stream for event sourcing with aggregate_root -- this would be clearer for me

but if you use for event sourcing without aggregate root and you were passing `uuid` so far then this is also true.
