### ISSUE TITLE
Generate test helper stub for with bounded_context generator

### ISSUE THREAD

**Issue by pawelpacana** [RailsEventStore/rails_event_store#145]
```ruby
ENV['RAILS_ENV'] = 'test'

$LOAD_PATH.push File.expand_path('../../../spec', __FILE__)
require File.expand_path('../../../config/environment', __FILE__)
require File.expand_path('../../../spec/rails_helper', __FILE__)

require_relative '../lib/catalog' # or any other BC name you've chosen
```

Generating following code would ensure:
- autoloading works in specs (requiring root module)
- one can individual specs bu providing path to file
- top-level app spec/rails helper is loaded (debatable if always needed)

**Comment by pawelpacana** [comment]
Additionaly we could generate top-level `spec/catalog_spec.rb`:

```ruby
require 'rails_helper'

path = Rails.root.join('catalog/spec')
Dir.glob("#{path}/**/*_spec.rb") do |file|
  require file
end
```

That would ensure that BC tests are not missed on CI and run with others.

**Comment by pawelpacana** [comment]
Likely needs a guideline to use BC spec helper in BC specs:
```ruby
require_relative 'spec_helper'
```

**Comment by fidel** [comment]
Completed in https://github.com/RailsEventStore/rails_event_store/commit/988a443813f48789d414fabcd2235d364ce3c58b
