### ISSUE TITLE
Include bounded_context gem within rails_event_store dependencies

### ISSUE THREAD

**Issue by pawelpacana** [RailsEventStore/rails_event_store#146]
Include gem to have batteries included within `rails_event_store`. We've decided that `rails_event_store` in an umbrella for whole gem ecosystem (unlike `ruby_event_store` which one can use to assemble very own set of tools).

**Comment by andrzejkrzywda** [comment]
I'm all for it, the sooner the better. 

bounded_context is a simple, yet very valuable tool. Adding this shouldn't cause any problem, but should benefit many programmers.
