### ISSUE TITLE
Include arkency-command_bus within rails_event_store dependencies

### ISSUE THREAD

**Issue by pawelpacana** [RailsEventStore/rails_event_store#147]
Include gem to have batteries included within `rails_event_store`. We've decided that `rails_event_store` in an umbrella for whole gem ecosystem (unlike `ruby_event_store` which one can use to assemble very own set of tools).

Might be sensible to move it to the monorepo and bump version number as well.

**Comment by andrzejkrzywda** [comment]
Yes!

**Comment by paneq** [comment]
Considering that nothing in RES depends on command bus I don't see the technical need. But marketing-wise it could be a good move.

**Comment by paneq** [comment]
@pawelpacana @andrzejkrzywda @mpraglowski 

How do you think we could expose an instance of command bus to developers? Just adding a dependency does not seem enough for me.

```
module RailsEventStore
  class Client < RubyEventStore::Client
    def initialize(repository: RailsEventStore.event_repository,
                   event_broker: EventBroker.new(dispatcher: ActiveJobDispatcher.new),
                   page_size: PAGE_SIZE,
                   command_bus: Arkency::CommandBus.new,
)
      capture_metadata = ->{ Thread.current[:rails_event_store] }
      super(repository: repository,
            event_broker: event_broker,
            page_size: page_size,
            metadata_proc: capture_metadata)
    end

    attr_reader :command_bus
  end
end
```

```ruby
config.to_prepare do
  Rails.configuration.event_store = event_store = RailsEventStore::Client.new
  event_store.subscribe(OrderNotifier.new, to: [OrderCancelled])
  event_store.command_bus.register(BarCommand, -> (bar_cmd) { BarService.new.call(bar_cmd) })
end
```

**Comment by paneq** [comment]
Maybe it would be enough If we just moved command_bus readme to event store and recommend what we recommend in the README?

```ruby
config.to_prepare do
  config.command_bus = Arkency::CommandBus.new
  register = command_bus.method(:register)

  { FooCommand => FooService.new(event_store: event_store).method(:foo),
    BarCommand => BarService.new,
  }.map(&:register)
end
```

??

**Comment by paneq** [comment]
But maybe event store could benefit somehow from knowing about the commands as well? Maybe for tracking command->event relationship?

**Comment by andrzejkrzywda** [comment]
I suggest we start with a small step and just bring the gem as a dependency. This will trigger additional steps later like copying documentation and maybe moving the code to the monorepo.
