### ISSUE TITLE
Remove LegacyEventRepository in 0.21.0 release

### ISSUE THREAD

**Issue by pawelpacana** [RailsEventStore/rails_event_store#152]
Get rid of LegacyEventRepository and limited support for old database schema at this point.

**Comment by fidel** [comment]
Do we plan to drop schema migration code too? Or should we wait a bit with that? /cc @paneq

**Comment by pawelpacana** [comment]
> Do we plan to drop schema migration code too?

My intent and understanding was that LegacyEventRepository can't support all use cases and does it's best recreating new behaviors on old schema. We offered it for limited time so that you could defer migration for some time.

It doesn't cost us much on the other hand to ship migration code until schema changes again.

**Comment by paneq** [comment]
I think we should keep the migration code forever.

Also I would not remove the legacy schema until maintaining it becomes costly. In our newest release we added a new feature and the cost of maintaining a legacy schema was 0 I believe, so also 0 motivation for me to remove.

I understand that we eventually want to drop it, but as long as it is a no-cost plug-in I would not remove it.

What do you think?

**Comment by andrzejsliwa** [comment]
Full agree, lets keep it until we can, and remove it only when will become painful.

**Comment by pawelpacana** [comment]
Let's defer removal then and keep it as long as it doesn't cause trouble. Might make sense to drop on https://github.com/RailsEventStore/rails_event_store/milestone/3

**Comment by fidel** [comment]
Leaving adapter in place then, closed #169
