### ISSUE TITLE
Unable to update to rails_event_store 2.8

### ISSUE THREAD

**Issue by arfl** [RailsEventStore/rails_event_store#1520]
Just run bundle update rails_event_store 2.8 and failed with the following error: 
```
Because rails_event_store >= 2.8.0 depends on rails_event_store_active_record = 2.8.0
  and rails_event_store_active_record = 2.8.0 could not be found in rubygems repository https://rubygems.org/ or installed locally,
  rails_event_store >= 2.8.0 is forbidden.
So, because Gemfile depends on rails_event_store ~> 2.8,
  version solving has failed.
```

rails_event_store_active_record 2.8 is not released yet. Please release it.

**Comment by lukaszreszke** [comment]
Hi @arfl, 

Thanks for reporting the issue. 

I released the RailsEventStoreActiveRecord gem.

Can you confirm that you're able to perform the update now?

**Comment by pawelpacana** [comment]
Seems to be in the index now: https://rubygems.org/gems/rails_event_store_active_record

**Comment by arfl** [comment]
I can update now. Thank you!
