### ISSUE TITLE
Custom serializers/deserializers aka mappers

### ISSUE THREAD

**Issue by paneq** [RailsEventStore/rails_event_store#154]
I think with custom serialization/deserialization strategy we could solve a few problems.

a) performance - if you want faster RES just serialize using different format
b) event's interface. If you want to use structs or hashes that should be ok, as long as we know how to deserialize it and serialize it.

I believe we need:

* event_id (string)
* event_type (string)
* data (string/binary)
* metadata (string/binary)

Related: #27 #50

**Comment by paneq** [comment]
Good point:

> ruby_event_store injects a timestamp into the metadata hash 

Response:

>This is a timestamp of event publication. It is similar to you go to post some message at the post office, you handle your message (letter in envelope) that is "frozen" - but the post office clerk will hit the envelope with stamp adding a time when it has been handled. This is exactly what is RubyES doing.
> And it could not be set earlier because the moment of event creation is not the same as the moment of publication.

I don't think we can assume `metadata` is a `Hash`

If we want flexibility in defining events then the client could use a closed struct which does not allow populating it with any kind of data...

On the other hand we also have request metadata that we populate... We must somehow do it before the event is serialized. So it seems there are 3 stages

1. an event class is instantiated and filled with data by a developer
2. the event's metadata is enriched by RES
3. the event is serialized by a mapper (YAML by default, other can be provided)
4. the event is stored by RES

This feature is about introducing an explicit 3rd stage of the process. I am not sure yet how we can do it without introducing an interface for the 2nd stage as well.

BTW. I think timestamp should be a separate attribute, and not in metadata. We only know the timestamp once the event is actually persisted `RailsEventStoreActiveRecord::Event#created_at`. Also... An event in the future could be persisted in different streams at different times.

**Comment by paneq** [comment]
> I believe we need:
> event_id (string)
> event_type (string)
> data (string/binary)
> metadata (string/binary)

This is in terms of what needs to be returned to us by a serializer. Not what an event needs to define.

The point of the serializer/deserializer (aka mapper) is to decouple the event format from what needs to be persisted somehow.

**Comment by paneq** [comment]
I think that I come to an understanding:

* the event's metadata is enriched by RES
  * right now this is implemented in RubyEventStore. I believe this should be moved up to RailsEventStore

    ```ruby
    metadata[:timestamp] ||= clock.()
    metadata.merge!(metadata_proc.call || {}) if metadata_proc
    ```
* RubyEventStore would get an event (any kind) and a serializer and would use the serializer to convert the event into a few binary strings to be persisted by any adapter.
  * That means that for RubyEventStore the event would be basically immutable and could be in any format!
* RailsEventStore would get an event and before passing it down to RubyEventStore it would enrich the metadata with global metadata (and possibly the timestamp although I don't see much value in it)
* If the `timestamp` is supposed to mean a moment in time when the event was persisted then the only layer capable of doing it most correctly is the adapter layer (either by filling it out in the last possible moment) or by utilizing DBs functionality.

What do you think @andrzejsliwa @mlomnicki @mpraglowski @gottfrois @pawelpacana @fidel ?

**Comment by joelvh** [comment]
hi @paneq, I'm happy to have discovered you guys' set of gems to implement DDD in Rails. I've been reading through your open issues and other resources to learn about what you guys are doing. I'm about to test things out in our application, and will be following along closely on these issues. Love that you guys keep track of your thoughts consistently.

Wanted to know if/how you guys have handled events with data that needs to be encrypted. The serialization feature you're proposing might be a solution, but wanted to see if you already have dealt with this. Currently, tables with sensitive data in our application have binary columns for the data, initialization vector, and salt.

Curious how you guys think about encryption needs in an application like this (for data at rest). (Also getting my head around hexagonal architectures in Ruby applications to help with segmenting use of sensitive data... but I may pick your brain on that another day.)

Thanks in advance!

**Comment by paneq** [comment]
> wanted to see if you already have dealt with this

I didn't have the need so far.

**Comment by paneq** [comment]
> Love that you guys keep track of your thoughts consistently.

Thanks for your positive support.

**Comment by sevos** [comment]
TBH: I see currently no reason to change `#metadata` return type from Hash to anything else, unless we see the evidence that other types may be faster. Possibility to change YAML to, for example, JSON may be interesting, but I would strongly recommend to research the biggest bottlenecks in our stack first (my bet still is that huge event tables (100Mio+ events, 10Mio+ streams) are still too slow, and maybe implementing kind of snapshot+closing ledger could improve the performance in some cases.

**Comment by andrzejsliwa** [comment]
@sevos regards to huge events tables, please take a look also on recent version, some improvements on data structure were made. But will require migration

**Comment by paneq** [comment]
> I see currently no reason to change #metadata return type from Hash to anything else, unless we see the evidence that other types may be faster

That's not the point to be faster. The point is the ability to serialize anything and define events any way you want (any pattern or gem). Then it is up to the developer whether they want to have `metadata` or not and up to the serializer to handle provided events correctly.

**Comment by paneq** [comment]
> Possibility to change YAML to, for example, JSON may be interesting, but I would strongly recommend to research the biggest bottlenecks in our stack first (my bet still is that huge event tables (100Mio+ events, 10Mio+ streams) are still too slow, and maybe implementing kind of snapshot+closing ledger could improve the performance in some cases.

Before we research and measure anything we should establish what usecase are we talking about? Persisting a single, restoring aggregate from a single stream? Running a projection on many stream?

In:

```
a) performance - if you want faster RES just serialize using different format

b) event's interface. If you want to use structs or hashes that should be ok, as long as we know how to deserialize it and serialize it
```

all I meant that it might be sometimes helpful and useful to have faster serialization formats and custom mappers should allow us but whether that turns out to be useful or truth remains to be seen.

For me, personally, B is much more important part and it has nothing to do with performance so let's not discuss any real or imaginary performance issues here.

**Comment by mpraglowski** [comment]
> Also... An event in the future could be persisted in different streams at different times.

But it is still the same event - we do not want `timestamp` to depend on when event has been persisted (linked) in a stream. It is a time of moment when the fact defined by domain event has happened. Maybe we need additional timestamp for storing a moment when event has been linked to stream? For the "original" stream this link timestamp should be equal to event's timestamp.

**Comment by paneq** [comment]
@sevos @andrzejsliwa @mpraglowski done in #189

**Comment by paneq** [comment]
Related: #228
