### ISSUE TITLE
Better API for subscribers (dynamic and static) which are procs

### ISSUE THREAD

**Issue by paneq** [RailsEventStore/rails_event_store#155]
Current API:

```ruby
cancel_order = CancelOrder.new
event_store  = Rails.configuration.event_store

event_store.subscribe(
    -> (event) {
      Rails.logger.warn(event.inspect)
    },
    [OrderCancelled]
  ) do
  cancel_order.call(order_id, user_id)
end
```

Proposed API:

```ruby
cancel_order = CancelOrder.new
event_store  = Rails.configuration.event_store

event_store.on(OrderCancelled) do |event|
  Rails.logger.warn(event)
end.during do
  cancel_order.call(order_id, user_id)
end
```

or

```ruby
cancel_order = CancelOrder.new
event_store  = Rails.configuration.event_store

event_store.during do
  cancel_order.call(order_id, user_id)
end.on(OrderCancelled) do |event|
  Rails.logger.warn(event)
end.execute
```

## Checklist

* [ ] one shot subscribers
* [ ] normal subscribers

**Comment by paneq** [comment]
Today I was working on something and I wrote:

```
client.subscribe(->(ev){@ev = ev}, [ResTesting::OrderCreated])
```

and I realized again how non-idiomatic the whole situation is. 

Here is another take on that API:

## Long-term subscribers

```ruby
event_store.subscribe(OrderCancelled, handler)

event_store.subscribe(OrderCancelled) do |event|
  Rails.logger.warn(event)
end
```

## One-shot subscribers

```ruby
event_store.within{ do_something }.subscribe(OrderCancelled, handler)

event_store.within do
  cancel_order.call(order_id, user_id)
end.subscribe(OrderCancelled) do |event|
  Rails.logger.warn(event)
end
```

I think `within` might be a better word than `during`. Capybara inspiration.
https://www.dropbox.com/s/tr60r54v6pw6qkx/Screenshot%202018-02-21%2022.35.37.png?dl=0

**Comment by paneq** [comment]
I realized since `within` would be a new API returning a new object we could introduce it quite safely.

**Comment by pawelpacana** [comment]
Looks cool. How does it compare to`AS::Notifications` naming?

**Comment by paneq** [comment]
As for changing the order of arguments for `subscribe`...

I am not sure how to go from 

```
subscribe(subscriber, event_types, &proc)
```

to 

```
subscribe(event_types, subscriber, &subscriber2)
  subscriber ||= subscriber2
end
```

I think we can recognize old API vs new API based on `event_types` if it responds to `each` (whether that's first or second argument). Let's hope not many handlers respond to `each` and this _best-effort_ heuristic be good enough_

**Comment by paneq** [comment]
> How does it compare to AS::Notifications naming?

Hmmm, good question

```
ActiveSupport::Notifications.instrument('render', extra: :information) do
  render plain: 'Foo'
end

ActiveSupport::Notifications.subscribe('render') do |name, start, finish, id, payload|
  name    # => String, name of the event (such as 'render' from above)
  start   # => Time, when the instrumented block started execution
  finish  # => Time, when the instrumented block ended execution
  id      # => String, unique ID for this notification
  payload # => Hash, the payload
end
```

BTW: Temporary Subscriptions

> You can subscribe to some event temporarily while some block runs. For example, in

```
callback = lambda {|*args| ... }
ActiveSupport::Notifications.subscribed(callback, "sql.active_record") do
  ...
end
```

> the callback will be called for all “sql.active_record” events instrumented during the execution of the block. The callback is unsubscribed automatically after that.

from: http://api.rubyonrails.org/classes/ActiveSupport/Notifications.html

I prefer my `within` proposal ;)

**Comment by paneq** [comment]
I was not sure why in the original issue I proposed `execute`... But maybe to allow chaining multiple subscriptions.

```
event_store.within do
  cancel_order.call(order_id, user_id)
end.subscribe(OrderCancelled) do |event|
  head :ok
end.subscribe(OrderCancelled) do |event|
  render json: {error: "doh"}
end.execute
```

Alternatives: `run`, `call`

**Comment by pawelpacana** [comment]
> Alternatives: run, call

`call` will always be idiomatic in Ruby

**Comment by paneq** [comment]
It's baking. Soon
