### ISSUE TITLE
Create new release for `ruby_event_store-rom`

### ISSUE THREAD

**Issue by leoarnold** [RailsEventStore/rails_event_store#1582]
The current version of the `ruby_event_store-rom` gem is `2.0.0`. In that release, the `db:setup` task is broken. The problem was already fixed two years ago:

https://github.com/RailsEventStore/rails_event_store/pull/1262

It would be nice to have a non-broken version of `ruby_event_store-rom` as the current release.

**Comment by pawelpacana** [comment]
New version has been released, enjoy!

- https://rubygems.org/gems/ruby_event_store-rom
- https://github.com/RailsEventStore/rails_event_store/blob/master/contrib/ruby_event_store-rom/CHANGELOG.md#210
