### ISSUE TITLE
Rspec issue when testing with have_subscribed_to_events

### ISSUE THREAD

**Issue by remoteweb** [RailsEventStore/rails_event_store#1666]
Dear fellows,

i've been having some strange issues trying to test that my handler is subscribed to the event.

## Steps to reproduce 
Using the documentation instructions i am testing with the following

```
expect(OnHubCompanyUpdated::SyncCompany).to have_subscribed_to_events(HubCompanyUpdated).in(event_store)
```

## Expected
To pass

## Current
Rspec Is throwing error

```
Failure/Error: expect(::OnHubCompanyUpdated::SyncCompany).to have_subscribed_to_events(HubCompanyUpdated).in(event_store)

       expected OnHubCompanyUpdated::SyncCompany to be subscribed to events, diff:
       @@ -1 +1,2 @@
       +[HubCompanyUpdated]
```

## Additional Information

Subscriber is defined like this
```
module OnHubCompanyUpdated
  class SyncCompany
    def call(event)
      ## code to be executed
    end
  end
end

```

binding pry on the following line
https://github.com/RailsEventStore/rails_event_store/blob/c7e39ef8bf141d2d2bfbfa6e5b27e3230f18e5ed/ruby_event_store-rspec/lib/ruby_event_store/rspec/have_subscribed_to_events.rb#L15C106-L15C106

```
tes [1] pry(#<RubyEventStore::RSpec::HaveSubscribedToEvents>)> handler
=> OnHubCompanyUpdated::SyncCompany

tes [2] pry(#<RubyEventStore::RSpec::HaveSubscribedToEvents>)> expected
=> [HubCompanyUpdated]

tes [3] pry(#<RubyEventStore::RSpec::HaveSubscribedToEvents>)> event_store.subscribers_for(expected.first)
=> [#<OnHubCompanyUpdated::SyncCompany:0x00000001201f6e88>,
 #<RailsEventStore::LinkByEventType:0x00000001201f5808 @event_store=#<RailsEventStore::JSONClient:0x2d8ac>, @prefix="$by_type_">,
 #<RailsEventStore::LinkByCorrelationId:0x00000001201f4e30
  @event_store=#<RailsEventStore::JSONClient:0x2d8ac>,
  @key=:correlation_id,
  @prefix="$by_correlation_id_">,
 #<RailsEventStore::LinkByCausationId:0x00000001201f46b0
  @event_store=#<RailsEventStore::JSONClient:0x2d8ac>,
  @key=:causation_id,
  @prefix="$by_causation_id_">]
```

This check will always fail 
```
@subscribed_to = expected.select { |event| event_store.subscribers_for(event).include?(handler) }
```

If I define the subscribes to event with the following code
```
store.subscribe(OnHubCompanyUpdated::SyncCompany, to: [HubCompanyUpdated])
```

The test will pass but the definition is different than in docs.

Any ideas?

**Comment by pjurewicz** [comment]
Hey @remoteweb, thanks for posting!
I'm not sure if I get it. Did you expect a subscription to exist without explicitly defining it?
What do you mean by "definition is different than in docs"?

**Comment by remoteweb** [comment]
Thanks for you quick reply and assignment.

I expect the subscriber to exist and I think it does exist as I have binding.pry inside the matcher and I get this

```
tes [3] pry(#<RubyEventStore::RSpec::HaveSubscribedToEvents>)>  event_store.subscribers_for(expected.first)

[#<OnHubCompanyUpdated::SyncCompany:0x00000001201f6e88>, ...]

```

The test is
```
expect(OnHubCompanyUpdated::SyncCompany).to have_subscribed_to_events(HubCompanyUpdated).in(event_store)
```

**Comment by pjurewicz** [comment]
Thanks, now I get it. Will review this assertion definition soon.

**Comment by pjurewicz** [comment]
Minimal code to reproduce your case:

```ruby
  it 'got subscribed' do
    event_store.within do
      expect(SyncCompany).to have_subscribed_to_events(HubCompanyUpdated).in(event_store)
    end.subscribe(SyncCompany, to: [HubCompanyUpdated]).call
  end
 ```
 ⬆️ this test passes 🟢 
 
 ```ruby
   it 'got subscribed' do
    event_store.within do
      expect(SyncCompany).to have_subscribed_to_events(HubCompanyUpdated).in(event_store)
    end.subscribe(SyncCompany.new, to: [HubCompanyUpdated]).call
  end
 ```
  ⬆️ this one fails 🔴 
  
  It is tricky, but I do not consider this as an issue. In the second case, you pass a certain instance of SyncCompany class to `subscribe` method. To test this subscription properly, you should pass the same instance to the assertion.
```ruby
  it 'got subscribed' do
    handler = SyncCompany.new
    event_store.within do
      expect(handler).to have_subscribed_to_events(HubCompanyUpdated).in(event_store)
    end.subscribe(handler, to: [HubCompanyUpdated]).call
  end
```
⬆️ this test passes 🟢 

If you don't care about a stateful handler, you should rather pass a class to the `subscribe` method.
The difference between those two is described in [this section of the documentation](https://railseventstore.org/docs/v2/subscribe/#fresh-handler-state).

Perhaps the documentation should focus more on stateless subscription handlers, as they are the norm. Thank you for pointing it out.

**Comment by remoteweb** [comment]
🙏 Thanks for the time put in to add this great explanation. I was falsely expecting the spec helpers to handle all cases by default and I missed to understand properly all different handler configurations.
