### ISSUE TITLE
NoMethodError when using `RubyEventStore::RSpec::Publish` matcher with `InMemoryRepository` and preceding events

### ISSUE THREAD

**Issue by silvabox** [RailsEventStore/rails_event_store#1670]
When using the `Publish` matcher in the following manner:
```ruby
before do
  # some code that publishes an event to `other_event_stream`
end

# ...

expect { subject }.to publish(SomeEvent)
  .in(event_store)
  .in_stream(stream_name)
```
...using the `InMemoryRepository`, we get the error `NoMethodError: undefined method '+' for nil:NilClass`.

This happens as a result of the call in `Publish`:
```ruby
      def matches?(event_proc)
        fetch_events.from_last
        event_proc.call
        stream_names.all? do |stream_name|
          fetch_events.stream(stream_name)
```
The initial call to `fetch_events.from_last` will set the `spec.start` to an `event_id` from an arbitrary stream published to in the preamble (in this example a `before` block. A `let!` block has the same effect).
The subsequent `fetch_events.stream(stream_name)` then causes an error in `InMemoryRepository:153`:
```ruby
      serialized_records = serialized_records.drop(index_of(serialized_records, spec.start) + 1) if spec.start
```
since `index_of(serialized_records, spec.start)` is `nil` (i.e. `nil + 1`)

I would propose that if the event specified in `spec.start` is not present in `serialized_records`, then it should simply iterate from the beginning of the collection.

**Comment by pjurewicz** [comment]
Hello @silvabox! Thank you very much for sharing this problem.
I've just managed to reproduce your case with this simple test:

```ruby
      specify do
        event_store.publish(FooEvent.new, stream_name: "Foo$1")
        expect do
          event_store.publish(FooEvent.new, stream_name: "Foo$2")
        end.to publish(FooEvent)
                 .in(event_store)
                 .in_stream("Foo$2")
      end
```

We are working on a fix.

**Comment by silvabox** [comment]
That's fantastic, thank you @pjurewicz for responding so quickly 😌

**Comment by pjurewicz** [comment]
The issue you've experienced is resolved on master with commit: https://github.com/RailsEventStore/rails_event_store/commit/5b1d38dd1ba54af12a6ac9d3ba930b79e7bf6bbf

We will release it officially soon, but you can start using it right away with this entry in your Gemfile (with some other minor changes included):
```
gem "rails_event_store", github: "RailsEventStore/rails_event_store", ref: "5b1d38d"
```
