### ISSUE TITLE
RubyEventStore::Projection reads only 100 first events by default

### ISSUE THREAD

**Issue by vbyno** [RailsEventStore/rails_event_store#173]
RubyEventStore::Projection reads only 100 first events by default. 
```
    # class RubyEventStore::Projection
    def run(event_store, start: :head, count: PAGE_SIZE)
      if streams.any?
        reduce_from_streams(event_store, start, count)
      else
        reduce_from_all_streams(event_store, start, count)
      end
    end
```
It is not described in the [documentation](http://railseventstore.org/docs/projection/). And even if it were described, I don't think it is a correct behavior for the projection. IMHO, all events from the stream should be read. What are your ideas concerning that?

**Comment by andrzejkrzywda** [comment]
This was trolling me so many times. I'd vote for explicit 2 methods, one like `run_with_pagination` and the default `run_all` or just `run`.

**Comment by paneq** [comment]
Why would anyone run not full projection at all? What would be the usecase? Shouldn't pagination be an internal implementation detail for the projection?

**Comment by vbyno** [comment]
<Why would anyone run not full projection at all?
That was a question I was asking myself too. But there is one more problem. The constant is called `PAGE_SIZE` but actually, there is no pagination. Events are not being found in the batches. It is just a limitation for one query.
So, what would you vote for? I'd change `run` to get all events from stream/streams for the start. In future, maybe, it worths being implemented using `find_in_batches`

**Comment by paneq** [comment]
I would vote for 

> pagination be an internal implementation detail for the projection

and yes, it should iterate over all available events in provided stream(s)

**Comment by mpraglowski** [comment]
Yep - the starting point is ok, but paging is suboptimal. This is a problem not only here in projections. It should be replaced with some other API - maybe Enumerable or ActiveRecord like (find_each, in_groups_of, each... )

**Comment by mpraglowski** [comment]
I think the confusion is here - the `count` argument is a limit of for number fo events t be read by projection, it is not a page size. At least it is my understanding of that tests:

https://github.com/RailsEventStore/rails_event_store/blob/master/ruby_event_store/spec/projection_spec.rb#L37
https://github.com/RailsEventStore/rails_event_store/blob/master/ruby_event_store/spec/projection_spec.rb#L84

But I do not see any use case for that - page size should be used here.

**Comment by mpraglowski** [comment]
https://github.com/RailsEventStore/rails_event_store/pull/175 for discussion - `count` is now a page size not a limit

**Comment by pawelpacana** [comment]
The `count:` parameter now works as a page size.
