### ISSUE TITLE
Support for storing event data using DB-specific primitives

### ISSUE THREAD

**Issue by jasonjho** [RailsEventStore/rails_event_store#174]
Since event data is stored as a `text` using default ActiveRecord YAML serialization, this makes querying the event data a bit harder since you have to be aware of the serialization format and cannot take advantage of indexing at the database level.

Would there be a way to easily define or override the data field with DB specific types? For instance, if you're using Postgres you may want to favor `jsonb` or enable the `hstore` extension, which would allow clients of the database to more easily query the event data directly.

Any thoughts on whether something like this can be supported for future releases?

Thanks! And really great work on this project!

**Comment by paneq** [comment]
@jasonjho Did you try newest version and passing down a custom `serializer` or custom `mapper` ? http://railseventstore.org/docs/mapping_serialization/ (custom mapper is not documented yet but you can have a look at #168 to get the idea)

@andrzejsliwa I believe storing JSON was one of the reasons you implemented #154 in #168

**Comment by jasonjho** [comment]
@paneq I haven't, but thanks for forwarding! I didn't realize this functionality existed. Looks quite promising. Quick follow up q: Do the custom serialized formats still get stored as `text`? Or will we be able to somehow define a new datatype at the schema level, such as `jsonb`?

**Comment by paneq** [comment]
@jasonjho they do by default but I don't see a reason why you should not be able to change the column type :) Give it a try and tell us how it worked.

**Comment by jasonjho** [comment]
Great, thanks! Closing since I believe this is addressable via the extensible serializers.
