### ISSUE TITLE
Timezones not working (for me)

### ISSUE THREAD

**Issue by casiodk** [RailsEventStore/rails_event_store#1753]
When using timezone in a browser in copenhagen/europe timezone, UTC is the only timezone available.

Is it possible to add the default timezone, + available timezones in an initializer instead?

![Screenshot 2024-03-18 at 10 24 17](https://github.com/RailsEventStore/rails_event_store/assets/632607/36055d49-f0ed-42f4-b2fe-61e9ba24b5fb)

![Screenshot 2024-03-18 at 10 28 01](https://github.com/RailsEventStore/rails_event_store/assets/632607/45b53d64-f1ff-499f-90fd-fc83793f8946)

Related to https://github.com/RailsEventStore/rails_event_store/pull/1727 https://github.com/RailsEventStore/rails_event_store/issues/1723

**Comment by casiodk** [comment]
Is this available now? @porbas :)

**Comment by lukaszreszke** [comment]
Hey @casiodk. It is not yet released. We're planning to do that soon. I'll ping you here once release new version.

**Comment by lukaszreszke** [comment]
@casiodk we just released v2.15.0 that contains the improvement. Please let us know if it works fine for you.

**Comment by casiodk** [comment]
Ohhh yeah, its awesome :) Thanks a lot!

**Comment by casiodk** [comment]
:)
