### ISSUE TITLE
Async handlers enqueueing jobs twice in development mode

### ISSUE THREAD

**Issue by jasonjho** [RailsEventStore/rails_event_store#176]
I have the following in a Rails initializer:

```Rails.configuration.to_prepare do
  # Configure event store to schedule async handlers after commit
  unless defined? EventStore
    Rails.configuration.event_store = EventStore = RailsEventStore::Client.new(
      event_broker: RailsEventStore::EventBroker.new(
        dispatcher: RailsEventStore::ActiveJobDispatcher.new(
           proxy_strategy: RailsEventStore::AsyncProxyStrategy::AfterCommit.new
        )
      )
    )
  end

  EventStore.subscribe(AsyncEventHandlers::EmailWelcomeUserHandler, [Events::UserAccountCreated])
end
```

When code is reloaded during development by making a change to handler code, I'm noticing that the ActiveJob handler is invoked twice, which is not desirable.

Anything I am doing wrong here?

**Comment by jasonjho** [comment]
Apologies, this was due to caching the assignment. However, does this mean that calling `subscribe` multiple times on the same handler causes multiple subscriptions?

**Comment by paneq** [comment]
@jasonjho 

yes, calling:

```ruby
event_store.subscribe(AsyncEventHandlers::EmailWelcomeUserHandler, [Events::UserAccountCreated]
event_store.subscribe(AsyncEventHandlers::EmailWelcomeUserHandler, [Events::UserAccountCreated]
```

will subscribe the handler twice to the event.

**Comment by paneq** [comment]
@jasonjho btw are you using `to_prepare` as recommended in http://railseventstore.org/docs/install/
