### ISSUE TITLE
AsyncRecord missing method `add_to_transaction`

### ISSUE THREAD

**Issue by jasonjho** [RailsEventStore/rails_event_store#181]
We're using `aasm` transitions within our AR models and sometimes during a chain of `after:` callbacks, we push an event to the EventStore. However, if there is a corresponding Async handler that is listening for that event using the `AsyncProxyStrategy`, we run into the following error:

```
NoMethodError:
     undefined method `add_to_transaction' for #<RailsEventStore::AsyncProxyStrategy::AfterCommit::AsyncRecord:0x00007fa2cec1f188>
....
```

I suspect the issue is because `AsyncRecord` tries to quack like a transaction record (in order to ensure that handlers are run `after_commit`), but there is a corner case (https://github.com/rails/rails/blob/v5.1.4/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb#L89) where the unknown method `add_to_transaction` method is invoked.

I believe the fix is to simply add an empty `add_to_transaction` method on `AsyncRecord`. I don't think any logic has to actually be added in that method.

It would be great to verify this issue, as we're seeing it in production. We are running Rails 5.1.4 and RailsEventStore 0.19.0

Thanks!

**Comment by paneq** [comment]
> I suspect the issue is because AsyncRecord tries to quack like a transaction record (in order to ensure that handlers are run after_commit), but there is a corner case 

indeed it does.

> but there is a corner case (https://github.com/rails/rails/blob/v5.1.4/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb#L89) where the unknown method add_to_transaction method is invoked.

shiiiit...

> I believe the fix is to simply add an empty add_to_transaction method on AsyncRecord. I don't think any logic has to actually be added in that method.

I am trying to verify it now by checking what ActiveRecord does and why.

Thank you for bringing this to our attention.

**Comment by paneq** [comment]
* https://github.com/rails/rails/blob/v5.1.4/activerecord/lib/active_record/transactions.rb#L363

```ruby
    def add_to_transaction
      if has_transactional_callbacks?
        self.class.connection.add_transaction_record(self)
      else
        sync_with_transaction_state
        set_transaction_state(self.class.connection.transaction_state)
      end
      remember_transaction_record_state
    end

    private

      # Save the new record state and id of a record so it can be restored later if a transaction fails.
      def remember_transaction_record_state
        @_start_transaction_state[:id] = id
        @_start_transaction_state.reverse_merge!(
          new_record: @new_record,
          destroyed: @destroyed,
          frozen?: frozen?,
        )
        @_start_transaction_state[:level] = (@_start_transaction_state[:level] || 0) + 1
      end
```

**Comment by paneq** [comment]
```
    # Call the #after_commit callbacks.
    #
    # Ensure that it is not called if the object was never persisted (failed create),
    # but call it after the commit of a destroyed object.
    def committed!(should_run_callbacks: true) #:nodoc:
      if should_run_callbacks && destroyed? || persisted?
        _run_commit_without_transaction_enrollment_callbacks
        _run_commit_callbacks
      end
    ensure
      force_clear_transaction_record_state
    end
```

**Comment by paneq** [comment]
rails 5.0 affected as well:

* https://github.com/rails/rails/blob/v5.0.4/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb#L90
* https://github.com/rails/rails/blob/v5.0.4/activerecord/lib/active_record/transactions.rb#L374

**Comment by paneq** [comment]
Rails 4.2 did not have that logic:

```
      def commit_records
        ite = records.uniq
        while record = ite.shift
          begin
            record.committed!
          rescue => e
            raise if ActiveRecord::Base.raise_in_transactional_callbacks
            record.logger.error(e) if record.respond_to?(:logger) && record.logger
          end
        end
      ensure
        ite.each do |i|
          i.committed!(false)
        end
```

but it could call `committed!(false)` ...

**Comment by paneq** [comment]
Investigating when in rails 5 this method is called:

```ruby

      def commit_records
        ite = records.uniq
        while record = ite.shift
          if @run_commit_callbacks
            record.committed!
          else
            # if not running callbacks, only adds the record to the parent transaction
            record.add_to_transaction
          end
        end
      ensure
        ite.each { |i| i.committed!(should_run_callbacks: false) }
      end
```

so `@run_commit_callbacks` must be false.

```
      def begin_transaction(options = {})
        @connection.lock.synchronize do
          run_commit_callbacks = !current_transaction.joinable?
          transaction =
            if @stack.empty?
              RealTransaction.new(@connection, options, run_commit_callbacks: run_commit_callbacks)
            else
              SavepointTransaction.new(@connection, "active_record_#{@stack.size}", options,
                                       run_commit_callbacks: run_commit_callbacks)
            end

          @stack.push(transaction)
          transaction
        end
      end

      def commit_transaction
        @connection.lock.synchronize do
          transaction = @stack.last

          begin
            transaction.before_commit_records
          ensure
            @stack.pop
          end

          transaction.commit
          transaction.commit_records
        end
```

so it depends on `!current_transaction.joinable?`

**Comment by paneq** [comment]
```ruby
    class NullTransaction #:nodoc:
      def joinable?; false; end
    end

    class Transaction #:nodoc:
      attr_reader :connection, :state, :records, :savepoint_name
      attr_writer :joinable

      def initialize(connection, options, run_commit_callbacks: false)
        @connection = connection
        @state = TransactionState.new
        @records = []
        @joinable = options.fetch(:joinable, true)
        @run_commit_callbacks = run_commit_callbacks
      end
        
      def joinable?; @joinable; end

end

**Comment by paneq** [comment]
Not overwritten in SavepointTransaction and RealTransaction

**Comment by paneq** [comment]
So... `run_commit_callbacks = !current_transaction.joinable?`

* When `current_transaction` is `NullTransaction` then `joinable?` is `false` then `run_commit_callbacks` is `true`.

* When `current_transaction` is `Transaction` then `joinable?` is `true` (from what I see) then `run_commit_callbacks` is `false`.

**Comment by paneq** [comment]
So maybe this can be replicated by invoking nested transactions, let me try.

**Comment by paneq** [comment]
Reproduced with:

```
    it "async proxy for defined adapter enqueue job only after top-level transaction commit" do
      dispatcher = ActiveJobDispatcher.new(proxy_strategy: AsyncProxyStrategy::AfterCommit.new)
      expect_to_have_enqueued_job(AsyncHandler) do
        ActiveRecord::Base.transaction do
          expect_no_enqueued_job do
            ActiveRecord::Base.transaction(requires_new: true) do
              dispatcher.call(AsyncHandler, event)
            end
          end
        end
      end
      expect(AsyncHandler.received).to be_nil
      perform_enqueued_jobs(AsyncHandler.queue_adapter)
      expect(AsyncHandler.received).to eq(yaml)
    end
```

**Comment by paneq** [comment]
Tests and fix in #3feb47d . I wonder how it behaves in Rails 4.2 which does not have this method...

**Comment by paneq** [comment]
As to `committed!(false)` and `committed!(should_run_callbacks: false)` , my current understanding is that it can happen when previous AR record added to transaction raises an exception in transactional callback and `raise_in_transactional_callbacks` is configured to `true`. Then the next records are marked as commited but their callbacks are not executed... 😱 I need to think about it.

**Comment by paneq** [comment]
When rails 4.2 && `ActiveRecord::Base.raise_in_transactional_callbacks = true`

then

```
~/d/r/rails_event_store (after_commit_nested_transactions|✚1) $ 
env RAILS_VERSION=4.2.9 bundle exec rspec spec/active_job_dispatcher_spec.rb
.......true
F...

Failures:

  1) RailsEventStore::ActiveJobDispatcher async proxy for defined adapter do not enqueue job after nested transaction rollback
     Failure/Error:
       def rolledback!(**_)
       end
     
     ArgumentError:
       wrong number of arguments (given 1, expected 0)
```

**Comment by jasonjho** [comment]
Thank you for being so prompt with this! Appreciate the migration steps to
include the fix. Excited to try this out and thanks again for such a great
framework.

**Comment by paneq** [comment]
@jasonjho I already merged to master but I am leaving for vacations so I won't have the time to release new version to rubygems. Hopefully someone will step up in the meantime.

**Comment by pawelpacana** [comment]
@jasonjho This has just been released: https://github.com/RailsEventStore/rails_event_store/releases/tag/v0.24.0
