### ISSUE TITLE
Release 1.0

### ISSUE THREAD

**Issue by pawelpacana** [RailsEventStore/rails_event_store#185]
There has to be finally a release after which one could expect stability in terms of public API. 

Not long ago we've changed database schema heavily (0.19.0) to fix potential concurrency-related issues. That was a major blocker, at least from my perspective. So are we ready now? What else seems crucial before we freeze public API and behavior?

I'd suggest reviewing #184 and #153 as both touch public API.

**Comment by pawelpacana** [comment]
Is it the moment to remove deprecations?
Is it the moment to remove LegacyEventRepository?

**Comment by paneq** [comment]
> I'd suggest reviewing #184 and #153 as both touch public API.

👍 Agree, exactly that!

**Comment by andrzejkrzywda** [comment]
While I agree that both #184 and #153 would be nice to have improved - I'd opt for releasing 1.0 without blocking on them.

We have a nice, working system, the API is not perfect (and never will be for everybody) but we support many use cases (aggregates, linking to many streams, using read models, process managers).  There are no known bugs. It's all what I'd expect from having RES 1.0.

My suggestion - let's release 1.0 with what we have now and include #184 and #153 as main improvements for 2.0.

Maybe we could celebrate releasing 1.0 during wroc_love.rb? :)

**Comment by mpraglowski** [comment]
I would also suggest #126 as part of 1.0 release

**Comment by pawelpacana** [comment]
Closing as we've scoped that already https://github.com/RailsEventStore/rails_event_store/milestone/3 and I doubt there's much more to discuss on this topic.

**Comment by joelvh** [comment]
@pawelpacana I'd like to get #463 or #476 completed for 1.0 so ROM has feature parity with AR.

**Comment by pawelpacana** [comment]
@joelvh That'd be cool, thanks for reminding! 

I haven't looked into `update_messages` yet but it's on my list. I'll look into #463 and #476 then.

**Comment by joelvh** [comment]
@pawelpacana ok, great. Reviewing what was proposed there, I'm going to go with the "upsert" version in #476. Might need some help with mutations, but getting things sync'd up with master right now.

Thanks.
