### ISSUE TITLE
HavePublished matches? bug 

### ISSUE THREAD

**Issue by xichen27** [RailsEventStore/rails_event_store#199]
```
def matches?(event_store)`
  @events = @stream_name ? event_store.read_events_backward(@stream_name) : event_store.read_all_streams_backward
  @matcher.matches?(@events) && matches_count(@events, @expected, @count)
end
```

Should be `event_store.read_stream_events_backward(@stream_name)`. `read_events_backward` takes three params.

**Comment by xichen27** [comment]
@paneq Thanks for looking into it. You were right. I used Repository instead of RES::Client in the rspec tests.

**Comment by paneq** [comment]
@xichen27 I am glad you got it figured. We would be happy if you fill out our poll about RES usage: https://goo.gl/forms/ecNpJsL5qM2M8Ls93 if you haven't yet :) Thank you and have a great day!
