### ISSUE TITLE
How should declarative aggregate event handlers deal with event inheritance

### ISSUE THREAD

**Issue by paneq** [RailsEventStore/rails_event_store#202]
```
class A
end

class B < A
end

class Order
  include AggregateRoot

  on A do |ev|
  end
end
```

can `on A` handle event `B` ?

Related #171 #190 @andrzejsliwa

**Comment by pawelpacana** [comment]
I'm not entirely sure what inheritance brings into this scenario. Each event has a distinct `type` and that is what a handler is interested in.
