### ISSUE TITLE
rails_event_store_active_record dependency on rails

### ISSUE THREAD

**Issue by paneq** [RailsEventStore/rails_event_store#205]
RES AR uses `rails/generators`:
https://github.com/RailsEventStore/rails_event_store/blob/df8383520e83f22fde22f932652a372ab61ed1d7/rails_event_store_active_record/lib/rails_event_store_active_record/generators/v1_v2_migration_generator.rb#L1 but it is not listed as its dependency.

We should probably either make Rails a dependency or split into two gems:
* `ruby_event_store_active_record` - without rails dependency and without generators. Could assume schema X to be present when used.
* `rails_event_store_active_record` - which would depend on ruby_event_store_active_record and rails and contain the generator/migration code which is actually rails specific.

This is generally annoying because it is not the first time I want to use RES AR from a ruby script and it forces me to have Rails as dependency just so it can load generators.

Perhaps the dependency could be optional?:

```ruby
if defined?(Rails)
  require 'rails_event_store_active_record/generators/migration_generator'
  require 'rails_event_store_active_record/generators/v1_v2_migration_generator'
end
```

I am not sure how it works in practice though...

**Comment by pawelpacana** [comment]
Perhaps we could move generators to `rails_event_store` gem.

**Comment by paneq** [comment]
Indeed, I forgot to mention that option as well.

**Comment by paneq** [comment]
I wonder if that would make `rails_event_store` depend on `active_record` or not... On the other hand it might already depend on it...

**Comment by andrzejkrzywda** [comment]
I like the option of moving the generators to `rails_event_store`.

It sounds like this would let `rails_event_store_active_record` be used without Rails. At the same time `rails_event_store` can keep all rails-related code, generators, magic, hacks.

**Comment by paneq** [comment]
Idea:

```
Does using Thor directly make any sense for the generators task?  https://github.com/erikhuda/thor/wiki/Generators
```

**Comment by andrzejkrzywda** [comment]
Would it work if instead of calling the migration generator directly (thus introducing the dependency) we just explain to people how to invoke the correct migration from the command line and/or show the code to paste into the migration?

**Comment by paneq** [comment]
```ruby
begin
  require 'rails/generators'
  # define V1V2MigrationGenerator
rescue LoadError
  # do nothing if rails unavailable
end
```
