### ISSUE TITLE
Promote public hackathon before wroc_love.rb 16.03, Friday, 10:15 - 17:00

### ISSUE THREAD

**Issue by paneq** [RailsEventStore/rails_event_store#207]
Room: 108

**Comment by pawelpacana** [comment]
![res-hackathon](https://user-images.githubusercontent.com/116740/37032393-a9cd84b6-2142-11e8-8f60-1993ecfdc83c.png)

**Comment by pawelpacana** [comment]
https://twitter.com/pawelpacana/status/971002644440539137
