### ISSUE TITLE
Pass RES client instance to Browser

### ISSUE THREAD

**Issue by pawelpacana** [RailsEventStore/rails_event_store#214]
It would be useful to be allowed to pass particular RES client instance to browser. Currently we look into usual place and that works for most of us:
https://github.com/RailsEventStore/rails_event_store/blob/2eb821c73cc3c6aa63dfe3a9680a0b689ae71193/rails_event_store-browser/app/controllers/rails_event_store/browser/application_controller.rb#L8-L10

I could however imagine having client instance with configurations somewhere else.

**Comment by pawelpacana** [comment]
One way to do it: https://stackoverflow.com/questions/20734766/rails-mountable-engine-how-should-apps-set-configuration-variables

**Comment by pawelpacana** [comment]
If Browser was _just_ a Rack app, then we could probably pass initialized app instance here: http://api.rubyonrails.org/classes/ActionDispatch/Routing/Mapper/Base.html#method-i-mount

But it's a Rails Engine so likely dragons on that way. Ideas?

**Comment by pawelpacana** [comment]
Done in new browser version.

**Comment by joelvh** [comment]
Didn’t even see this ticket before the rework!
