### ISSUE TITLE
Revert silly attr_reader-to-ivar change in order to fix Ruby 2.2 warnings

### ISSUE THREAD

**Issue by pawelpacana** [RailsEventStore/rails_event_store#215]
In commit https://github.com/RailsEventStore/rails_event_store/commit/4b77b2ee4c2a7139b6cc88016127c35395bbd227, as a followup to https://github.com/RailsEventStore/rails_event_store/commit/e999471ec3251a7748a3e674143ce4ae219b3534 I've introduced change that supressed Ruby 2.2 warnings. 

However there was much doubt involved in this change. After some time and considering such code does not lead to warning on Rubies above version 2.2 I'd rather skip this particular warning simillarly to: https://github.com/RailsEventStore/rails_event_store/commit/413a45105e282728f377401f547da4bfcdecc817 or 

```ruby
RSpec.describe 'Ruby warnings' do
  matcher :not_complain do
    match do |actual|
      expect(actual).to eq([])
    end

    failure_message do |actual|
      actual.join("\n")
    end
  end

  specify do
    expect(app_warnings).to not_complain
  end

  def app_warnings
    warnings.select { |w| w =~ /\A\s*#{Rails.root}/ }
      .reject(&method(:private_attribute))
  end

  def warnings
    `ruby -w config/environment.rb 2>&1`.split("\n")
  end

  private
  def private_attribute(warning)
    RUBY_VERSION < '2.3.0' && warning =~ /warning: private attribute\?/
  end
end
```

**Comment by paneq** [comment]
👍 

I think we could just not run this test at all for ruby 2.2 and have no need to filter out any errors for higher rubies.
