### ISSUE TITLE
Consider moving railseventstore.org to monorepo

### ISSUE THREAD

**Issue by pawelpacana** [RailsEventStore/rails_event_store#216]
It is very common to introduce change both in code and docs. It would be easier to manage such changes in one repo.

**Comment by paneq** [comment]
I was wondering the same and I was inclined to do it, but I was not sure if it does not negatively affect deployment of documentation changes.

**Comment by pawelpacana** [comment]
I've tested one possible approach (migrating from surge to netlify) and such setup would work there.

**Comment by pawelpacana** [comment]
- [ ] repo moved with history
- [ ] issues moved
- [ ] deployment of master works
- [ ] old repo marked as obsolete

Bonus: 
- [ ] branch deploys (dynamic subdomain)
- [ ] deploy notifications with URL for preview
