### ISSUE TITLE
Experiment with metadata-driven streams

### ISSUE THREAD

**Issue by pawelpacana** [RailsEventStore/rails_event_store#221]
One could image forming streams based on some metadata values.

For example if we record in metadata:
- requester IP address
- logged-in user
- `correlation_id`, `request_id` or any other identifier of single activity

we could then partition streams by this metadata:
- everything that happened manifested by domain events with the same `correlation_id`
- all events originating from single IP address
- all events of particular user revealing flows of events in the system

Might be related to: https://github.com/RailsEventStore/rails_event_store/issues/72#issuecomment-326513289

**Comment by paneq** [comment]
This might require:

* exposing metadata API that can be used for events inheriting from `RubyEventStore::Event` and protobuf defined events
  * exposing in repository
  * exposing in mappers
* writing a global handler/subscriber (configurable?) that would link to stream based on event metadata (which one? all?). What convention should it use for stream names? Maybe `$#{metadata_key}-#{metadata_value}` ?

**Comment by pawelpacana** [comment]
https://github.com/EventStore/EventStore/pull/1622

**Comment by pawelpacana** [comment]
👍
