### ISSUE TITLE
Discussion: starter-kit to kickstart RES development in greenfield

### ISSUE THREAD

**Issue by pawelpacana** [RailsEventStore/rails_event_store#224]
We've started https://github.com/RailsEventStore/starter-kit but not much happened there afterwards. How do we want to keep-it up-to-date? 

What's the target audience for this kit?

**Comment by pawelpacana** [comment]
Could it include all examples from RES docs?

**Comment by paneq** [comment]
> Could it include all examples from RES docs?

Like publishing events, a handler, an async handler etc?

**Comment by pawelpacana** [comment]
Something related — we now have a rails template that can be used while generating new application. 

See: https://railseventstore.org/new
