### ISSUE TITLE
ruby_event_store mutation testing have been failing for everyone recently

### ISSUE THREAD

**Issue by paneq** [RailsEventStore/rails_event_store#231]
https://www.dropbox.com/s/5x63t2yxzvc7xj7/Screenshot%202018-03-17%2013.44.33.png?dl=0

**Comment by paneq** [comment]
Example https://travis-ci.org/RailsEventStore/rails_event_store/jobs/354694165 , passed locally for me

**Comment by paneq** [comment]
@pawelpacana Can you reproduce locally on `no_global_repo` branch?

**Comment by paneq** [comment]
Example 2: https://travis-ci.org/RailsEventStore/rails_event_store/builds/354834684?utm_source=github_status&utm_medium=notification

**Comment by paneq** [comment]
not only i cannot reproduce locally but also

```
# RSpec.configure do |config|
#   config.around(:each) do |example|
#     Timeout.timeout(5, &example)
#   end
# end
```

when I comment this out the mutation testing still passes locally.

**Comment by paneq** [comment]
https://github.com/mbj/mutant#the-crash--stuck-problem-mri says (about older ruby)

> MRI crashes with a segfault and gets stuck when handling the segfault. Depending on the number of active kill jobs mutant might appear to continue normally until all workers are stuck into this state when it begins to hang. Currently mutant must assume that your test suite simply not terminated yet as from the outside (parent process) the difference between a long running test and a stuck MRI is not observable. Its planned to implement a timeout enforced from the parent process, but ideally MRI simply gets fixed.

Perhaps this is what is happening with one mutation. Maybe because we have protobuf which is implemented as a C extension.

**Comment by paneq** [comment]
```
[32m(1241/4170) 100% - killtime: 145.01s runtime: 2757.70s overhead: 2612.69s[0m
1214
evil:RubyEventStore::Client::Within#call:/home/travis/build/RailsEventStore/rails_event_store/ruby_event_store/lib/ruby_event_store/client.rb:154:f5e03
1242
evil:RubyEventStore::Client::Within#call:/home/travis/build/RailsEventStore/rails_event_store/ruby_event_store/lib/ruby_event_store/client.rb:154:cf2d2
[32m(1241/4170) 100% - killtime: 145.01s runtime: 2758.70s overhead: 2613.69s[0m
```

in https://travis-ci.org/RailsEventStore/rails_event_store/jobs/355120836 :(

**Comment by paneq** [comment]
```
(3214/4170) 100% - killtime: 540.44s runtime: 1073.34s overhead: 532.90s
1214
evil:RubyEventStore::Client::Within#call:/home/travis/build/RailsEventStore/rails_event_store/ruby_event_store/lib/ruby_event_store/client.rb:154:f5e03
3218
evil:RubyEventStore::Projection#reduce_from_streams:/home/travis/build/RailsEventStore/rails_event_store/ruby_event_store/lib/ruby_event_store/projection.rb:78:6a0ec
```

in retried https://travis-ci.org/RailsEventStore/rails_event_store/jobs/355120836

**Comment by paneq** [comment]
this part of code uses

```
        @thread_global_subscribers = Concurrent::ThreadLocalVar.new([])
        @thread_subscribers = Concurrent::ThreadLocalVar.new do
          Hash.new {|hsh, key| hsh[key] = [] }
        end
```

under the hood and maybe that's related.

**Comment by paneq** [comment]
https://www.dropbox.com/s/fxsjbmjoxsaraf8/Screenshot%202018-03-19%2018.09.03.png?dl=0

```
(17/202) 100% - killtime: 2.37s runtime: 3.39s overhead: 1.02s
18
f5e03
def call
  unsubs = @global_subscribers.map do |s|
    self
  end
  unsubs += @subscribers.map do |handler, types|
    @event_broker.add_thread_subscriber(handler, types)
  end
  @block.call
ensure
  unsubs.each(&:call)
end
```

found thanks to: https://www.dropbox.com/s/91fuyd3xjxxpa08/Screenshot%202018-03-19%2018.10.07.png?dl=0

**Comment by paneq** [comment]
I changed locally:

```
specify "temporary subscriptions don't affect other threads", mutant: false do
```

as mbj recommended.

If i manually introduce the change which mutant introduces and run

```
bundle exec rspec  --format documentation --tag ~@mutant:false
```

then rspec never finishes.

**Comment by paneq** [comment]
`bundle exec rspec  --format documentation --tag ~@mutant:false spec/subscription_spec.rb` is enough to reproduce with the mutation introduced.

**Comment by paneq** [comment]
```
      def call
        unsubs = @global_subscribers.map do |s|
          # @event_broker.add_thread_global_subscriber(s)
          self
        end
        unsubs += @subscribers.map do |handler, types|
          @event_broker.add_thread_subscriber(handler, types)
        end
        @block.call
      rescue Exception
        puts $!.inspect
      ensure
        unsubs.each(&:call)
      end
```

causes

```
#<RSpec::Core::ExampleProcsy "with many subscribers they are called in the order events were published">
  with many subscribers they are called in the order events were published
#<RSpec::Core::ExampleProcsy "dynamic global subscription via proxy">
#<RubyEventStore::EventDuplicatedInStream: RubyEventStore::EventDuplicatedInStream>
#<RubyEventStore::EventDuplicatedInStream: RubyEventStore::EventDuplicatedInStream>
#<RubyEventStore::EventDuplicatedInStream: RubyEventStore::EventDuplicatedInStream>
#<RubyEventStore::EventDuplicatedInStream: RubyEventStore::EventDuplicatedInStream>
#<RubyEventStore::EventDuplicatedInStream: RubyEventStore::EventDuplicatedInStream>
#<RubyEventStore::EventDuplicatedInStream: RubyEventStore::EventDuplicatedInStream>
#<RubyEventStore::EventDuplicatedInStream: RubyEventStore::EventDuplicatedInStream>
#<RubyEventStore::EventDuplicatedInStream: RubyEventStore::EventDuplicatedInStream>
#<RubyEventStore::EventDuplicatedInStream: RubyEventStore::EventDuplicatedInStream>
```

infinite loop because `unsubs.each(&:call)` adds itself again with this mutation.

I suspect timeout is not working because operations on `Concurrent::ThreadLocalVar` somehow ignore it or are broken when it occurs.

**Comment by paneq** [comment]
Perhaps we can make `context "dynamic subscribe v2" do` a shared example and run for `Within` mutations with changed event broker?

**Comment by paneq** [comment]
I tried to do it and I substituted the broker with:

```
class InterruptableBroker < RubyEventStore::PubSub::Broker
  class ActsAsThreadLocalVar < Struct.new(:value)
  end

  def initialize(dispatcher: DEFAULT_DISPATCHER)
    super
    @thread_global_subscribers = ActsAsThreadLocalVar.new([])
    @thread_subscribers = ActsAsThreadLocalVar.new(Hash.new {|hsh, key| hsh[key] = [] })
  end
end
```

but it did not help

**Comment by paneq** [comment]
This is the problem in a nutshell and why Timeout does not help

```
require 'timeout'
def method()
  loop{}
rescue
  puts "x"
  raise
ensure
  puts "e"
  puts caller.join("\n")
  method()
end

Timeout.timeout(0.5) do
  method()
end
```

**Comment by paneq** [comment]
But i have not idea why it does not land in rescue https://www.dropbox.com/s/t9anrnhluvro21v/Screenshot%202018-03-19%2022.05.44.png?dl=0

**Comment by paneq** [comment]
Thought https://stackoverflow.com/questions/49373075/forwarding-delegating-2-arguments-in-ruby using delegating/forwarding to avoid the mutation completely ;)

**Comment by pawelpacana** [comment]
🎉

**Comment by mbj** [comment]
@mostlyobvious, @paneq Mutant now has build in worker side timeouts + a configuration option to count timeouts as covered.
