### ISSUE TITLE
Browser: show correlated events to given event you're looking at

### ISSUE THREAD

**Issue by pawelpacana** [RailsEventStore/rails_event_store#233]
It would be nice to have a tool to inspect what else happened in a request/action that triggered this particular event.

Something like this:
https://github.com/prooph/proophessor-do/blob/6e182e9a0c8ca05c32f51c781c0a29282f370568/docs/mgmt-ui/index.md

Related: #221

**Comment by swistak35** [comment]
Correlation list can be pretty lengthy to put it under the details of the event in event view.

If you don't mind, I would start with following:
* link to respective correlation stream
* list of events which were *caused* by this event. That list should be relatively short, but again there are probably cases where it can have 1000s of entries (in some batch-processing example). In that case, I'd set some reasonable constraint "if causation stream is longer than 20 events, display only link to it".

WDYT?
