### ISSUE TITLE
Please document use of InMemoryRepository

### ISSUE THREAD

**Issue by pawelpacana** [RailsEventStore/rails_event_store#240]
_From @replaid on January 9, 2018 18:35_

http://railseventstore.org/docs/repository/

Please document InMemoryRepository here:

* That it exists
* What it's good for and not
* Do I need to create a new store object for tests that use it?
* Or is it best to use `RailsEventStore.event_repository =` in an RSpec `around` block to set the repo to InMemoryRepository and then replace it with the old one?
  

_Copied from original issue: RailsEventStore/railseventstore.org#15_

**Comment by paneq** [comment]
@replaid Done :)
