### ISSUE TITLE
Add AS::Notifications instrumentation

### ISSUE THREAD

**Issue by paneq** [RailsEventStore/rails_event_store#244]
* Aggregate sourcing time
* Handler time
* event storing time

Related: #73 #90

**Comment by pawelpacana** [comment]
- serialization time

**Comment by pawelpacana** [comment]
- process manager / saga completion time and event receiving intervals

**Comment by paneq** [comment]
I was looking at #90

and its first case `publish_events`.

```
    def publish_events(events, stream_name: GLOBAL_STREAM, expected_version: :any)
      append_to_stream(events, stream_name: stream_name, expected_version: expected_version)
      events.each do |ev|
        event_broker.notify_subscribers(ev)
      end
      :ok
    end
```

if we instrument this method it's an aggregated statistic for storing events + scheduling async handlers + processing sync handlers. I am not sure how valuable such an aggregated statistic is.

I was thinking.... Perhaps it's best to start with low-level stats. We already know the repository API, it's limited very much.

So I think maybe we could wrap `repository` into a proxy/decorator that can pass all the arguments down but also measure the time and instrument them:

```ruby
module RailsEventStore
  class Client < RubyEventStore::Client
    def initialize(repository: RailsEventStoreActiveRecord::EventRepository.new,
                   mapper: RubyEventStore::Mappers::Default.new,
                   event_broker: EventBroker.new(dispatcher: ActiveJobDispatcher.new),
                   request_metadata: default_request_metadata,
                   page_size: PAGE_SIZE)
      super(repository: repository,
            mapper: mapper,
            event_broker: event_broker,
            page_size: page_size)
      @request_metadata = request_metadata
    end

    def repository
      @instrumented_repository ||= RepositoryInstrumenterDecorator.new(super)
    end
```

or we could pass a decorated version via `super()`, whatever.

The decorator would be very simple:

```
class RepositoryInstrumenterDecorator
  def initialize(repository)
    @repository = repository
  end

  def append_to_stream(events, stream, expected_version)
    ActiveSupport::Notifications.instrument("append_to_stream.repository.rails_event_store", events: events, stream: stream) do
      repository.append_to_stream(events, stream, expected_version)
    end
  end
  
  # etc etc for link_to_stream, has_event? ...
end
```

I assume we could similarly benchmark `dispatcher` by decorating it.

@pawelpacana @andrzejkrzywda @joelvh @fmwr  what do you think?

**Comment by pawelpacana** [comment]
> Aggregate sourcing time

Moving to separate issue.

> Handler time

That's possible for sync handlers, for async we can measure scheduling time. One would have to implement it on their own in handlers

> Event storing time

Should be possible by now.
