### ISSUE TITLE
Unstable order of read events from GLOBAL_STREAM

### ISSUE THREAD

**Issue by pawelpacana** [RailsEventStore/rails_event_store#261]
See #260

**Comment by paneq** [comment]
I am not sure I understand. For GLOBAL_STREAM we explicitly order by `position, ID` but position is inserted with `NULL` so everything should be ok. `ID` is autoincremented so the order is stable within a single transaction and undetermined for concurrent writes. But linear for linear writes.

PR #260 builds test case by inserting `EventInStream` with in stream `all` with position which is not null, which should not happen in real life.

**Comment by paneq** [comment]
>  For GLOBAL_STREAM we explicitly order by position, ID

ok, some methods use just `id` which is still fine imho.

**Comment by pawelpacana** [comment]
My point is that we allow both: `repository.read_all_streams_forward(:head, 3)` and `repository.read_events_forward("all", :head, 3)` and results are different.

**Comment by pawelpacana** [comment]
Maybe the word "unstable" sets the wrong context and mental expectations. "Discrepancy" describes it probably a bit better.

Compare those two:
https://github.com/RailsEventStore/rails_event_store/blob/6d9f66d87b86842c096a03a6e8cc3fa262eaecd3/rails_event_store_active_record/spec/event_repository_spec.rb#L96-L170

**Comment by paneq** [comment]
I see, I understand better now. I assumed `read_events_forward("all"` is undefined behavior :)

I guess it's good that we specified it now. When converting to `read(spec)` the difference between `read_events_forward("all"` and `read_all_streams_forward` should disappear? Hmmm, maybe not...

**Comment by pawelpacana** [comment]
My bad, the test example wasn't telling enough. I've decided to show all readers at once:

```ruby
       expect(repository.read_all_streams_forward(:head, 3).map(&:event_id)).to eq([u1,u2,u3])
       expect(repository.read_events_forward("all", :head, 3).map(&:event_id)).to eq([u1,u2,u3])
       expect(repository.read_stream_events_forward("all").map(&:event_id)).to eq([u1,u2,u3])
 
       expect(repository.read_all_streams_backward(:head, 3).map(&:event_id)).to eq([u3,u2,u1])
       expect(repository.read_events_backward("all", :head, 3).map(&:event_id)).to eq([u3,u2,u1])
       expect(repository.read_stream_events_backward("all").map(&:event_id)).to eq([u3,u2,u1])
```
