### ISSUE TITLE
Dispatcher is not an event broker dependency

### ISSUE THREAD

**Issue by paneq** [RailsEventStore/rails_event_store#265]
Currently `RubyEventStore::PubSub::Broker` takes a `dispatcher` as a dependency. But out of 5 methods, only 1 use it:

* `add_subscriber`
* `add_global_subscriber`
* `add_thread_global_subscriber`
* `add_thread_subscriber`
* `notify_subscribers` - the only one that uses `dispatcher`

This tells us imho it is not a good dependency and we should move it higher.

### solution A - pass a `dispatcher` as an argument

```ruby
      def notify_subscribers(event, dispatcher)
        all_subscribers_for(event.type).each do |subscriber|
          dispatcher.call(subscriber, event)
        end
      end
```

### solution B - client queries the broker and calls the dispatcher

```ruby
def publish_events(events, stream_name: GLOBAL_STREAM, expected_version: :any)
  append_to_stream(events, stream_name: stream_name, expected_version: expected_version)
  notify_subscribers(events)
  :ok
end

private 

def notify_subscribers(events)
  events.each do |ev|
    @event_broker.all_subscribers_for(ev.type).each do |subscriber|
      dispatcher.call(subscriber, event)
    end
  end
end
```

**Comment by paneq** [comment]
Ok, I forgot about

```
      def verify_subscriber(subscriber)
        raise SubscriberNotExist if subscriber.nil?
        @dispatcher.verify(subscriber)
      end
```

but I generally don't think this `verify` is necessary. I would remove it.

**Comment by paneq** [comment]
Or we could move calling it to `Client` as well?

```ruby
def subscribe(subscriber = nil, event_types = nil, to: nil, &proc)
      if to
        subscriber ||= proc
        @dispatcher.verify(subscriber)
        @event_broker.add_subscriber(subscriber, to)
```

**Comment by pkondzior** [comment]
@paneq you can assign me

**Comment by pkondzior** [comment]
I will remove dispatcher from the broker dependency and call verify and dispatch inside the client

**Comment by pawelpacana** [comment]
> I will remove dispatcher from the broker dependency and call verify and dispatch inside the client

@pkondzior how did it go?

**Comment by pkondzior** [comment]
I have a WIP locally, but I think it needs a bit more work until it can be pushed for review, ETA upcoming week

**Comment by mpraglowski** [comment]
https://github.com/RailsEventStore/rails_event_store/pull/389

**Comment by pawelpacana** [comment]
I believe this is done -- reopen if otherwise.
