### ISSUE TITLE
What if we changed RubyEventStore::GLOBAL_STREAM from "all" default to Object.new ?

### ISSUE THREAD

**Issue by paneq** [RailsEventStore/rails_event_store#270]
To shield other implementations from the error that AR repo made which makes these 2 calls equal.

```
expect(repository.read_all_streams_forward(:head, 3).map(&:event_id)).to eq([u1,u2,u3])
expect(repository.read_events_forward("all", :head, 3).map(&:event_id)).to eq([u1,u2,u3])
```

That would made it possible for other repositories to implement it differently internally.

Generally our intention when the stream is not passed was to store in _global_ stream that you can only read when you don't specify stream when reading and you must use the methods for reading from the _global_ stream, not some accidental _all_ stream.

What do you think?

**Comment by pawelpacana** [comment]
I'm not sure I follow. The goal is to not mistake "all" with some `GLOBAL_STREAM = Object.new` when passing it as a stream name?

**Comment by paneq** [comment]
> The goal is to not mistake "all" string with some GLOBAL_STREAM = Object.new when passing it as a stream name?

yes, exactly! in all possible places!

currently everyone implementing repository has no way to distinguish between stream "all" passed manually and stream not being passed.

AR repository already suffered from it and I don't want ROM repo or InMemoryRepo or any other future implemented repo to suffer from it as well.

The implementation would be more likely to implement global stream in a custom way or using more unlikely name (like `__global__` as I wanted in the past) instead of `"all"`. 

This is especially important since our repo linter does not enforce reading stream "all" (explicitly provided) to return same results as reading global stream (using different repo methods or by not providing in case fluent api).

I can try to do it, but it would be nice to get green light.

**Comment by joelvh** [comment]
This isn't really related to solving this issue, but I had changed some ROM tests to use the `GLOBAL_STREAM` constant... is it better to use the "all" string instead? Should there be a test to make sure `GLOBAL_STREAM` still is "all"? I don't see any tests making sure `GLOBAL_STREAM == "all"`....

**Comment by pawelpacana** [comment]
> I had changed some ROM tests to use the GLOBAL_STREAM constant... is it better to use the "all" string instead?

@joelvh the one difference is for sure how mutant responds to it in this context:

```
irb(main):003:0> RubyEventStore::GLOBAL_STREAM.eql? RubyEventStore::GLOBAL_STREAM
=> true
irb(main):004:0> RubyEventStore::GLOBAL_STREAM.equal? RubyEventStore::GLOBAL_STREAM
=> true
irb(main):005:0> "all".eql? RubyEventStore::GLOBAL_STREAM
=> true
irb(main):006:0> "all".equal? RubyEventStore::GLOBAL_STREAM
=> false
```

**Comment by joelvh** [comment]
@pawelpacana changed the test to use strings.

**Comment by pawelpacana** [comment]
Speaking of behavior change, I'm open for discussion. 

PS. To some degree that reminds me #141 experiment (which intended to remove `all` from `event_store_events_in_streams` table if favor of assuming global is what's in `event_store_events`).

**Comment by pawelpacana** [comment]
@paneq We'll done, consider me convinced. Without it https://travis-ci.org/RailsEventStore/rails_event_store/jobs/363075653 is impossible to solve after introduction of https://github.com/RailsEventStore/rails_event_store/commit/f3c0c2a58e33af978527fa6ccae958917ee6c6d1
