### ISSUE TITLE
Linking the global stream by name ("all") doesn't work as expected?

### ISSUE THREAD

**Issue by joelvh** [RailsEventStore/rails_event_store#275]
Is it intended that `repository.link_to_stream(event_ids, stream_name, expected_version)` does not allow you to link to the global stream?

The logic inside of AR's `add_to_stream` won't add the event to the stream with a position if the stream name matches `GLOBAL_STREAM`. However, it will also not add the "all" event as a global stream entry because `include_global` is not set to `true`.

https://github.com/RailsEventStore/rails_event_store/blob/master/rails_event_store_active_record/lib/rails_event_store_active_record/event_repository.rb#L94

I saw this during the ROM work and then ran into the unexpected result while adding some new tests. I would suggest that we check if the stream name matches `GLOBAL_STREAM` OR `include_global == true`.

**Comment by paneq** [comment]
> Is it intended that repository.link_to_stream(event_ids, stream_name, expected_version) does not allow you to link to the global stream?

yes, because an event can occur only once in any stream (there is even uniqueness constraint if I recall correctly) and every event is added to the global stream when it is first published. So linking an event to the global stream does not make sens as it must already be there.

**Comment by joelvh** [comment]
OK, makes sense @paneq

**Comment by paneq** [comment]
@joelvh was there no test for that in linter?

**Comment by joelvh** [comment]
@paneq I don't believe so.
