### ISSUE TITLE
Use mapper for serializing events to async handlers instead of YAML

### ISSUE THREAD

**Issue by paneq** [RailsEventStore/rails_event_store#279]

**Comment by pkondzior** [comment]
@paneq This means RailsEventStore::AsyncProxyStrategy::AfterCommit should have access to mapper somehow right?

**Comment by paneq** [comment]
@pkondzior That was my initial thinking as well but then...

Why would you need to serialize the domain event (with mapper) multiple times?

Dispatcher/EventBroker could receive domain event AND serialized event (by mapper). The first one is used by sync handlers and the 2nd one would be useful for async handlers.

what do you think about such design?

**Comment by paneq** [comment]
@pkondzior also related #265 for simplification maybe

**Comment by pkondzior** [comment]
@paneq I think serializing/deserializing on each call would make things super slow, the buffer might be good idea here

**Comment by paneq** [comment]
@pkondzior the slowness would depend linearly on number of subsribed async handlers. We already serialize once for repository so I was wondering why not simply reuse it and pass that object down. Sounds better than passing the mapper itself imho.

**Comment by pkondzior** [comment]
@paneq also using NullMapper would remove performance penelities when async is not required and can be inlined

**Comment by paneq** [comment]
@pkondzior yep, I don't worry about it :)

**Comment by pawelpacana** [comment]
@pkondzior still on it?

**Comment by pkondzior** [comment]
@pawelpacana yes, WIP is here https://github.com/RailsEventStore/rails_event_store/commit/0ca82b6cd35e2f7751a5effc9a2dbe27d45510dc I will be continuing work on it upcoming week

**Comment by pawelpacana** [comment]
I believe this is done.
