### ISSUE TITLE
Use https://github.com/arkency/protobuf-nested-struct to serialize Metadata with protobuf

### ISSUE THREAD

**Issue by paneq** [RailsEventStore/rails_event_store#305]
when protobuf configured

**Comment by paneq** [comment]
https://github.com/arkency/protobuf-nested-struct

**Comment by paneq** [comment]
Related #280

**Comment by paneq** [comment]
cc @valscion

**Comment by paneq** [comment]
@valscion yep. I will either use https://github.com/arkency/protobuf-nested-struct/blob/master/lib/protobuf_nested_struct/struct.proto#L6 or https://github.com/arkency/protobuf-nested-struct/blob/master/lib/protobuf_nested_struct/struct.proto#L10 as top-level protobuf struct for serializing metadata without known schema upfront.

**Comment by valscion** [comment]
Sounds good to me! :+1: It might make sense to use the `HashMapStringValue` as the top-level struct so that metadata consumers can at least assume that the top-level is a hash where they can query for the keys easily.

Is there a scenario where that would not be what we want?

**Comment by paneq** [comment]
That's what I am leaning towards as well
