### ISSUE TITLE
Cannot serialize event's data and metadata in binary format due to DB schema

### ISSUE THREAD

**Issue by paneq** [RailsEventStore/rails_event_store#308]
While working on #307 I encountered an unexpected problem. If event's data or metadata is serialized in a binary format which has bytes outside of utf8/latin encoding currently generated by our migration then storing it fails. Verified on Sqlite3 and Mysql.

Test for `event_repository_lint`:

```ruby
  specify 'can store arbitrary binary data' do
    binary = "\xB0"
    expect(binary.valid_encoding?).to eq(false)
    binary.force_encoding("binary")
    expect(binary.valid_encoding?).to eq(true)

    repository.append_to_stream(
      event = SRecord.new(data: binary, metadata: binary),
      RubyEventStore::Stream.new('stream'),
      RubyEventStore::ExpectedVersion.none
    )
  end
```

Exception sqlite:

```
     Encoding::UndefinedConversionError:
       "\xB0" from ASCII-8BIT to UTF-8
     # /Users/rupert/develop/rails_event_store/rails_event_store_active_record/lib/rails_event_store_active_record/event_repository.rb:14:in `block in append_to_stream'
```

Exception mysql:

```
  1) RailsEventStoreActiveRecord::EventRepository behaves like event_repository can store arbitrary binary data
     Failure/Error: build_event_record(event).save!
     
     ActiveRecord::StatementInvalid:
       Mysql2::Error: Incorrect string value: '\xB0' for column 'metadata' at row 1: INSERT INTO `event_store_events` (`event_type`, `id`, `metadata`, `data`, `created_at`) VALUES ('4052b236-36b3-44d6-b1a8-639acb846bb8', 'a9b55df4-34ec-47e9-94fa-c0936e27704b', '?', '?', '2018-04-21 08:34:04')
     Shared Example Group: :event_repository called from ./spec/event_repository_spec.rb:26
     # ./lib/rails_event_store_active_record/event_repository.rb:14:in `block in append_to_stream'
```

Related:

* Compression mapper: #295
* encryption mapper / GDPR
* #189

**Comment by paneq** [comment]
Our migration uses `text` fields but `binary` would be better for storing anything. I am wondering whether to make it mandatory or optional.

After all a developer might always choose to edit a migration or not run it so I don't see an issue if someone wants to store with `text` or `json` ...

@pawelpacana @joelvh @andrzejsliwa @valscion @mlomnicki what do you think?

**Comment by paneq** [comment]
* https://stackoverflow.com/questions/1168036/how-to-fix-incorrect-string-value-errors/1168099#1168099
* https://dev.mysql.com/doc/refman/8.0/en/blob.html
* http://blog.ifyouseewendy.com/blog/2015/08/10/data-types-in-rails/
* http://api.rubyonrails.org/classes/ActiveRecord/Migration.html

**Comment by valscion** [comment]
> what do you think?

I don't think we have any other solution than to only accept a binary encoded column type for `data` and `metadata` if used with protobuf? If so, then the remaining issue is how to make this upgrade smooth and avoid data loss, if possible.

> Our migration uses text fields but binary would be better for storing anything. I am wondering whether to make it mandatory or optional.

It has felt a bit strange in the past that I've been able to read the event data contents with my normal MySQL tools. To me, all but the event ID could be blackboxes that I need a decoder to understand.

Maybe RES could raise a helpful error when first trying to serialize with protobuf to a text column, and provide a link to a migration that needs to be ran? Could the default migrations, e.g. this 

https://github.com/RailsEventStore/rails_event_store/blob/d42ca4b1f9040697bd275b82a1f050d8139e1996/rails_event_store_active_record/lib/rails_event_store_active_record/generators/templates/migration_template.rb#L21-L40

have some sort of constant or something that could be flipped in case you'd like to use protobuf mapping?

For me, I'd be fine with encoding `data` and `metadata` with a `BLOB` type in database. Our upgrade path with RES will also include the deletion of all event data generated thus far, so I'm not the best proponent on ensuring a safe upgrade path 😁

**Comment by paneq** [comment]
I decided that for now, I will add info in the protobuf tutorial in a documentation to do it manually. We can continue discussing whether blob should be used by everyone :)

In that case next migration instead of changing the existing one should be a safer choice.

**Comment by valscion** [comment]
Yeah this sounds like a good tradeoff. Protobuf will anyway be a bit experimental for some time, so it isn't too much to ask to do the migration manually with the protobuf tutorial.

**Comment by pawelpacana** [comment]
https://stackoverflow.com/questions/5403638/convert-text-to-blob-in-mysql/5406009#5406009

**Comment by pawelpacana** [comment]
We're going binary on next release (#490).

**Comment by paneq** [comment]
whoa!
