### ISSUE TITLE
schema and info from the java ecosystem

### ISSUE THREAD

**Issue by MidnightWonderer** [RailsEventStore/rails_event_store#317]
I am currently experimenting with https://github.com/AxonFramework/AxonFramework  
Here a few things I learned:  
  
The event repository is scalable by combining together "cold"* repository and "hot"* repository.
\* just created my own words for the conciseness  
  
"hot repository" is for protecting business rules and concurrency management  
while "cold repository" is for long-term storage
In order to facilitate the feature they created
- a way to combine event queries from 2 repositories https://docs.axonframework.org/part-iii-infrastructure-components/repository-and-event-store#combining-multiple-event-stores-into-one
- an eventually consistent and easy to shard repository https://docs.axonframework.org/part-iii-infrastructure-components/repository-and-event-store#mongodb-event-storage-engine

I just read between the line I believe there should also be
- a mechanism to transfer events from hot repository to cold repository.
  
I have a mixed feeling comparing RES and Axon.  
JPA generated schema from Axon is a mess.  
The schema generated translate roughly to active record dump as:  
```ruby
    create_table :association_value_entry, default: nil do |t|
      t.string :association_key, null: false
      t.string :association_value
      t.string :saga_id, null: false
      t.string :saga_type
      t.index [:saga_type, :association_key, :association_value], name: :spring_index_78ad466c09
      t.index [:saga_id, :saga_type], name: :spring_index_1f68b1e4d3
    end

    create_table :domain_event_entry do |t|
      t.bigint :global_index, null: false, index: { unique: true, name: :spring_index_476e606907 }
      t.string :event_identifier, null: false, index: { unique: true, name: :spring_index_a6789b37cd }
      t.binary :meta_data
      t.binary :payload, null: false
      t.string :payload_revision
      t.string :payload_type, null: false
      t.string :time_stamp, null: false
      t.string :aggregate_identifier, null: false
      t.bigint :sequence_number, null: false
      t.string :type
      t.index [:aggregate_identifier, :sequence_number], unique: true, name: :spring_index_181e1822ad
    end

    create_table :saga_entry do |t|
      t.string :saga_id, null: false, index: { unique: true, name: :spring_index_d42a1ecffb }
      t.string :revision
      t.string :saga_type
      t.binary :serialized_saga
    end

    create_table :snapshot_event_entry do |t|
      t.string :aggregate_identifier, null: false
      t.bigint :sequence_number, null: false
      t.string :type, null: false
      t.string :event_identifier, null: false, index: { unique: true, name: :spring_index_f4642c5204 }
      t.binary :meta_data
      t.binary :payload, null: false
      t.string :payload_revision
      t.string :payload_type, null: false
      t.string :time_stamp, null: false
      t.index [:aggregate_identifier, :sequence_number, :type], unique: true, name: :spring_index_2a6f6cc86a
    end

    create_table :token_entry do |t|
      t.string :processor_name, null: false
      t.integer :segment, null: false
      t.string :owner
      t.string :timestamp, null: false
      t.binary :token
      t.string :token_type
      t.index [:processor_name, :segment], unique: true, name: :spring_index_53514ff346
    end
```
I have no idea what all the fields do. I just post it here in case it catch someone's eye.  
  
While I have a feeling that Axon did better on programming interface and implementation pluggability.  
Nevertheless, I like RES more overall for its tidiness and simplicity.  
  
I also learned by exploring the framework that Spring and JPA from Java ecosystem are even way more magical than Rails. (The framework execute code differently by themselves based on what appeared on the classpath)  
I am pretty sure I can't participate in the upcoming RES hackathon.  
So I wrote my finding here in case somebody wants an idea.

**Comment by paneq** [comment]
Cool, thanks for your research.

> implementation pluggability

can you mention what is not pluggable in RES? Because as far as I know every dependency is passed in constructor and can be exchange to something different and developers using RES actually do it.

**Comment by MidnightWonderer** [comment]
Hi @paneq  
It is not entirely about what RES currently doing but the community.  
Ruby community did a better job for database design and maintenance because everyone learn about database schema, migrations, and everything since the very beginning when they started building something.  
  
In the other hand Java community abstract out all the details of the database. Most of the real world project have a hard time maintaining the database. I hardly find an average Spring developer talking about schema migration and versioning. However, the Java community have really deep root in dependency inversion, polymorphism, and adapter patterns (to name a few) their entire stack built around those ideas.  
  
Take JPA for example. They started with the specifications and interfaces then everyone is free to implement the specification. (e.g. Hibernate, EclipseLink, OpenJPA)  
It just like having an interface for ActiveRecord and there are many ActiveRecord implementations to choose from. One can even subclassing the exist implementation to extend or customize the functionality.  
  
While in RES I see that you guys really attempt to establish dependency injection alike pattern.  
But since there are only 1 implementations of ActiveRecord it does not really make sense to extract dependency any further. So with the current setup I can provide implementations at the repository level for RES. Just like what you said I can customize some functionality by supply the dependency as construction parameters.  
  
But to see concrete real world problem you can take my attempt to encode uuid in binary format for an instance https://github.com/RailsEventStore/rails_event_store/pull/294 (I am targeting MySQL).  
I do agree that this is the reasonable unit of decomposition for Ruby project but for Axon with JVM community they really did it all the way down. They are also around longer that RES (I supposed) so they have more high level utilities that agnostic to low level implementation. (Which I believe you guys planned to add them at the ruby_event_store gem.)  
  
To consolidate it to the relevant parts:  
It is not you guys fault or bad designs. It is how things evolve and the people around the ecosystem.  
If I were to use Axon I guess I need to implement data persistence layer myself.  
Whatever I choose I have some homework to do on the storage scalability for my use case anyway.  
I am still favor RES as my first option for now and I see the emerging community here as well.  
I am just not sure about the stability of the API and the test suite you guys provided in the ruby_event_store.  
  
Great job overall

**Comment by paneq** [comment]
> But since there are only 1 implementations of ActiveRecord it does not really make sense to extract dependency any further.

* https://github.com/RailsEventStore/rails_event_store/tree/master/rails_event_store_active_record
* https://github.com/RailsEventStore/rails_event_store/tree/master/ruby_event_store-rom
* https://github.com/RailsEventStore/rails_event_store/tree/master/rails_event_store_active_record-legacy
* https://github.com/gottfrois/rails_event_store_mongoid

Ah, I think you meant something different. That AR repository does not take more objects as dependencies. We are open to that. Just keep backwards-compatibility high and provide small pull requests and we can see what's possible.

> I am just not sure about the stability of the API.

Check out this changelog https://github.com/RailsEventStore/rails_event_store/releases and tell me how hard it is to migrate to new version when everything from a new release is described super accurately.

> and the test suite you guys provided in the ruby_event_store.

seems good enough for @joelvh to implement ruby_event_store-rom . 

If you find something missing you can send PR to add a missing test. We use mutation testing on all subcomponents and that pretty much makes sure everything is tested. I don't know of any other project with such high testing requirements to contribute frankly.

> But to see concrete real world problem you can take my attempt to encode uuid in binary format for an instance #294 

like I mentioned, on master branch you can probably just exchange mapper for that...

> They are also around longer that RES (I supposed) so they have more high level utilities that agnostic to low level implementation.

might be true, i am not following.

In the end I am gonna try to convince you to use RES. It's your choice. I am just here to _debunk myths_ 😜

**Comment by MidnightWonderer** [comment]
Hi, maybe I misunderstood something I did not see the mapper functionality usable for id serialization without modifying repository code.  
I see that I can transform event_id there but as you can see here just for an instance  
From: rails_event_store_active_record/lib/rails_event_store_active_record/event_repository_reader.rb
```ruby
def read_event(event_id)
  event = Event.find(event_id)
  RubyEventStore::SerializedRecord.new(
    event_id: event.id,
    metadata: event.metadata,
    data: event.data,
    event_type: event.event_type
  )
rescue ActiveRecord::RecordNotFound
  raise RubyEventStore::EventNotFound.new(event_id)
end
```
The mapper never applied to the `event_id` parameter for `find` method.

**Comment by paneq** [comment]
@MidnightWonderer indeed, you are correct.

It should work when publishing events and retrieving events

```
    def append_to_stream(events, stream_name: GLOBAL_STREAM, expected_version: :any)
      events = normalize_to_array(events)
      events.each{|event| enrich_event_metadata(event) }
      repository.append_to_stream(serialized_events(events)
      # ...
```

```ruby
    def read_stream_events_forward(stream_name)
      deserialized_events(read.stream(stream_name).each)
    end
```

but it won't work in any API which takes `event_id` as one of the arguments such as for example `read_event(event_id)` and `read_events_forward(stream_name, start: count:)` where `start:` is an event id because we are not mapping them.

Perhaps the mappers should have a method to map only `event_id` which should be used in those APIs. If that's of interest to you, you can create a separate issue for that and we can discuss.

I see 2 simple workaround for now. You build have an adapter which takes RES::Client as dependency and converts ie:

```ruby
class MyStore
  def initialize(res)
    @res = res
  end

  def read_event(event_id)
    binary_id = convert(event_id)
    read_event(binary_id)
  end

  # ....
end
```

might work. Haven't checked.

Or you pass binary ids as event_id.

```ruby
event = OrderPlaced.new(
  event_id: binary_id, 
  data: {
    order_id: 1,
    order_data: "sample",
    festival_id: "b2d506fd-409d-4ec7-b02f-c6d2295c7edd"
})
event_store.publish_event(event, stream_name: stream_name)
```

**Comment by MidnightWonderer** [comment]
Thanks  
This thread evolves to be some long discussion thread.  
  
Regarding id serialization.
In the end, I settled with a wrapper for RailsEventStoreActiveRecord.  
https://github.com/the-cave/event-id-mapper  
  
Taking [recompose](https://github.com/acdlite/recompose) approach of doing things.  
Any comments appreciated.
