### ISSUE TITLE
`event_id` in `event_store_events_in_streams` in MySQL longer than needed to hold UUID

### ISSUE THREAD

**Issue by pawelpacana** [RailsEventStore/rails_event_store#320]
https://github.com/RailsEventStore/rails_event_store/blob/master/rails_event_store_active_record/lib/rails_event_store_active_record/generators/templates/migration_template.rb#L13

It can easily be `varchar(36)` like https://github.com/RailsEventStore/rails_event_store/blob/master/rails_event_store_active_record/lib/rails_event_store_active_record/generators/templates/migration_template.rb#L30

**Comment by pkondzior** [comment]
Will do it

**Comment by pkondzior** [comment]
https://github.com/RailsEventStore/rails_event_store/compare/master...pkondzior:shorten-event-id-size-in-migration?expand=1
