### ISSUE TITLE
ROM failing on master

### ISSUE THREAD

**Issue by pawelpacana** [RailsEventStore/rails_event_store#332]
https://travis-ci.org/RailsEventStore/rails_event_store/jobs/374473430

Most likely something changed upstream with dependency update.

**Comment by pawelpacana** [comment]
cc @joelvh

**Comment by joelvh** [comment]
thanks for the heads up @pawelpacana - fix in #339 - feel free to merge once tests pass.

**Comment by pawelpacana** [comment]
Thanks!
