### ISSUE TITLE
Storing Commands in RES

### ISSUE THREAD

**Issue by joelvh** [RailsEventStore/rails_event_store#340]
Would like to see thoughts on ways to think about storing Commands in RES in relation to Events. One of the things I liked conceptually a lot about [Eventide](http://www.eventide-project.org) a lot is that there's a Command history along with the Events.

It seems you could have two separate RES setups, one for Commands and one for Events. Possibly both could live in the same tables and maybe not use streams -- or have Events also be added to streams related to a specific Command.

* Are there any strong opinions about treating RES more as a message store?
* Have you had differing scenarios for using Commands in your projects?

Thanks!

**Comment by joelvh** [comment]
I'm also interested in this from the viewpoint of using the RES brokering and dispatching for both Commands and Events.

**Comment by andrzejkrzywda** [comment]
@joelvh It's definitely in our plans.

In my current project, we're now working on introducing command sourcing and I hope that we can extract some thoughts/ideas into RailsEventStore.

Implementation-wise - would love to hear more ideas/opinions how we can approach this in short-term vs long-term.

Conceptually I like the idea of having the same instance of RES being aware of which command is running and which event is published - this can allow some corelation_id to happen under the hood.

**Comment by joelvh** [comment]
Hi @andrzejkrzywda - I know I mentioned this on Slack end of last year and wanted to take your recommendation from back then to start an Issue on the topic.

I think a funny point of confusion can become the various definitions of a Command because there are a couple patterns. My goal will be to get an end-to-end demo together of how the various patterns work together using RES.

I will be experimenting and share my observations here.

**Comment by paneq** [comment]
If you use `command_bus` #147 http://railseventstore.org/docs/command_bus/ and decorate dispatching commands with saving them first then you are basically done :)

> Possibly both could live in the same tables and maybe not use streams

I don't know. I don't see much value from reusing tables. But command has type, id, data and maybe some metadata so it seems there could be some potential. But identical DB schema is not good enough reason for me to justify coupling with the same table.

> Have you had differing scenarios for using Commands in your projects?

_differing_ compared to what ?

> or have Events also be added to streams related to a specific Command.

I think of it as a subset of "Experiment with metadata-driven streams #221" feature.

If command has id and and events have correlation id in metadata which is taken from initial command or from an event that triggered event handler then we could have them all linked in a stream named by that `correlation_id`. I added "Correlation ID as 1st class citizen #346" as an idea.

**Comment by joelvh** [comment]
@paneq using the Command as the correlation ID makes sense. Eventide copies metadata from the command to the event using a helper method (`follow`), which effectively does that same thing.

"Differing" I may have been referring to multiple patterns with the same name, but also curious if you use commands that are not passed as messages but rather are more like services that emit events via aggregates. Do you use commands in different ways along those lines, or do you have a specific way you tend to setup your projects? (Mostly wondering from your experience and your preferences when it comes to this, so I have some perspective where you're coming from typically.)

Thanks!

**Comment by paneq** [comment]
Today's thoughts

* `append_to_stream` is sufficient for storing commands. `publish_event` is not necessary as commands don't have multiple handlers but a single handler.
* Perhaps we should rename/alias/inherit `RubyEventStore::Event` to `RubyEventStore::Message`

**Comment by paneq** [comment]
@joelvh basically this diagram: https://github.com/RailsEventStore/rails_event_store/issues/246

**Comment by paneq** [comment]
`gsub("EventStore", "MessageStore")` sounds interesting.

**Comment by andrzejkrzywda** [comment]
We're storing commands in our project, using RES - maybe @fmwr can elaborate more on the details?

**Comment by mpraglowski** [comment]
I will join the discussion here with some questions:

Why you want to store commands? 
Maybe a simple domain event `CommandExecuted` with correlation id, command type & command payload would be enough?

**Comment by paneq** [comment]
> Maybe a simple domain event CommandExecuted with correlation id, command type & command payload would be enough?

ugh, why would you do such workarounds instead of persisting the command directly?

> with correlation id

of what value?

> Why you want to store commands?

* to have a log, just like with events.
* To implement command sourcing

**Comment by mpraglowski** [comment]
> ugh, why would you do such workarounds instead of persisting the command directly?

That's why I'm asking why you need to store command ;) If just as a part of audit log then this should be enough. But I miss some use cases here.

> > with correlation id
> of what value?

Whatever will help you identify a command - but that actually might be a random uuid as you will have a command in event's payload.

> to have a log, just like with events.

Event with command payload seems to be valid solution here.

> To implement command sourcing

Still I would imagine implementation where I process `CommandExecuted` events in some handler that will invoke commands stored in event payload on command bus.


> gsub("EventStore", "MessageStore") sounds interesting.

BTW I would rather go with `EventStore` & `CommandStore` and do not mix command & event sourcing.

**Comment by paneq** [comment]
> > > with correlation id

> > of what value?

> Whatever will help you identify a command - but that actually might be a random uuid as you will have a command in event's payload.

So a command comes with ID X which is propagated through logging etc. But you store it as an event with ID Y. Event handler reacts and triggers a new command. That new command is correlated to the event which triggered it. As a result correlation ID is set to Y and not X? Rinse and repeat for every command/event dependency. That does not sound optimal for me.

On the other hand if we persisted an event with the same ID as the command then basically we are persisting the command itself and I see no point in wrapping it in `CommandExecuted`.

> BTW I would rather go with EventStore & CommandStore and do not mix command & event sourcing.

No-one is mixing anything...

How would the API and usage of CommandStore differ from EventStore? As far as I imagine, commands are serialized message persisted in streams which is a subset of EventStore functionality (`EventStore-EventBus = MessageStore`).

**Comment by paneq** [comment]
> hat the use cases we discuss here could be implemented already using existing features.

I am not sure anyone doubted the possibility.

> Until someone will mix events & commands in single stream :)

The possibility of doing that especially for correlation and causation streams is exactly what I am trying to achieve. I trust the devs they know what they are doing and that they write tests. If they want to store both messages in a single stream, I am fine. If they want to store them separately, they are more than capable of doing that without shooting themselves in the foot.

**Comment by mpraglowski** [comment]
> The possibility of doing that especially for correlation and causation streams is exactly what I am trying to achieve.

Ok, that was not clear for me. So I have other questions:

- [ ] how this shall impact projections
- [ ] should be have 2 ways of handling sourcing (command vs event) in aggregate root ? (I would expect not to mix both of them there)

I'm still not sure if I like this idea but just 'show me the code' :)

**Comment by paneq** [comment]
>  how this shall impact projections

if your projection stream only has events then not at all.

>  should we have 2 ways of handling sourcing (command vs event) in aggregate root ? (I would expect not to mix both of them there)

i would leave it to the developers. nothing changes if you don't save commands in the same stream. If you do, handle it... by doing nothing for events or by doing nothing for commands.

**Comment by paneq** [comment]
I don't assume commands must to be stored in the same stream as as events for an object/entity/aggregate.

**Comment by paneq** [comment]
> I'm not convinced that a RubyEventStore::Client is the best place to store commands, why here? Why not some CommandStore? If we will have different data structures, it will have different use cases, looks for me as something that does not belongs here.

I don't see it having different data structures. It's just data that gets serialized for me. If they are not implemented using the same library as your events, that's not an issue. Pass a mapper which can distinguish and delegate based on whether that's a command or event.

As for usecases:

* Command bus decorator persists the command. No difference compared to `append_to_stream`/`append`/`persist` with events. Exactly same steps required. You need to serialize the message and store it in some DB.
* Command sourcing. If you persist the commands in the right stream, it works just like event sourcing. You just build state based on commands instead of events.

> Maybe we should have EventStore & CommandStore that will have common part in MessageStore.

I am saying that's the same store. My angle: first make the api more general, later we can rename or alias the namespaces (or not).

**Comment by joelvh** [comment]
@paneq have you guys discussed this much lately? I want to build in a safeguard that a command hasn't been previously processed, to achieve what Eventide does in their example command handler.

`account.up_to_date?(deposit)`

https://gist.github.com/sbellware/2e3e3b2e2737c92a81777f55ff2c76d6#file-command_handler-rb

Have you dealt with ensuring a command hasn't already been processed? I think using the command bus, this should likely not be an issue if the command bus is in-process and synchronous. However, Eventide is likely using the event store as a queue and processing the commands in a different process.

Thoughts on the necessity of something like this? If I were to pursue this, I would probably link the commands to a stream such as `Account$123$Commands` or similar, and look up if the command was already there.

**Comment by joelvh** [comment]
What I've done is simply publish each command to the "Command" as the first step of the command handler as a means to ensure the command hasn't been processed before (expecting a duplicate event ID exception otherwise).

The only thing that I haven't addressed yet is to rollback the RES transaction if exceptions or business validations in the command handler fail in following steps.

The purpose is primarily to log the command that was processed, but also piggybacking no the ability to make sure commands/events don't get processed multiple times.

**Comment by andrzejkrzywda** [comment]
We're in the process of enabling command storing, but also command sourcing in one of our very specific projects. So far, we started simply, similarly to your setup @joelvh - we store commands as events called "CommandIssued". It's not a long-term solution, but for now we focus more on command sourcing. Within next weeks/months, we're going to share more observations.

**Comment by joelvh** [comment]
Great to hear @andrzejkrzywda! I mentioned in #372 that I've been thinking that some approach to extensibility to RES to add features might be worth exploring (if it hasn't already), to add features that RES might not know about. This could be an advantage over configurability.

Look forward to seeing what your experiences are with command sourcing.

**Comment by andrzejkrzywda** [comment]
`to add features that RES might not know about` - one idea which I was contemplating was to expose public RES events (how meta is that?), like for example `EventPublished`, `EventLinkedToStream`, `AggregateSourced` to allow building features on top of RES, even without RES being aware of that. Your suggestion of implementing Rack-middleware-like pattern is also very interesting!

**Comment by joelvh** [comment]
That's an interesting idea, to publish events to notify extensions of what's happening. I would equate it more to how Wisper broadcasts events than using the event store for it. Maybe you mean to publish those "meta" events in a way that is outside of the published events in the event store?

**Comment by joelvh** [comment]
Hi @mpraglowski any reason not to pursue this?
