### ISSUE TITLE
Rails 5 belongs_to implicit required issue

### ISSUE THREAD

**Issue by macgill4444** [RailsEventStore/rails_event_store#351]
We have an app that runs on Rails 5. As you probably know, in Rails 5 `belongs_to` relationships are implicitly required. After adding `rails_event_store` gem all our validation tests around required `belongs_to` arguments fail. Our test suite runs on Rspec. We've fixed this for now by adding the `required: true` argument to our `belongs_to` relationships. 

Any idea where the issue arose from? I've checked the value of `Rails.application.config.active_record.belongs_to_required_by_default` and it's still true.

**Comment by paneq** [comment]
Thank you @macgill4444 for reporting the issue. Sounds super strange. No idea where that could come from.

Could you provide exact rails version and ruby version?

Do you think you could provide a minimal reproducible scenario? Like a fresh rails app + Rails Event Store + 2 model (one with belongs_to)?

**Comment by pawelpacana** [comment]
I'd love to help but that is difficult without a code to reproduce. Closing now, please reopen with steps to reproduce.
