### ISSUE TITLE
YARD documentation

### ISSUE THREAD

**Issue by pawelpacana** [RailsEventStore/rails_event_store#352]
Consider moving some docs (public API documentation) to https://yardoc.org, focusing on getting started and tutorials on railseventstore.org.

**Comment by paneq** [comment]
Add links to:

* https://www.rubydoc.info/gems/rails_event_store
* https://www.rubydoc.info/gems/ruby_event_store/

To our main documentation. Or embed it.

**Comment by pawelpacana** [comment]
This probably an ongoing process (of adding more API docs) from now on. Main objective to start documenting has been fulfilled.
