### ISSUE TITLE
Is there any way to get RubyEventStore::Stream's ID I published?

### ISSUE THREAD

**Issue by FX-HAO** [RailsEventStore/rails_event_store#353]
My use case is that I want to restore the states to a specific version. It's like what the AggregateRoot does. But AggregateRoot is currently not support restore to a specific version. It just aggregates all the  events. I think maybe I can add an argument named `stream_id` or something to `load` method to achieve this feature. But at first, I must have the RubyEventStore::Stream's ID I published and saving it for restoring. Any idea?

**Comment by FX-HAO** [comment]
Yes, there is no stream's id indeed. But I need something like it to identify my event version.
I found there are `id` and `event_id` in table event_store_events_in_streams. If I can get either one of them, I can achieve something like `read_stream_events_backward(stream_name, end: event_id)` to read events until `event_id` rather than all events. Then I can build an entity’s state at a specific version(`event_id`) by replaying the events.

**Comment by paneq** [comment]
The event that you publish has `event_id` getter: https://github.com/RailsEventStore/rails_event_store/blob/f2eb0993fc66ef3740fe118d0fe8012f794061db/ruby_event_store/lib/ruby_event_store/event.rb#L10 and you provide it to some of the methods http://railseventstore.org/docs/read/ .

There is no really good API right now to achieve reading until an event. I think you gotta do something like: `read_events_backward(stream_name, start: last_event_id, count: 1_000_000_000).reverse`.

Maybe you could use http://railseventstore.org/docs/projection/ and stop processing when this certain event occurs...

But we are working on better fluent API for reading right now #258 #310 .

**Comment by FX-HAO** [comment]
The problem is that `publish_event` does not return the published event, it just returns `:ok`. So I cannot get the `event_id`.

**Comment by paneq** [comment]
You can access the `event_id` even before publishing.

https://github.com/RailsEventStore/rails_event_store/blob/f2eb0993fc66ef3740fe118d0fe8012f794061db/ruby_event_store/lib/ruby_event_store/event.rb#L5

**Comment by FX-HAO** [comment]
Sorry, I didn't noticed that before. Thanks for your help.

**Comment by paneq** [comment]
No need to apologize. Have a lovely day.

**Comment by paneq** [comment]
@FX-HAO If you have a moment, please fill out our survey about RES usage  https://goo.gl/forms/PmRMhGRCyG6VQION2

**Comment by paneq** [comment]
@FX-HAO If you want to support our work, just buy one of our books sometime https://blog.arkency.com/products/
