### ISSUE TITLE
Command ID / Message ID

### ISSUE THREAD

**Issue by paneq** [RailsEventStore/rails_event_store#364]
Yo, in relation to #346 #362 

I wanted to achieve common API for getting command ID's and event ID's.

* Right now for event's the API is `event_id`.
* `command_bus` does not impose any structure on commands right now
* `event_id` does not sound like a good API for command ID's that could be used by `#correlate_with()` which currently looks like:

    ```ruby
    def correlate_with(other_message)
        self.correlation_id = other_message.correlation_id || other_message.event_id
        self.causation_id   = other_message.event_id
    end
    ```

I think both (events and commands) are messages so it feels natural for me to assume `message_id` as the common interface. That would mean adding `message_id` reader to `RubyEventStore::Event` and changing the code `correlate_with` code to:

 ```ruby
def correlate_with(other_message)
    self.correlation_id = other_message.correlation_id || other_message.message_id
    self.causation_id   = other_message.message_id
end
```

Does that make sense in your opinion?

For `commands` we are still not going to enforce/assume any schema or class etc. But if they follow the `message_id` interface, they could be used as an argument to `correlate_with`:

```ruby
event.correlate_with(command)
```

**Comment by joelvh** [comment]
@paneq I think the `message_id` makes sense. Do you see some more "official" `Command` existing in RES at some point?

**Comment by joelvh** [comment]
I would also potentially push for `message_id` being the actual value and `event_id` being an alias... but I know that is a much bigger change.

**Comment by paneq** [comment]
> Do you see some more 1st class Command existing in RES at some point?

At some point probably, but I don't have a vision for it yet.

> I would also potentially push for message_id being the actual value and event_id being an alias... but I know that is a much bigger change.

Well, we could maintain both getters and setters...
