### ISSUE TITLE
GDPR Strategies for Event Sourcing

### ISSUE THREAD

**Issue by joelvh** [RailsEventStore/rails_event_store#372]
Hey all,

I know GDPR has been a big topic. Wanted to see what the strategies have been to address this in RES?

My thought is to explore functionality or "plugins" that could help address the patterns that will need to be adopted by virtually everyone going forward. (I saw a brief reference to GDPR in #308.)

I'll share my approaches for my next project but wanted to see what contributors' experience has been so far.

P.S. Some further spying reveals @paneq mentioned having [tried some approaches recently](https://twitter.com/pankowecki/status/1003523347634966528).

**Comment by joelvh** [comment]
Someone at Arkency recently pointed out [this tweet](https://twitter.com/abdullin/status/1003325884957372417):

*Suggested GDPR solution:*
1) Encrypt events with per account key
2) On deletion request - delete the account encryption key and issue tombstone event to tell subscribers to drop derived data.
3) On the next scheduled compaction - discard events for all tombstoned accounts.

"Tombstones" are another pattern that would be nice to see implementation examples with RES.

**Comment by joelvh** [comment]
[This tweet by Roger Johansson](https://twitter.com/RogerAlsing/status/998106765693784064) that Rinat Abdullin was responding to has a long discussion about various approaches.

* History rewrite or compaction strategies
* Encryption properties or "crypto shredding"
    * Encrypt data with the user's key and then throw away the key?
* Shutdown to chase the latest events
* Tombstones

**Comment by pawelpacana** [comment]
In one of the projects we've implemented solution where only some parts of the data are encrypted. Metadata keeps track of which parts are readable only when you have a key. Keys are stored separately and are forgotten on deletion request.

I'd like to port that solution at some point into RES.

**Comment by joelvh** [comment]
@pawelpacana would be great to see an example, even conceptually for now to plant a seed for how it might fit into ES.

Semi-related to this, I have been thinking about extensibility of RES, to add features such as this. Right now, things are very configurable, but wonder if there's a way to do things in an extensible manner, such as how things like middleware work. Rack middleware, Sequel's extensions and Rails' engines are examples along those lines....

**Comment by pawelpacana** [comment]
> Semi-related to this, I have been thinking about extensibility of RES, to add features such as this. Right now, things are very configurable, but wonder if there's a way to do things in an extensible manner, such as how things like middleware work. Rack middleware, Sequel's extensions and Rails' engines are examples along those lines....

Composable mappers/dispatchers would be a lovely addition!

**Comment by paneq** [comment]
> Composable mappers would be a lovely addition!

#400

**Comment by pawelpacana** [comment]
In-progress implementation: https://github.com/RailsEventStore/rails_event_store/commit/ff4917c58e53ee9e55f3324863d88a5585cb6ae6

**Comment by pawelpacana** [comment]
@joelvh I've described some strategies in https://railseventstore.org/docs/gdpr/. The field-level encryption in present in `EncryptionMapper` released recently.

**Comment by pawelpacana** [comment]
> Notify consumers about deletions via new event

I think this could be more of a capturing fact that someone `RequestedToBeForgotten`.

**Comment by joelvh** [comment]
@pawelpacana  you rock. I was going through my notifications in order today and already made some minor grammatical edits to the GDPR docs, which look awesome!

I also saw the release of the encryption mapper fly by, which is super exciting as well.

I've been heads-down for the last couple months on our project using RES, and have lots to catch up on that  you guys have been hard at work on. I need to look at all the release notes to see what features need to be sync'd  up with  ROM.

Two areas that are top-of-mind in our project right now are encryption for sensitive data as well as PII. We also want to probably use this technique for a feature of a customer who wants the ability to "erase" certain data either after a period of time or when  a "project" is completed. (This is in the context of our domain  concepts, which  mirrors very much  the solutions to dealing with GDPR, but with different requirements for what to erase.)  I will be diving into this quite a bit soon (I hope).

The other area is wanting to pick your brains  more on some architectural solutions based on your experience - but I'll broach that separately.

Great work - i will be in touch as I get up-to-speed on all the latest.

**Comment by joelvh** [comment]
@pawelpacana the docs suggest HashiCorp's Vault for key management. Is that what you guys use?

I'm looking at using AWS' KMS, and wonder if you guys have experience managing keys in a multi-tenant SaaS project, where we might want to maintain separate keys per user/customer.

What are your thoughts about separate keys per user/customer and how to implement that with something like AWS KMS?

**Comment by pawelpacana** [comment]
@joelvh I didn't use Vault nor KMS personally. I've suggested it as one of the possibilities to consider when evaluating options.
