### ISSUE TITLE
Create run migrate after delete

### ISSUE THREAD

**Issue by tranhoangvuit** [RailsEventStore/rails_event_store#380]
Hi all,
I got this error when I drop and run migrate my database again.
`	 2: from /Users/austintran/.rvm/gems/ruby-2.5.1@epos-web/gems/activesupport-5.2.0/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
	 1: from /Users/austintran/.rvm/gems/ruby-2.5.1@epos-web/gems/activerecord-5.2.0/lib/active_record/connection_adapters/postgresql/database_statements.rb:63:in `block (2 levels) in query'
/Users/austintran/.rvm/gems/ruby-2.5.1@epos-web/gems/activerecord-5.2.0/lib/active_record/connection_adapters/postgresql/database_statements.rb:63:in `async_exec': PG::UndefinedTable: ERROR:  relation "event_store_events" does not exist (ActiveRecord::StatementInvalid)
LINE 8:                WHERE a.attrelid = '"event_store_events"'::re...
                                          ^
:               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod,
                     c.collname, col_description(a.attrelid, a.attnum) AS comment
                FROM pg_attribute a
                LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum
                LEFT JOIN pg_type t ON a.atttypid = t.oid
                LEFT JOIN pg_collation c ON a.attcollation = c.oid AND a.attcollation <> t.typcollation
               WHERE a.attrelid = '"event_store_events"'::regclass
                 AND a.attnum > 0 AND NOT a.attisdropped
               ORDER BY a.attnum`
Thank you so much.

**Comment by paneq** [comment]
@tranhoangvuit could you include full log of commands you executed? Otherwise, I can't help you much.

> when I drop and run migrate my database again

I am not sure I understand.

Did you run `bundle exec rake db:schema:load` ?
