### ISSUE TITLE
Document all the LinkBy* available classes on a separate documentation page

### ISSUE THREAD

**Issue by paneq** [RailsEventStore/rails_event_store#390]
Related Issues: #72 #221 #346

**Comment by lukaszreszke** [comment]
I documented the LinkBy* classes together with linking subject https://railseventstore.org/docs/v2/link/
Thanks to the side-nav it should be nicely accessible. If you disagree with that decision please reopen the issue and suggest other solution.

**Comment by paneq** [comment]
Thank you!
