### ISSUE TITLE
RubyEventStore::Event constructor should not implicitly convert data attribute to Hash

### ISSUE THREAD

**Issue by paneq** [RailsEventStore/rails_event_store#395]
I see no value in that behavior:

```ruby
  class Event
    def initialize(event_id: SecureRandom.uuid, metadata: nil, data: nil)
      @event_id = event_id.to_s
      @metadata = Metadata.new(metadata.to_h)
      @data     = data.to_h
    end
```

Let's say you want to use `ClosedStruct` or `Struct` or `OpenStruct` or event a `String` as `data`. You also configured a mapper/serializer in a way which knows how to handle such classes an how to serializer/deserialize them properly. Why should RES enforce it to be a `Hash`? Why can it not be anything else?

The impact should be minimal in my opinion:
* the documentation shows Hashes
* the user can wrap mapper with one that does `to_h` conversion
* the user can add `to_h` calls in all places which instantiate events
* the user can use its own class inheritance to add `to_h` conversion and call `super` with modified arguments.

**Comment by fidel** [comment]
Discuss: #480
