### ISSUE TITLE
Make RubyEventStore::Specification#result method private

### ISSUE THREAD

**Issue by paneq** [RailsEventStore/rails_event_store#398]
As far as I see it does not need to be exposed.

**Comment by Atul9** [comment]
Hi @paneq I checked `ruby_event_store/lib/ruby_event_store/specification.rb` file. I didn't find any method named `result`

**Comment by paneq** [comment]
Hi @Atul9 , I was talking about this:

https://github.com/RailsEventStore/rails_event_store/blob/a609202e664aad027efa25b9c71b2880ddf0defd/ruby_event_store/lib/ruby_event_store/specification.rb#L46
