### ISSUE TITLE
to_h in constructor considered harmufl ;)

### ISSUE THREAD

**Issue by paneq** [RailsEventStore/rails_event_store#409]
Here is an idea:

```ruby
class RubyEventStore::Event
    def initialize(event_id: SecureRandom.uuid, metadata: nil, data: nil)
      @event_id = event_id.to_s
      @metadata = Metadata.new(metadata.to_h)
      @data     = data.to_h
    end
```

Let's not call `to_h`.

If someone wants to use `Struct` or `OpenStruct` or custom class as data, let's allow it!

They need to configure mapper which can handle that but it's not our problem.

On the contrary. This `to_h` adds more problems than it solves imho. It's one of the reasons that when using protobuf we needed to do write custom initializer which does not call `to_h`.

```ruby
module RubyEventStore
  class Proto < RubyEventStore::Event
    def initialize(event_id: SecureRandom.uuid, metadata: nil, data:)
      @event_id = event_id
      @metadata = Metadata.new(metadata.to_h)
      @data     = data
    end
```

**Comment by pawelpacana** [comment]
Duplicate #395

**Comment by paneq** [comment]
I couldn't find it. I thought I forgot to submit it :) Thx!

**Comment by fidel** [comment]
> It's one of the reasons that when using protobuf we needed to do write custom initializer which does not call to_h

Data is mandatory in `Protobuf`, so it's still needs custom initializer. At least we can go with `super` now.

**Comment by paneq** [comment]
> Data is mandatory in Protobuf, so it's still needs custom initializer. At least we can go with super now.

I think we could let it fail on mapping/serialization step. The mapper would reject events with no `data` and we would be a step closer to droping `Proto` class. What do you think?

**Comment by fidel** [comment]
> I think we could let it fail on mapping/serialization step. The mapper would reject events with no data and we would be a step closer to droping Proto class. What do you think?

Makes sense. Do you expect custom exception in mapper or just `NoMethodError` while calling `data.class.encode`?

**Comment by mpraglowski** [comment]
Custom error always tell you more - `NoMethodError` is to generic IMHO
