### ISSUE TITLE
InMemoryRepository - verify no mixing between expected_versions: :any and Integer

### ISSUE THREAD

**Issue by paneq** [RailsEventStore/rails_event_store#420]
Recently I had 2 developers contacting me who published with inconsistent `expected_version` to the same stream. They used AggregateRoot and they manually published outside of it to the same stream. This is not supported.

However it would be costly for our 2-table schema to verify this assumption so we don't check and silently accept it even though reading the data would lead to an incorrect order (and it does). 

But we could warn them if our `InMemoryRepository` which is likely used in tests would raise an exception in such case. What do you think?

**Comment by pawelpacana** [comment]
Makes sense if that repository is primarily used in tests.

**Comment by swistak35** [comment]
Done in #1091
