### ISSUE TITLE
Brew issues on CircleCI

### ISSUE THREAD

**Issue by swistak35** [RailsEventStore/rails_event_store#426]
An issue started appearing with brew on CircleCI, related to wrong sha of google-chrome: https://circleci.com/gh/RailsEventStore/rails_event_store/3997

**Comment by paneq** [comment]
> ==> Note: running "brew update" may fix sha256 checksum errors

**Comment by paneq** [comment]
on the other hand:

```
==> Auto-updated Homebrew!
Updated 5 taps (homebrew/cask, homebrew/cask-versions, homebrew/cask, homebrew/cask-versions, homebrew/core).
```

**Comment by pawelpacana** [comment]
🤔 https://github.com/Homebrew/homebrew-cask/pull/50309

**Comment by paneq** [comment]
locally I have `MD5 (googlechrome.dmg) = 5533641bc4cc7af7784565ac2386a807`

**Comment by pawelpacana** [comment]
that's SHA256

**Comment by paneq** [comment]
Locally I have `c6d7930c958e9f76234dffd5d06ecb845927023d`

**Comment by swistak35** [comment]
@pawelpacana Thought about it, but I don't have that button anymore (circleci v2?).

**Comment by paneq** [comment]
More likely because we don't cache and maybe because this is mac.

**Comment by pawelpacana** [comment]
```
 ~ brew cask cleanup                                                                                                                                                            16s 767ms
==> Removing cached downloads
Nothing to do
```

**Comment by pawelpacana** [comment]
Fixed itself.
