### ISSUE TITLE
Aggregate Root & Child Objects

### ISSUE THREAD

**Issue by mattgrande** [RailsEventStore/rails_event_store#427]
(Please let me know if there's a better place to ask this; The community page indicated that questions were allowed here)

I have an event sourced object with Aggregate Root; The object has child objects. Simple example:

```
class Author
  include AggregateRoot

  def add_book(book_info)
    apply BookAdded.new(data: {...})
  end

  on BookAdded do |e|
    book = Book.new(e.data)
    self.books << book
  end
end

class Book
  include AggregateRoot
end

dan_brown = Author.new
dan_brown.add_book(title: 'Some nonsense')
dan_brown.store 'StreamName'
```

This works all well and good... But I'd like to be able to be able to have a stream for the book _in addition to_ the stream for the author. Is there a built-in way of doing this? How would you recommend handling something like this?

**Comment by joelvh** [comment]
@mattgrande you would want to manage the book separately and then add the book ID to the author, potentially.

**Comment by joelvh** [comment]
Yeah, exactly. Aggregate roots should manage entities that only that aggregate root needs and aren't referenced by other aggregate roots. Seems authors and books can exist separately from each other. Therefore, they should manage their own states. If you reference an external entity, reference by ID -- don't pass in that entity's data.

Your read models might be where you possibly combine data from multiple entities.

**Comment by joelvh** [comment]
*Aggregate roots should only manage the state (data) of entities that are *not* referenced by other aggregate roots.

**Comment by mattgrande** [comment]
Thank you very much!
