### ISSUE TITLE
Reseting broker

### ISSUE THREAD

**Issue by swistak35** [RailsEventStore/rails_event_store#435]
In one of our applications, we've faced with rails errors `"A copy of SomeHandlerClassName has been removed from the module tree but is still active!"`. Our subscribing solutions was looking that way

`config/initializers/subscriptions.rb`
```
class ApplicationSubscriptions
  def call(event_store)
  # code which subscribe all handlers to all facts on given event store
  end
end

Rails.configuration.to_prepare do
  ApplicationSubscriptions.new.(Rails.configuration.event_store)
end
```

After changing some code in handlers, rails reloads the code and run `to_prepare`. The above code was adding new subscriptions, however it wasn't removing the old ones, so in there was dangling references to classes which were no longer attached to any constants, and that's how we were getting beforementioned error.

We've now patched event store to have method `#reset_broker!`:

```
  def reset_broker!
    @broker = RubyEventStore::PubSub::Broker.new(
      subscriptions: RubyEventStore::PubSub::Subscriptions.new,
      dispatcher: @dispatcher)
  end
```

and we've added the call `event_store.reset_broker!` before adding subscriptions in `ApplicationSubscriptions`.

1) What do you think about adding `#reset_broker!` to RubyES?
2) Maybe in RailsES we should reset the broker automatically (i.e. ship the `to_prepare` hook with the RailsES). That would however remove all subscriptions after code reload...
3) Maybe we should add to RailsES some standarized format of "subscriptions" file, and handle whole process ourselves (obviously interchangeable and not mandatory).

**Comment by swistak35** [comment]
As of standardized format of subscriptions file, we could for example
* by default have `YamlSubscriber`, which reads from some default file like `config/eventstore.yml`
* in usual case most programmers can just provide a class, which is subscribing the handlers in `#call(event_store)` like our `ApplicationSubscriptions`

So the constructor for the RailsEventStore client would be:

```
RailsEventStore::Client.new(subscriber: ApplicationSubscriptions)
```

and by default we would provide `YamlSubscriber` there.

**Comment by paneq** [comment]
As far as I know the recommended procedure works:

```ruby
Rails.application.configure do
  config.to_prepare do
    Rails.configuration.event_store = RailsEventStore::Client.new
    # add subscribers here
  end
end
```

and a new instance solves all the issues. Is there any reason you don't use new instance?

@swistak35 ?

**Comment by swistak35** [comment]
Currently mostly because I don't want to rely on the fact, that every place of our legacy application is always getting fresh event store directly from configuration. If event_store is passed as dependency during the class initialization like:

```
class Foo
   def initialize(event_store)
   end
end
```

And then that class, for any reason, lives for a long time in the application, then it will keep reference to old event store and GC won't collect old event store and old reloaded classes.

**Comment by paneq** [comment]
@swistak35 if there is a class which takes `event_store` as dependency and lives forever then isn't that class already broken in terms of handling rails-reloading ?

**Comment by paneq** [comment]
> And then that class, for any reason, lives for a long time in the application, then it will keep reference to old event store and GC won't collect old event store and old reloaded classes.

yes, but only in development. Is that an issue?

**Comment by paneq** [comment]
My recommendation is to localize code reloading problem in 1 place:

```ruby
Rails.application.configure do
  config.to_prepare do
    Rails.configuration.event_store = event_store = RailsEventStore::Client.new
    Rails.configuration.global = SomeGlobalIntegration.new(event_store)
  end
end
```

or use new instances 

```ruby
SomeGlobalIntegration.new(Rails.configuration.event_store)
```
