### ISSUE TITLE
AfterCommit AsyncProxyStrategy and Transactional Testing Issue

### ISSUE THREAD

**Issue by mpraglowski** [RailsEventStore/rails_event_store#439]
Transactional testing, whether by RSpec's use_transactional_fixtures or DatabaseCleaner's transactional cleaning strategy, is incompatible with the AfterCommit AsyncProxyStrategy.

The relevant code is as follows:

```
module AsyncProxyStrategy
  class AfterCommit
    def call(klass, event)
      if ActiveRecord::Base.connection.transaction_open?
        ActiveRecord::Base.
          connection.
          current_transaction.
          add_record(AsyncRecord.new(klass, event))
      else
        klass.perform_later(YAML.dump(event))
      end
    end
  end
end
```

Transactional testing always leaves an open transaction, and any after_commit hooks associated with this outermost transaction are never executed, instead of being scheduled immediately.

Please advise.

Regards,
Joseph

**Comment by paneq** [comment]
As far as I know it works fine since Rails 5:

* https://github.com/rails/rails/pull/18458
* https://github.com/grosser/test_after_commit

**Comment by paneq** [comment]
Clarification: AfterCommit callbacks are executed in transactions tests when there is 1 transaction opened  (the one wrapping whole test) but does that work with our code? I don't know. I believe it should. It would be nice to know more info (rails version) and have some code to reproduce.
