### ISSUE TITLE
Upgrade browser to Elm 0.19

### ISSUE THREAD

**Issue by pawelpacana** [RailsEventStore/rails_event_store#458]
- https://github.com/avh4/elm-upgrade
-  https://github.com/elm/compiler/blob/master/upgrade-docs/0.19.md
- https://github.com/rtfeldman/elm-spa-example/blob/master/src/Main.elm
- https://package.elm-lang.org/packages/elm/browser/latest/Browser#application

```
- NoRedInk/elm-json-decode-pipeline
  - [ ] Changes uses of Json.Decode.Pipeline.decode to Json.Decode.succeed
- elm/core
  - [ ] Replace uses of toString with String.fromInt, String.fromFloat, or Debug.toString as appropriate
- elm/html
  - [ ] If you used Html.program*, install elm/browser and switch to Browser.element or Browser.document
  - [ ] If you used Html.beginnerProgram, install elm/browser and switch Browser.sandbox
- elm/browser
  - [ ] Change code using Navigation.program* to use Browser.application
  - [ ] Use the Browser.Key passed to your init function in any calls to Browser.Navigation.pushUrl/replaceUrl/back/forward
- elm/url
  - [ ] Changes uses of Navigation.Location to Url.Url
  - [ ] Change code using UrlParser.* to use Url.Parser.*
```

**Comment by swistak35** [comment]
- NoRedInk/elm-json-decode-pipeline
  - [ ] Changes uses of Json.Decode.Pipeline.decode to Json.Decode.succeed
- elm/core
  - [ ] Replace uses of toString with String.fromInt, String.fromFloat, or Debug.toString as appropriate
- elm/html
  - [ ] If you used Html.program*, install elm/browser and switch to Browser.element or Browser.document
  - [ ] If you used Html.beginnerProgram, install elm/browser and switch Browser.sandbox
- elm/browser
  - [ ] Change code using Navigation.program* to use Browser.application
  - [ ] Use the Browser.Key passed to your init function in any calls to Browser.Navigation.pushUrl/replaceUrl/back/forward
- elm/url
  - [ ] Changes uses of Navigation.Location to Url.Url
  - [ ] Change code using UrlParser.* to use Url.Parser.*
