### ISSUE TITLE
Add AS::Notifications instrumentation for AggregateRoot

### ISSUE THREAD

**Issue by pawelpacana** [RailsEventStore/rails_event_store#460]
Useful to track EventSouring performance. I think from RES standpoint it makes sense to instrument `load` and `store`.

**Comment by andrzejkrzywda** [comment]
https://github.com/RailsEventStore/rails_event_store/issues/244 might be a good inspiration.

**Comment by mpraglowski** [comment]
Proposed implementation in #591
