### ISSUE TITLE
Migrating db to create RES tables crashes when RES is being initialised

### ISSUE THREAD

**Issue by mkolodziej** [RailsEventStore/rails_event_store#464]
If I generate the Rails Event Store migrations and add a Rails initializer with the code from the docs:

```
Rails.configuration.to_prepare do
  Rails.configuration.event_store = event_store = RailsEventStore::Client.new
end
```

and *then* run `rake db:migrate` (which happens in this order during deployment for example) then my migrations fail when Rails is initialised, because the RES initialisation requires the tables to exist:

`ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "event_store_events" does not exist`

For now I'm working around that by checking for:
`ActiveRecord::Base.connection.table_exists? :event_store_events`

at the beginning of the initialiser code, but perhaps this should be mentioned in the docs.

**Comment by andrzejkrzywda** [comment]
Thanks for submitting the issue, it's an interesting problem. Perhaps, as you say, we should inform about it better in the docs.

**Comment by pawelpacana** [comment]
Thank you for taking time to report this.

We do check for `event_store_events` table columns once database connection is established. It is a safety check for presence of legacy schema — not compatible with default adapter working with non-legacy schemas: https://github.com/RailsEventStore/rails_event_store/blob/2b123ef95a80318af4bb2273249b4add03fa9f25/rails_event_store_active_record/lib/rails_event_store_active_record/correct_schema_verifier.rb#L31-L33

This check will be dropped soon. But even sooner we could improve it by making this check conditional — only if the table already exists.

**Comment by pawelpacana** [comment]
@mkolodziej Would like to contribute such fix?

First we'd need reliable test case in `rails_event_store_active_record` to illustrate that under open database connection and without existing `event_store_events` table the repository cannot be initialized.

**Comment by fidel** [comment]
@mkolodziej it's fixed in https://github.com/RailsEventStore/rails_event_store/commit/9b6e745afba525598f80b678b3cdb65457a17c37. It should be released next week.

**Comment by pawelpacana** [comment]
I'd even say release this week

**Comment by fidel** [comment]
Underpromise, overdeliver ;)

**Comment by mkolodziej** [comment]
Thanks for fixing this. Sorry @pawelpacana, I overlooked notifications from this thread and didn't notice you were asking for a contribution. Will keep that in mind if I ever report any other issue :)
