### ISSUE TITLE
Missing docs to set up ruby_event_store-browser in a Rails env?

### ISSUE THREAD

**Issue by jasonjho** [RailsEventStore/rails_event_store#482]
Are there missing docs on how to set up the new `ruby_event_store-browser` in v0.33.0? I still see references to `rails_event_store-browser`, but that seems to have been deprecated.

**Comment by joelvh** [comment]
Hi @jasonjho have you looked at the docs here? https://railseventstore.org/docs/browser/

While not explicitly laid out, you could mount the Rack middleware (Sinatra) in your Rails routes.

Something like this?

```ruby
# Gemfile
gem 'ruby_event_store-browser'
gem 'sinatra'

# config/routes.rb
require 'ruby_event_store/browser/app'

Rails.application.routes.draw do
  mount RubyEventStore::Browser::App.for(
    event_store_locator: -> { Rails.configuration.event_store },
    path: '/res'
  ) => '/res'
end
```

**Comment by pawelpacana** [comment]
> Are there missing docs on how to set up the new ruby_event_store-browser in v0.33.0?

There are 😞 

What @joelvh mentioned is fine. In v0.32.0 this was what we recommended in deprecation period:

```ruby
            mount RubyEventStore::Browser::App.for(
               event_store_locator: -> { Rails.configuration.event_store },
               host: 'http://localhost:3000',
               path: '/res'
             ) => '/res' if Rails.env.development?
```

**Comment by pawelpacana** [comment]
Thank you @jasonjho and @joelvh! Docs have been updated. Related improvement to be discussed in #483.
