### ISSUE TITLE
Migrating existing events from YAML to JSON

### ISSUE THREAD

**Issue by jasonjho** [RailsEventStore/rails_event_store#484]
We currently have events using the default YAML serializer that writes to a TEXT column in our `event-store_events` table. We are looking to migrate to a JSON-based serializer and update all historical events to reflect this.

Been reading through https://railseventstore.org/docs/migrating_messages/ and https://railseventstore.org/docs/mapping_serialization/, which helps, but it's still unclear how to best migrate these events in the case of a serializer change. Would using the out of box JSON serializer assume writes to the TEXT column? Or does one need to add a migration to add a `json` or `jsonb` column to hold this data?  

Any tips would be greatly appreciated.  Thanks!

**Comment by jasonjho** [comment]
```Another valid use-case can be when you decide to migrate to a different mapper (ie from YAML to Protobuf).```

Is this even possible w/ the event_store API?  Seems that in order for the read batch operation to work, you'd need the appropriate serializer tied to the mapper. How does one migrate mappers when only one is specified to the client?

**Comment by mpraglowski** [comment]
@jasonjho have you managed to migrate to JSON ?

I've started to dig into this today. The very simple & naive implementation could be:

```
yaml_res = RailsEventStore::Client.new(mapper: RubyEventStore::Mappers::Default.new(serializer: YAML))
json_res = RailsEventStore::Client.new(mapper: RubyEventStore::Mappers::Default.new(serializer: JSON))

OrderExpired = Class.new(RailsEventStore::Event)
# test data
(1..10).each{|x| yaml_res.publish(OrderExpired.new(data: { key: x, text: "some-#{x}"}), stream_name: "stream$#{x}")}

# before migrate
RailsEventStoreActiveRecord::Event.last
# => #<RailsEventStoreActiveRecord::Event id: "f34ce40d-0786-43d7-8349-6009f3524281", event_type: "OrderExpired", metadata: "---\n:timestamp: 2018-11-02 14:03:33.037608000 Z\n", data: "---\n:key: 1\n:text: some-1\n", created_at: "2018-11-02 14:03:33">
yaml_res.read.each.first
# => #<OrderExpired:0x00007fc49d4510a0 @event_id="808db36b-ee91-4f62-a5ab-e8c5c03f0dad", @metadata=#<RubyEventStore::Metadata:0x00007fc49d451000 @h={:timestamp=>2018-11-02 14:05:42 UTC}>, @data={:key=>1, :text=>"some-1"}>

# migrate
yaml_res.read.in_batches.each_batch{|e| json_res.overwrite(e.to_a)}

# after migrate
RailsEventStoreActiveRecord::Event.last
# => #<RailsEventStoreActiveRecord::Event id: "f34ce40d-0786-43d7-8349-6009f3524281", event_type: "OrderExpired", metadata: "{\"timestamp\":\"2018-11-02 14:03:33 UTC\"}", data: "{\"key\":1,\"text\":\"some-1\"}", created_at: "2018-11-02 14:03:33">
```

Seems all ok until now but then I got some `ArgumentError` while trying to read from `json_res` using read specification `json_res.read.each.first`.

**Comment by pawelpacana** [comment]
@mpraglowski @jasonjho That `ArgumentError` comes from metadata keys being serialized as strings. Please see https://github.com/RailsEventStore/rails_event_store/issues/367 for detailed explanation.
