### ISSUE TITLE
Minor documentation bugs

### ISSUE THREAD

**Issue by jasonjho** [RailsEventStore/rails_event_store#485]
Found a few minor documentation errors that I found while upgrading to v0.33.0. I imagine many people will attempt to copy/paste certain config fragments cited in the doc pages, so it might be worth combing through some obvious errors.

In the [subscribe](https://github.com/RailsEventStore/rails_event_store/blob/master/railseventstore.org/source/docs/subscribe.html.md) docs under **Scheduling async handlers after commit**:

```ruby
event_store = RailsEventStore::Client.new(
  dispatcher: ComposedDispatcher.new(
    RailsEventStore::AfterCommitAsyncDispatcher.new(scheduler: RailsEventStore::ActiveJobScheduler),
    RubyEventStore::PubSub::Dispatcher.new
  )
)
```

1. ComposedDispatcher needs to be prefixed: `RubyEventStore::ComposedDispatcher` otherwise you will get a `NameError`.

2. `RailsEventStore::ActiveJobScheduler` => `RailsEventStore::ActiveJobScheduler.new`. If not instantiated when passed into `AfterCommitAsyncDispatcher`, the `verify` method won't be found.

Hope this helps!

**Comment by mpraglowski** [comment]
Thanks for reporting that. Fixed.
