### ISSUE TITLE
Events serialization / deserialization performance

### ISSUE THREAD

**Issue by mpraglowski** [RailsEventStore/rails_event_store#50]
Here a benchmarks for different serialization formats in Ruby: https://gist.github.com/havenwood/4513627#file-benchmark_results-rb

http://azranel.github.io/programming/rubyserializationformats/

When stream will grow to thousands of events this might be an issue.

**Comment by paneq** [comment]
@mpraglowski It's important to run our own benchmarks with some assumptions. I once checked my own and even the JSON speed varied depending on whether I was serializing hashes or arrays of arrays in JSON :)

btw you might be interested that protobuf in latest version has ruby implementation https://github.com/google/protobuf/releases/tag/v3.0.0

**Comment by paneq** [comment]
And protobuf3 has JSON mapping https://developers.google.com/protocol-buffers/docs/proto3#json , so I think you can store in JSON but in a way that guarantees other languages could easily read it with all supported types.

**Comment by mpraglowski** [comment]
Use of protobuf3 might be a nice fit also for #27

**Comment by pawelpacana** [comment]
Reminded me of some benchmarks I did: https://github.com/arkency/rails-event-store-serialization-benchmarks/blob/master/results.txt

**Comment by pawelpacana** [comment]
Not sure what is this issue for. Fast-forward from 2016 and we now support other mappers :wink:

I guess such comparison, in the context on RES, is worth a blog post or documentation entry -- which serializer to choose and why.
