### ISSUE TITLE
Cannot read events when using `of_type`

### ISSUE THREAD

**Issue by mattgrande** [RailsEventStore/rails_event_store#517]
Hi all, I'm reading the documentation on this page: https://railseventstore.org/docs/read/

I'm trying to read all events of a given type:

```
client = Rails.configuration.event_store
scope = client.read
              .stream('all')
              .limit(100)
              .of_type([JobStarted, JobStopped])
```

This gives me the following error:

```
NoMethodError: undefined method `of_type' for #<RubyEventStore::Specification:0x00007fc766bcbf58>
```

What am I doing wrong? Is there a better way to read all events of a specific type?

(Relevant versions: Ruby 2.5.1, Rails 5.2.1.1, RES 0.31.1)

**Comment by pawelpacana** [comment]
The `of_type` has been added in https://github.com/RailsEventStore/rails_event_store/releases/tag/v0.34.0 and is not available on version you're currently running (0.31.1).

We keep https://railseventstore.org/docs/ up-to-date with latest released version (0.35.0 at the moment).

The closest you can get with an API of 0.31.1 is:

```ruby
client = Rails.configuration.event_store
scope = client.read.limit(100)

scope.each.select { |event| [JobStarted, JobStopped].include?(event.type) }   
```

That would however filter after reading from data store, not when querying like we do in 0.34.0 and after.

**Comment by pawelpacana** [comment]
Btw. specifying `.stream('all')` is redundant if you want to target all events (no filtering by stream).

**Comment by mattgrande** [comment]
Thanks for your help @pawelpacana; I'll see if I can get up the the latest version.

Is there anywhere in the docs where it says what version functions were added in?

**Comment by pawelpacana** [comment]
Browsing https://github.com/RailsEventStore/rails_event_store/releases is the best you can do. We don't have docs per release version at the moment.

**Comment by pawelpacana** [comment]
For `of_type` to work efficiently you'd also need an index on database column. That it highlighted in changelog:

<img width="808" alt="zrzut ekranu 2018-12-18 o 15 08 33" src="https://user-images.githubusercontent.com/116740/50159479-17153200-02d7-11e9-85dc-4db780c59c44.png">


What kind of database are you on, Postgresql?

**Comment by mattgrande** [comment]
Yep, I'm on Postgres. I'll ensure I go through the changelogs carefully when I upgrade. Thanks!
