### ISSUE TITLE
Batch events for multiple aggregate roots

### ISSUE THREAD

**Issue by joelvh** [RailsEventStore/rails_event_store#539]
I have commands that sometimes use multiple aggregate roots. I want to store the events generated by all aggregate roots to be batched into a single transaction with RES so that, in case there is a version conflict, all events for multiple aggregates are rejected. Currently, if the the last aggregate causes a version conflict, the aggregates that were stored before it may not get rolled back.

What do you  think about 1) batching events for multiple streams (which is what this implies) and 2) implementing this as part of the Aggregate Root gem?

**Comment by paneq** [comment]
From conceptual standpoint: The point of Aggregate root is guard transactional constraints. By the book, you should use async messages to communicate between ARs and use pattern like saga to synchronize to changes to multiple of them. Or you need a bigger aggregate. 

From technical standpoint. I don't know how to do it in ROM based repo, but in ActiveRecord based repo, you could just wrap everything in `ActiveRecord::Base.transaction{}` and that would be all. If you get an exception at any point, you would rollback everything and be done with it (assuming your handlers are configured to be processed post-commit).

I don't think we should encourage coupling multiple aggregate roots together.

**Comment by mpraglowski** [comment]
Closing for now. Please reopen in case of more questions/thoughts.
