### ISSUE TITLE
Extract lint for mappers

### ISSUE THREAD

**Issue by pawelpacana** [RailsEventStore/rails_event_store#551]
There's a set of expectations for mappers which are not enforced evenly. `NullMapper` spec can be a good example where such lint could have helped. Given one would likely want to replace that part in RES (i.e. introducing their own `EncryptionMapper`) it makes sense to have a shared set of tests for it.

We're currently using shared examples of rspec for that purpose:  
https://github.com/RailsEventStore/rails_event_store/tree/master/ruby_event_store/lib/ruby_event_store/spec
RailsEventStore/rails_event_storeTod

**Comment by pawelpacana** [comment]
@mpraglowski done?

**Comment by mpraglowski** [comment]
Done in #553

**Comment by pawelpacana** [comment]
@mpraglowski #553 was about linting Event, not Mappers ;)
