### ISSUE TITLE
The problem with NullMapper

### ISSUE THREAD

**Issue by pawelpacana** [RailsEventStore/rails_event_store#552]
With [NullMapper](https://github.com/RailsEventStore/rails_event_store/issues/321) combined with `InMemoryRepository` one can have a decent and fast setup for testing. The speed comes from the fact that for in-memory storage no serialization is needed.

In fact `NullMapper` does not convert given event object to `SerializedRecord` instance. Yet the repositories assume such. It mostly worked given event instance responds to `event_id`, `data` and `metadata`.

With the introduction of `of_type` to `Specification` such implementation of `NullMapper` no longer fits assumptions — responding to `event_type` is required. What is more `Event` and `SerializedRecord` have differing `to_h` and `==` implementations making `NullMapper` behavior even more questionable.

Making `NullMapper` use `SerializedRecord` is currently not possible due to [requirement](https://github.com/RailsEventStore/rails_event_store/blob/master/ruby_event_store/lib/ruby_event_store/serialized_record.rb#L5) of `data` and `metadata` to be strings. But an object imitating `SerializedRecord` is still an option. I'm not sure how then `NullMapper` will fit into the scenario where one primarily uses `Protobuf` mapper (and possibly other sophisticated mappers).

Will introducing #400 change anything here? Is it that we only want a behavior where `data` and `metadata` remain unchanged?

**Comment by pawelpacana** [comment]
Wdyt @paneq @joelvh @fmwr?

**Comment by paneq** [comment]
> But an object imitating `SerializedRecord` is still an option. 

```ruby
class UnserializedRecord < Struct.new(:domain_event)
  delegate :event_id, :data, :metadata, to: :domain_event
  def event_type
    domain_event.type
  end
end
```

Perhaps such thin wrapper would still be fast enough and the cost of one more object is not that high as long as we avoid serialization.

Mapper would map to `UnserializedRecord` which has `SerializedRecord`-like interface and unmap from it. Basically that class would be like a cache entry to keep the domain event attached to it.

`UnserializedRecord` - :trollface: 😉 

> I'm not sure how then `NullMapper` will fit into the scenario where one primarily uses `Protobuf` mapper (and possibly other sophisticated mappers).

My guess right now is that it would fit nicely and passing [`Proto`](https://github.com/RailsEventStore/rails_event_store/blob/2aedb54d6b18141cd63a53b6025a1f8dccb97271/ruby_event_store/lib/ruby_event_store/mappers/protobuf.rb#L2) instance as a constructor argument should work just as fine as passing `RES::Event`. 

wdyt @pawelpacana ?

**Comment by pawelpacana** [comment]
Btw. introducing test to present an issue would be good first step.

**Comment by pawelpacana** [comment]
Having symmetry in domain event and serialized record regarding type method is also something I'd consider.
