### ISSUE TITLE
Potential limits

### ISSUE THREAD

**Issue by anderslemke** [RailsEventStore/rails_event_store#566]
Hi there, 👋

I was wondering if any of you have any experience in finding an upper limit of events stored in RailsEventStore?

At Zetland we rely heavily on RailsEventStore for almost everything, an my biggest nightmare is that the underlying PostgreSQL starts performing worse, potentially bringing everything down.

I know that PostgreSQL says that there is no upper limit on rows in a table, but my concern is that that claim is more theoretical than practical.

We're running rails_event_store 0.1.3 and our events table is created before https://github.com/rails/rails/pull/26266 so the `id` is an `integer` not `bigint`. So first of all, we'll need to get that sorted.

Currently we have about 80 millions events.

I'm profiling "saving events", and "loading aggregates".
Over the last year they seem stable. That is, with a robust trend going slightly upwards a few ms.

Saving an event takes about 30ms and building an aggregate, including fetching events from the event store, takes around 300ms.

Now, back to my nightmare. What do I do, if PostgreSQL starts degrading?

Right now, the only thing I can think of is some kind of sharding, where I introduce one or more new event stores in separate databases, and on aggregate-level decide which event store it uses.

I would love to hear about thoughts and experiences if you're willing to share.

**Comment by AbdulazizGH** [comment]
>At Zetland we rely heavily on RailsEventStore for almost everything, an my biggest nightmare is that the underlying PostgreSQL starts performing worse, potentially bringing everything down.


We're in a similar situation here. Our platform is mainly powered by RailsEventStore as a sub/pub messaging bus, and we've been racking tens of millions of event records over time.

We've yet to face any problems with scalability as of today, but we might hit a wall fairly soon. We're already thinking about database sharding(which is a huge pain in itself), or even dropping PSQL all together in favour of in-memory storage(Redis, Memcache, etc) to help scale the platform, but we're not yet sure about the ramifications of such change(for starters, loss of persistant event storage.)

We'd love to hear any success stories with scaling RailsEventStore too.

**Comment by pawelpacana** [comment]
> I was wondering if any of you have any experience in finding an upper limit of events stored in RailsEventStore?

I haven't seen this limit yet on projects I've consulted. The biggest deployment I helped is now approaching 200_000_000 events. That was not Postgresql however.

On [wrocloverb](http://wrocloverb.com) I've learned about a deployment of an older RES version storing an order of magnitude more events. I don't however recall performance issues from that chat.

If I'm not mistaken, @andrzejsliwa might have some experience with large postgresql deployment and performance degradation of huge table.

> Now, back to my nightmare. What do I do, if PostgreSQL starts degrading?

I'd consult an expert on postgresql first. I don't consider myself the one. If I remember correctly, postgres 10 and 11 received lots of improvements around table partitioning. That might help once the table becomes difficult to work on (https://blog.heroku.com/handling-very-large-tables-in-postgres-using-partitioning).

> I'm profiling "saving events", and "loading aggregates".
> Over the last year they seem stable. That is, with a robust trend going slightly upwards a few ms.

I'd love to have such profiling measured per RES release! But indeed some part of it is influenced in growing length of the database table.

> Saving an event takes about 30ms and building an aggregate, including fetching events from the event store, takes around 300ms.

Btw. do you know how much of the time is spent in mapper serializing/deserializing? I've did some comparisons between serializers: https://github.com/RailsEventStore/rails_event_store/issues/50

**Comment by pawelpacana** [comment]
For the reference: https://www.postgresql.org/docs/11/ddl-partitioning.html
