### ISSUE TITLE
subscribers syntax

### ISSUE THREAD

**Issue by casiodk** [RailsEventStore/rails_event_store#570]
It would be nice to be able to this

```
event_store.subscribe(
  event: Event::SomeEventHappened
    subscribers: [
      EventHandler,
    ]
)
```

instead of this
```
event_store.subscribe(
  EventHandler,
    to: [
      Event::SomeEventHappened
    ]
)
```

**Comment by casiodk** [comment]
i think it gives a better overview, to be able to list the events that happened and see which handlers are subscribed to those...

**Comment by mpraglowski** [comment]
It depends :) For me more natural way of reading seems to be the current version:

subscribe `SomeHandler` to: `ArrayOfEventsItShouldProcess`

Because it is handler what is subscribed, not the event.

If you prefer to have it the other way around the best solution now is to use your adapter class for event store client & define your own version of `subscribe` method.

**Comment by mpraglowski** [comment]
> i think it gives a better overview, to be able to list the events that happened and see which handlers are subscribed to those...

Some visualisation of what is subscribed to which events would be nice :) It could be part of debugging/management API and presented in EventStore Browser.

**Comment by casiodk** [comment]
what about
```
event_store.subscriptions(
    subscribe: [EventHandler, EventHandlerB],
    to: [Event::SomeEventHappened]
)
```
for more flexibility

**Comment by mpraglowski** [comment]
https://www.rubydoc.info/gems/ruby_event_store/RubyEventStore/Client#subscribe-instance_method

`subscribe` returns a proc to unsubscribe (remove subscriptions), with several handlers it would be unclear what unsubscribe proc would do - should it unsubscribe all of them? What if you need to remove only one subscription? Or maybe we should return an array of unsubscribe procs? 

I think it is easier to make some abstraction over subscriptions in your app - define your subscriptions as you want and the best way to make it clear for you and then write a method to subscribe it using RES subscription API.
