### ISSUE TITLE
Testing Async EventHandlers

### ISSUE THREAD

**Issue by casiodk** [RailsEventStore/rails_event_store#573]
I have this class

```
# frozen_string_literal: true

module EventHandlers
  class SomeClassAsync < ApplicationJob
    prepend RailsEventStore::CorrelatedHandler
    prepend RailsEventStore::AsyncHandler
    queue_as :instant_offers_default

    def perform(event)
      EventHandlers::SomeClass.new.call(event)
    end
  end
end
```

How would I test this?

**Comment by pawelpacana** [comment]
What would you like to test, an integration? In that case you'd most likely want to assert on side effects of this handler once a particular event is published. It might help to change AJ backend for test environment (i.e. https://api.rubyonrails.org/classes/ActiveJob/QueueAdapters/InlineAdapter.html) or ensure equeued job are performed before asserting (https://edgeapi.rubyonrails.org/classes/ActiveJob/TestHelper.html#method-i-perform_enqueued_jobs). With `sidekiq` outside of `ApplicationJob` I'd call `EventHandlers::SomeClassAsync.drain` to ensure an async job is executred before assertion.

Without asserting on side effects you can assert on the fact that this particular handler (as a job) has been enqueued: https://edgeapi.rubyonrails.org/classes/ActiveJob/TestHelper.html#method-i-assert_enqueued_with.

If you're less interested in an integration test then `EventHandlers::SomeClass#call` is your subject under test.

**Comment by pawelpacana** [comment]
Btw. check out https://blog.arkency.com/tags/testing/
