### ISSUE TITLE
EncryptionMapper ciphertext and non-binary encoder

### ISSUE THREAD

**Issue by pawelpacana** [RailsEventStore/rails_event_store#590]
It came to my attention that currently you cannot use EncryptionMapper with JSON serializer. The reason for that is the binary output of openssl encrypt. 

What works with default YAML, will not work with JSON for that matter. Encoding ciphertext with [Base64](https://github.com/attr-encrypted/attr_encrypted/blob/master/lib/attr_encrypted.rb#L49-L57) can be an option to ensure safe string is passed futher to JSON and alike.

My concerns:
- how to introduce it in a backwards compatible-way (in presence of existing cryptograms from previous releases that must decrypt well)
- how to make it optional (after all that might not be needed for binary-aware encoders or database fields)

**Comment by mpraglowski** [comment]
> how to introduce it in a backwards compatible-way (in presence of existing cryptograms from previous releases that must decrypt well)

The solution is to have it as a separate transformation in #572 - then current EncryptionMapper could skip this step is YAML serializer is used and new solutions should use valid pipeline with Base64 transformation.

**Comment by mpraglowski** [comment]
> how to make it optional (after all that might not be needed for binary-aware encoders or database fields)

Again #572 - and define it as a separate transformation. Then developer will be able build his own pipeline that suits his needs.

**Comment by pawelpacana** [comment]
> new solutions should use valid pipeline with Base64 transformation

That might work indeed. Information about encrypted attributes lives in metadata and such transformation could use it.
