### ISSUE TITLE
JSON data type support for ActiveRecord

### ISSUE THREAD

**Issue by scottbartell** [RailsEventStore/rails_event_store#592]
Is there any reason why the [ActiveRecord db migration](https://github.com/RailsEventStore/rails_event_store/blob/master/rails_event_store_active_record/lib/rails_event_store_active_record/generators/templates/create_event_store_events_template.rb#L24:L25) doesn't allow the data type for `data` and `metadata` to be configured to JSON or JSONB [like the ROM Adapter db migration](https://github.com/RailsEventStore/rails_event_store/pull/524)?

**Comment by pawelpacana** [comment]
No specific reason, it just hasn't been done yet. For the time being, you can modify the migration that is generated to suit your needs.

Having the possibility to tell `data` and `metadata` type for migration would be a welcome addition.

**Comment by pawelpacana** [comment]
Thank you for the contribution 💙
