### ISSUE TITLE
AggregateRoot breaking changes

### ISSUE THREAD

**Issue by joelvh** [RailsEventStore/rails_event_store#596]
@pawelpacana ran into several issues with the AggregateRoot refactoring (#579, #584, #587, #588), which came to light when I started using the ROM updates on `master`. (For some reason, setting the git source of the `ruby_event_store-rom` causes Bundler to also use git for `aggregate_root`, even when I don't want it to. Any help there might alleviate this issue.)

1. We track command/aggregate/entity/event relationships in the Ruby class hierarchy and relationships. Therefore, we use `on_methods` to understand what events an aggregate emits. Changing from class to event name is a breaking change for us.
2. We pass an aggregate ID to the constructor, so #587 breaks things for us. We're setting the instance variable manually for the time being.
3. I've run into a situation where the default strategy doesn't detect the `on_*` private methods in the production mode web server and throws an exception looking for the `apply_*` method naming convention as a fallback. Checking console in production mode, the methods seem to be there -- still looking into why there is a problem when using aggregates in the web server. (I presume it is something on our end, but...) I was wondering if maybe we can have the `on_*` methods be renamed to `apply_*` so that they follow the same naming convention? Why have them different? (To combine both handler scenarios at the same time?)

Will report back as I figure out what is going on.

**Comment by joelvh** [comment]
@pawelpacana found the issue -- your fix to appease mutant removed the inheritance chain for `@on_methods`, so any events handled in a subclass creates methods, but the `on_methods` hash is empty when the default strategy applies the event.

Either we can have the default strategy look at `aggregate.class.on_methods` based on the aggregate passed to the strategy, or we re-introduce the `@on_methods` ancestor chain.

I'll see if I can put a PR together in the meantime.

**Comment by joelvh** [comment]
See #597

**Comment by pawelpacana** [comment]
Thanks, I'll have a look on a test case!

**Comment by joelvh** [comment]
@pawelpacana can #597 be merged?

**Comment by pawelpacana** [comment]
Test case looks good, thanks. Merged and resolved. I'll have another spike, with that case covered now
