### ISSUE TITLE
Personalization of causation/correlation/type streams for browser

### ISSUE THREAD

**Issue by swistak35** [RailsEventStore/rails_event_store#626]
Currently, displaying links (at browser) to correlation / causation / type streams work with assumption that our `LinkBy*` handlers are used with default prefix (`$by_correlation_`, `$by_causation_`, `$by_type_`) and with default metadata field (`correlation_id`, `causation_id`, event type).

There are two parts of this task:
* ability to customize stream names in browser configuration (`$by_correlation_`, `$by_causation_`, `$by_type_` mentioned above)
* ability to customize the metadata fields used for that streams (`correlation_id`, `causation_id`)

IMO the first task is more important than the second.

**Comment by pawelpacana** [comment]
Is this still an issue?

**Comment by grncdr** [comment]
The behavior mentioned above is still the case, and still confusing.

If you don't set up the `LinkBy` handlers as described in https://railseventstore.org/docs/v1/correlation_causation/#building-streams-based-on-correlation-id-and-causation-id those elements are still shown in the browser, but link to empty streams.

What I don't understand is why the ShowEvent view doesn't just show all streams an event is linked into? That would be much more useful to for me.

**Comment by pawelpacana** [comment]
> What I don't understand: why doesn't the ShowEvent view just show links to all streams that contain the event? That would be much more useful to me.

Good question! There's already an API for that — `streams_of(event_id)`. I have to remind myself if there were any performance implications.

**Comment by pawelpacana** [comment]
> What I don't understand: why doesn't the ShowEvent view just show links to all streams that contain the event? That would be much more useful to me.

Scheduled for next release.
