### ISSUE TITLE
Wrong number of arguments for after_commit_async_dispatcher

### ISSUE THREAD

**Issue by jasonjho** [RailsEventStore/rails_event_store#631]
I ran into this recently, but not sure what could be causing the wrong number of arguments -- given that the method doesn't seem to be defining expected arguments.

Any ideas?  

RailsEventStore version 0.34.0
Rails 6.0.0.rc1

```Internal Server Error: wrong number of arguments (given 1, expected 0) /usr/local/bundle/gems/rails_event_store-0.34.0/lib/rails_event_store/after_commit_async_dispatcher.rb:35:in `committed!'
/usr/local/bundle/gems/activerecord-6.0.0.rc1/lib/active_record/connection_adapters/abstract/transaction.rb:126:in `block in commit_records'
/usr/local/bundle/gems/activerecord-6.0.0.rc1/lib/active_record/connection_adapters/abstract/transaction.rb:126:in `each'
/usr/local/bundle/gems/activerecord-6.0.0.rc1/lib/active_record/connection_adapters/abstract/transaction.rb:126:in `ensure in commit_records'
/usr/local/bundle/gems/activerecord-6.0.0.rc1/lib/active_record/connection_adapters/abstract/transaction.rb:126:in `commit_records'
/usr/local/bundle/gems/activerecord-6.0.0.rc1/lib/active_record/connection_adapters/abstract/transaction.rb:257:in `block in commit_transaction'
/usr/local/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
/usr/local/bundle/gems/activerecord-6.0.0.rc1/lib/active_record/connection_adapters/abstract/transaction.rb:247:in `commit_transaction'
/usr/local/bundle/gems/activerecord-6.0.0.rc1/lib/active_record/connection_adapters/abstract/transaction.rb:285:in `block in within_new_transaction'
/usr/local/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
/usr/local/bundle/gems/activerecord-6.0.0.rc1/lib/active_record/connection_adapters/abstract/transaction.rb:270:in `within_new_transaction'
/usr/local/bundle/gems/activerecord-6.0.0.rc1/lib/active_record/connection_adapters/abstract/database_statements.rb:277:in `transaction'
/usr/local/bundle/gems/activerecord-6.0.0.rc1/lib/active_record/transactions.rb:212:in `transaction'
/usr/local/bundle/gems/jsonapi-resources-0.9.8/lib/jsonapi/acts_as_resource_controller.rb:92:in `block in transaction'
/usr/local/bundle/gems/jsonapi-resources-0.9.8/lib/jsonapi/operation_dispatcher.rb:42:in `transaction'
/usr/local/bundle/gems/jsonapi-resources-0.9.8/lib/jsonapi/operation_dispatcher.rb:24:in `process'
/usr/local/bundle/gems/jsonapi-resources-0.9.8/lib/jsonapi/acts_as_resource_controller.rb:86:in `block in process_operations'
/usr/local/bundle/gems/activesupport-6.0.0.rc1/lib/active_support/callbacks.rb:101:in `run_callbacks'
/usr/local/bundle/gems/jsonapi-resources-0.9.8/lib/jsonapi/acts_as_resource_controller.rb:85:in `process_operations'
/usr/local/bundle/gems/jsonapi-resources-0.9.8/lib/jsonapi/acts_as_resource_controller.rb:77:in `process_request'
/usr/local/bundle/gems/jsonapi-resources-0.9.8/lib/jsonapi/acts_as_resource_controller.rb:44:in `update'```

**Comment by pawelpacana** [comment]
Can you verify this is no longer the case on v0.36.0? 

https://github.com/RailsEventStore/rails_event_store/pull/519
https://github.com/RailsEventStore/rails_event_store/releases/tag/v0.36.0

**Comment by pawelpacana** [comment]
> not sure what could be causing the wrong number of arguments

I'd expect this is triggered by an exception raised in one of the `after_commit` callbacks. In such case Rails would call `committed!` with additional argument:

https://github.com/rails/rails/blob/2c3332cc4c0fa77dbe2e13e8a792f80fbd8f4ad3/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb#L122-L139

**Comment by pawelpacana** [comment]
It seems that has changed for Rails 6, and now there's always a keyword argument passed:
https://github.com/rails/rails/blob/2c3332cc4c0fa77dbe2e13e8a792f80fbd8f4ad3/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb#L122-L139

**Comment by jasonjho** [comment]
@pawelpacana Awesome. Thank you for the quick turnaround. We'll test it on 0.36.0. I wonder though if it's just better to upgrade directly to 0.40.0? Are there any major breaking changes between them?

**Comment by pawelpacana** [comment]
> I wonder though if it's just better to upgrade directly to 0.40.0

When preparing releases I focus on documenting breaking changes since last release. I think it is now (before 1.0) safer to upgrade to nearest release. That way you have a chance to notice deprecation warnings before removals (as that might happen in next release after deprecation was introduced).
