### ISSUE TITLE
"incorrect" links to streams

### ISSUE THREAD

**Issue by swistak35** [RailsEventStore/rails_event_store#642]
The browser generates "incorrect" links to streams. They are incorrect, but because we have SPA app which doesn't really care what's in URL before fragment part, they work until someone will send the link to another person.

Reproduction steps:
1. Have browser mounted in subdirectory, like `myapplication.com/resbrowser`
2. Go to the browser
3. Click some event
4. Click on some stream link, it will be `myapplication.com/#streams/<stream_name>` instead of `myapplication.com/resbrowser/#streams/<stream_name>`.

**Comment by pawelpacana** [comment]
We pass `rootUrl` as a flag: https://github.com/RailsEventStore/rails_event_store/blob/master/ruby_event_store-browser/lib/ruby_event_store/browser/app.rb#L43

When not explicitly set, its value comes from `request.script_name`: https://github.com/RailsEventStore/rails_event_store/blob/master/ruby_event_store-browser/lib/ruby_event_store/browser/app.rb#L52. That should reflect mount point.

Is that v0.40 thing?

**Comment by pawelpacana** [comment]
In short, `rootUrl` should be used when building link URLs. It already contains the mount point.

<img width="964" alt="Zrzut ekranu 2019-07-3 o 20 50 06" src="https://user-images.githubusercontent.com/116740/60617515-33d90900-9dd4-11e9-9767-4acab56d19b0.png">


https://github.com/RailsEventStore/rails_event_store/blob/ab185e6cc7e1be01bb1f00076cc72e03f80784a2/ruby_event_store-browser/elm/src/Flags.elm#L5
