### ISSUE TITLE
Unsubscribing from subscriptions

### ISSUE THREAD

**Issue by pawelpacana** [RailsEventStore/rails_event_store#649]
There's no mention of subscription return value and how this callable can be used to unsubscribe:

https://github.com/RailsEventStore/rails_event_store/blob/cfc91c9cb367e514ba1c6de1a711a7610780b520/ruby_event_store/lib/ruby_event_store/spec/subscriptions_lint.rb#L60-L102

**Comment by mpraglowski** [comment]
Documented in https://github.com/RailsEventStore/rails_event_store/commit/0988295db88d9c71290196cf81a82889f2dbad31
