### ISSUE TITLE
Allow event stream position to be auto-incremented to support concurrent inserts

### ISSUE THREAD

**Issue by brentsnook** [RailsEventStore/rails_event_store#661]
We currently have several background workers that publish events in an aggregate specific stream. We have a synchronous reactor that then links these events in an overall stream for the month with `expected_version: :auto`.

```ruby
  class LinkEventsToMonthStreamReactor
      def call(event)
        Rails.configuration.event_store.link(
          event.event_id,
          stream_name: "monthly$#{Date.parse(event.data[:date]).strftime('%Y-%m')}",
          expected_version: :auto
        )
      end
   end
```

We are seeing a lot of `RubyEventStore::WrongExpectedEventVersion` errors and I'm guessing it is because of the way last version is read in this case:

https://github.com/RailsEventStore/rails_event_store/blob/c20e365daaead2faed4e467774762c3caacb11f1/rails_event_store_active_record/lib/rails_event_store_active_record/event_repository.rb#L72

For our scenario we just want several events to be inserted at the end of the stream. I know the [guarantees](https://railseventstore.org/docs/expected_version/#auto) of the `:auto` method state that it won't handle multiple concurrent writes explicitly but it would be useful if it or a different method did.

Is it possible to somehow use something like an auto-increment column and avoid the insert specifying an exact version to allow for multiple concurrent inserts at the end of a stream?

As a workaround we'll probably just catch the error and retry a few times.

**Comment by swistak35** [comment]
Hi, thanks for using Rails Event Store :) If you don't care about the order of the events added to stream at the same time, then I believe the best strategy for you would be `:any` strategy.

`:any` strategy preserves the order of the events as they are pushed, it's just that it does not specify the order of the events which are pushed at the same time -- meaning, there's no locking mechanism, so if we append event `X`, we don't know the specific event `Y` it will be succeeding. But as I understand from your description, you don't care about that and want just to push the events at the end of the stream.

They are ordered by the auto-incremented column (`id` from `event_store_events_in_streams`), just as you suggest: https://github.com/RailsEventStore/rails_event_store/blob/c566b8fb300ab854f46747f8147c8a752c65f840/rails_event_store_active_record/lib/rails_event_store_active_record/event_repository_reader.rb#L50


One disclaimer though: You should not mix strategies `:any` and `:auto`/explicit numbers for one stream. It cause that in the `position` column some of the values are integers, and some are NULLs, and the resulting order is rather unexpected (you may want to read https://github.com/RailsEventStore/rails_event_store/issues/425#issuecomment-411640721)

**Comment by brentsnook** [comment]
@swistak35 we already considered the `:any` strategy but it doesn't do what we need

We'd like the events in the stream to still have a position - that way events can be written to the same stream from an aggregate as well as a reactor and still be read out in a consistent order. We'd like reactors that are inserting not to care about last position, allowing for concurrent inserts to the stream. We want aggregates to still benefit from the optimistic locking behaviour that you get from stream positions in this case.

**Comment by pawelpacana** [comment]
>  that way events can be written to the same stream from an aggregate as well as a reactor and still be read out in a consistent order

From what you've described it sounds like you might benefit more from using `:any` both in an aggregate and reactors and switching locking from optimistic to pessimistic in an aggregate itself (i.e. with Advisory Locks).

Pessimistic locking is not something supported in the `aggregate_root` gem. Several examples how to implement aggregates without this gem can be found in https://github.com/arkency/aggregates

**Comment by pawelpacana** [comment]
> Is it possible to somehow use something like an auto-increment column and avoid the insert specifying an exact version to allow for multiple concurrent inserts at the end of a stream?

I think that auto-increment should also be scoped to particular rows. Perhaps on Postgresql one could use [sequences](https://www.postgresql.org/docs/9.5/sql-createsequence.html), keeping in mind the drawbacks. 

At the moment the way to achieve a different insert strategy leads to [implementing your own event repository](https://railseventstore.org/docs/repository/#configure-custom-repository) and changing the way it appends events:
https://github.com/RailsEventStore/rails_event_store/blob/c566b8fb300ab854f46747f8147c8a752c65f840/rails_event_store_active_record/lib/rails_event_store_active_record/event_repository.rb#L14-L19

**Comment by brentsnook** [comment]
Thanks for the reply @pawelpacana, sorry about the delay in getting back.

Could it be possible to make the strategy for version/position configurable in the default event repository? For example, it might be able to be achieved by pushing this logic into the `expected_version` and making that a configurable strategy.

https://github.com/RailsEventStore/rails_event_store/blob/c20e365daaead2faed4e467774762c3caacb11f1/rails_event_store_active_record/lib/rails_event_store_active_record/event_repository.rb#L72

This would be easier than implementing a new repository. If I was to do that I'd probably extend the existing one but the interface to override the required bits cleanly needed isn't there.

**Comment by pawelpacana** [comment]
> Could it be possible to make the strategy for version/position configurable in the default event repository?

I think that might be doable — extracting the component responsible for calculating position and allowing it to be replaced with your own.

**Comment by brentsnook** [comment]
> > Could it be possible to make the strategy for version/position configurable in the default event repository?
> 
> I think that might be doable — extracting the component responsible for calculating position and allowing it to be replaced with your own.

Great, I'll create a separate more specific issue about this soon. Thanks for your help
