### ISSUE TITLE
Migrate stream to use expected_version :auto

### ISSUE THREAD

**Issue by casiodk** [RailsEventStore/rails_event_store#672]
Hi is there any way to migrate an existing event stream to start using `expected_version :auto `

I am getting this error when I try on existing streams

RubyEventStore::WrongExpectedEventVersion

**Comment by brentsnook** [comment]
This can happen when you have a mix of records in a stream of null and non-null positions. The repository counts the events when determining the next position to insert at, null positions throw things out.

We've fixed this before by rewriting the positions using the AR classes:

```ruby
stream = 'mystream$123'
event_in_stream = RailsEventStoreActiveRecord::EventInStream
event_in_stream.where(stream: stream).update_all(position: nil)
updates = event_in_stream.where(stream: stream).order(:created_at).each_with_index.each_with_object({}) do |(record, position), hash|
  hash[record.id] = { position: position }
end
event_in_stream.update(updates.keys, updates.values)
```

**Comment by pawelpacana** [comment]
Maybe a related idea: https://github.com/RailsEventStore/ideas/issues/2
