### ISSUE TITLE
Uninitialized constant when setting up subscriber in initializer

### ISSUE THREAD

**Issue by castlese** [RailsEventStore/rails_event_store#677]
I am setting up RES and subscribers

`config/initializers/rails_event_store.rb:`
```
require 'rails_event_store'
require 'aggregate_root'

Rails.configuration.to_prepare do
  # registering default event store
  Rails.configuration.event_store = RailsEventStore::Client.new
  AggregateRoot.configure do |config|
    config.default_event_store = Rails.configuration.event_store
  end

  # subscribe to events
  Rails.configuration.event_store.tap do |store|
    store.subscribe(MyModule::Notifier::Opened, to: [MyModule::Opened])
  end
end
```
My lib directory looks like this:
- lib
  - mymodule
    - notifier
      - opened.rb
    - opened.rb

I am getting the following error on `rails s` etc:
`uninitialized constant MyModule::Opened` at the line where the subscriber is being registered in the initializer. 

I think it has to do with `to_prepare` happening before eager_loading of lib paths...

Any tips on how to set up this configuration?

**Comment by pawelpacana** [comment]
> I think it has to do with to_prepare happening before eager_loading of lib paths

I don't think that was a problem in sample app. Here's the corresponding config:
https://github.com/RailsEventStore/cqrs-es-sample-with-res/blob/master/config/initializers/rails_event_store.rb and eager loaded paths: https://github.com/RailsEventStore/cqrs-es-sample-with-res/blob/master/config/application.rb#L19-L20

 Do you have a sample code somewhere where this can be reproduced?

**Comment by pawelpacana** [comment]
Btw. autoload requires certain path for the module resolution to work: `MyModule::Opened` would need to be in `lib/mymodule/opened.rb` for it to work without issues:

Please refer to https://guides.rubyonrails.org/v5.2/autoloading_and_reloading_constants.html
