### ISSUE TITLE
undefined method `on_methods' when using AggregateRoot with custom apply strategy

### ISSUE THREAD

**Issue by jakubkosinski** [RailsEventStore/rails_event_store#678]
When you use `include AggregateRoot.with_strategy(strategy)` you're getting 
```
undefined method `on_methods'
```
when applying facts because `OnDSL` module is not included - it's included only when you're using default strategy (with `include AggregateRoot`).

It turned out that for custom strategy we're extending a module with `Constructor` module while with default strategy there's `extend OnDSL`.

**Comment by pawelpacana** [comment]
My doubt is: do we really want `OnDSL` for custom strategies? That is a fine default but once you diverge from default, I have a feeling you don't need that `on` handlers because you have your own event->method dispatch.
