### ISSUE TITLE
Speed up projections by only fetching projected events

### ISSUE THREAD

**Issue by brentsnook** [RailsEventStore/rails_event_store#681]
We noticed that running a projection from all streams was prohibitively slow and we were going to hand-roll our own projections then filter on event type.

After playing around I found that we could use the existing ruby event store projection with a small change:

```ruby
class FilteredProjection < RubyEventStore::Projection
  def read_scope(event_store, stream, count, start)
    super(event_store, stream, count, start).of_type(*handlers.keys.uniq)
  end
end
```

The `when` methods registering handlers for the projection should tell you exactly which events to pull out.

The above isn't ideal because we are overriding methods that aren't part of the public interface. I can submit a PR when I get a chance later.

**Comment by pawelpacana** [comment]
Related to #569
