### ISSUE TITLE
Do I need to check correlation when temporarly subsciring to event?

### ISSUE THREAD

**Issue by kinnrot** [RailsEventStore/rails_event_store#685]
Consider the following psudo - 

within(Commands::GenerateSomthing.new()).on(
      Events::Created
    ) do |event|
      redirect_to ...
    end.run

the Commands::GenerateSomthing.new() will publish  Events::Created

If Events::Created is fired from another code or something that happens in the system, I'll get it twice ?

Do I need to compare correlation ?

thanks,

**Comment by paneq** [comment]
@kinnrot - you don't have to. this code is thread safe and you only get notifications about events happening in the thread in which you subscribed:

* https://github.com/RailsEventStore/rails_event_store/blob/3963b5d077ee856325c44ba4f3f7498df097b784/ruby_event_store/lib/ruby_event_store/client.rb#L126L205
* https://github.com/RailsEventStore/rails_event_store/blob/8426ee9c301bea01d3bf17dcb9ab6327d057a0c6/ruby_event_store/lib/ruby_event_store/subscriptions.rb#L78L93

If you want to help with the documentation to clarify it, you can update this page: https://github.com/RailsEventStore/rails_event_store/blob/master/railseventstore.org/source/docs/subscribe.html.md
