### ISSUE TITLE
type vs event_type

### ISSUE THREAD

**Issue by sfcgeorge** [RailsEventStore/rails_event_store#688]
[In Event](https://github.com/RailsEventStore/rails_event_store/blob/5ab4ebb37f753bd99d8a9bffbd1703f665d1e425/ruby_event_store/lib/ruby_event_store/event.rb#L42) the `to_h` has a `type` key but [in SerializedRecord](https://github.com/RailsEventStore/rails_event_store/blob/5ab4ebb37f753bd99d8a9bffbd1703f665d1e425/ruby_event_store/lib/ruby_event_store/serialized_record.rb#L36) the `to_h` has an `event_type` key. This caused me issues when manually scheduling an async handler with an Event VS having an async handler scheduled automatically with a SerializedRecord.

This is roughly what I was doing which isn't compatible with `RailsEventStore::AsyncHandler` which expects `event_type`:

```ruby
Handler.new.perform_at(event.to_h, 1.day.from_now)
```

I ended up just never scheduling async handlers manually like that, which arguably hides the abstraction better. Nonetheless this asymmetry seems undesirable. `event_type` is used pretty much everywhere except in Event. Perhaps it could be changed to `event_type` and an alias added for `type`.

**Comment by pawelpacana** [comment]
> Perhaps it could be changed to event_type and an alias added for type.

I don't like the assymetry as well and I recall some past discussions about it. I have to remind myself  what are the possible consequences though.

**Comment by pawelpacana** [comment]
From the past:
- https://github.com/RailsEventStore/rails_event_store/commit/77519869707c4e2efba2fe0fdf5484b79c25ef57

**Comment by pawelpacana** [comment]
Work towards bringing the symmetry: https://github.com/RailsEventStore/rails_event_store/pull/724
