### ISSUE TITLE
Test on Ruby 2.7

### ISSUE THREAD

**Issue by pawelpacana** [RailsEventStore/rails_event_store#696]
We need to add newest Ruby version to our testing matrix

**Comment by pawelpacana** [comment]
That actually includes pushing new image to https://hub.docker.com/repository/docker/railseventstore/ruby

**Comment by pawelpacana** [comment]
Our source dockerfiles for builds are in `support/docker`. 

1. Copy and adjust `Dockerfile.2_6` -> `Dockerfile.2_7`
2. Build and push an image to `railseventstore` organization

**Comment by fidel** [comment]
For the record:
```
- cp Dockerfile.2_6 Dockerfile.2_7
- adjust content, just like in this commit
- docker build -t ruby:2.7 -f Dockerfile.2_7 .
- docker tag ruby:2.7 railseventstore/ruby:2.7
- docker login
- docker push railseventstore/ruby:2.7
```
