### ISSUE TITLE
Segmentation fault on concurrent-ruby 1.1.5

### ISSUE THREAD

**Issue by leandronsp** [RailsEventStore/rails_event_store#698]
Hi, 

I've faced some segmentation fault errors every time a process is finished. This is happening for both Ruby 2.5 and 2.6 as for my initial tests. 

After some debugging and research, I discovered that the `concurrent-ruby` gem [has an issue already in place](https://github.com/ruby-concurrency/concurrent-ruby/issues/808), which they came up with a fix at [this commit](https://github.com/ruby-concurrency/concurrent-ruby/commit/97fa0fb44e3d91d097333ed904b87395e39c04e0).

I pointed `concurrent-ruby` to master and **it did the trick for me**. Waiting for them to publish the new release.

**Comment by pawelpacana** [comment]
Hey, thanks for the notice! We'd probably bump the version of `concurrent-ruby` dependency to `>= 1.1.6` once it is released.

Do you perhaps know on which `concurrent-ruby` version that started being a problem?

**Comment by leandronsp** [comment]
Hi @pawelpacana, I'm not sure in which version the bug was introduced, but it's somewhere in [this file](https://github.com/ruby-concurrency/concurrent-ruby/blame/97fa0fb44e3d91d097333ed904b87395e39c04e0/lib/concurrent/atomic/ruby_thread_local_var.rb)

**Comment by pawelpacana** [comment]
Gem version bumped, new RES version to be released soon. Thank you once again for making us aware of the issue 🖤
