### ISSUE TITLE
Mutate on Ruby 2.7

### ISSUE THREAD

**Issue by fidel** [RailsEventStore/rails_event_store#701]
While doing #696 we experienced mutation test failing on Ruby 2.7 and decided to mutate code on Ruby 2.6 so far.

Problem occurs because of unparser gem (mutant gem dependency) not supporting Ruby 2.7 AST yet, as mentioned in: https://github.com/mbj/unparser/issues/129

As soon as unparser gem will support 2.7, mutations can be switched to run on 2.7 too.

**Comment by pawelpacana** [comment]
What is the status here after revert?

**Comment by fidel** [comment]
Status is that we don't mutate on 2.7. 

Despite mutant using parser for Ruby 2.7 series, and no use of 2.7 features in our codebase, the failures look the same as before bumping mutant to 0.9.5 and using Ruby 2.7. Strange mutations appear, integration errors happen:

```
Killing the mutation resulted in an integration error.
This is the case when the tests selected for the current mutation
did not produce a test result, but instead an exception was raised.

This may point to the following problems:
* Bug in mutant
* Bug in the ruby interpreter
* Bug in your test suite
* Bug in your test suite under concurrency
```

Any ideas how to push this forward?

**Comment by pawelpacana** [comment]
btw. we'd need protobuf gems on 2.7 for mutation testing

**Comment by fidel** [comment]
Yeah. Figured it out yesterday, but my battery died and I forgot to make a note on that.

**Comment by mbj** [comment]
> Any ideas how to push this forward?

The canonical way to debug these is to manually mutate in the affected mutations and run rspec by hand without mutant. And than learn from the feedback.

If you gave me a command line that reproduces I can have a look.

**Comment by mbj** [comment]
@pawelpacana, @fidel Latest mutant works fine on 2.7, but only if you do not use 2.7 specific syntax (Which I doubt you do as you release with 2.6 and lower compatibility).

See mutants [support matrix](https://github.com/mbj/mutant#ruby-versions).
