### ISSUE TITLE
Utilise Ruby 2.7 deprecation warnings

### ISSUE THREAD

**Issue by fidel** [RailsEventStore/rails_event_store#702]
As a followup to #696 we should deal with Ruby 2.7 deprecation warnings. Most common issue is:
`Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call`.

Fairly easy to fix, I suppose.

**Comment by pawelpacana** [comment]
Is there a rubocop autofix for that?

**Comment by dneilroth** [comment]
@fidel spun up a PR here https://github.com/RailsEventStore/rails_event_store/pull/735

**Comment by mpraglowski** [comment]
Some deprecation warning still exists in gem we have in dependencies.
