### ISSUE TITLE
NoMethodError: private method `load' called

### ISSUE THREAD

**Issue by alexandrule** [RailsEventStore/rails_event_store#713]
I'm facing a problem with the method ```load```
I suppose the problem is with autoloading in Rails and calling private method ```load``` from ```ActiveSupport::Dependencies```
Can I find a workaround for solving this problem or I missed something in configuration?

```
gem 'rails', '~> 4.2.3'
gem 'rails_event_store', '~> 0.42.0'
```

```ruby
module Domain
  class Deal
    include AggregateRoot
  end
end
```
```ruby
Domain::Deal.new.load(stream)
```
```
NoMethodError: private method `load' called for #<Domain::Deal:0x007f94d144bde0>
```

```
Domain::Deal.ancestors
=> [
    [ 0] Domain::Deal < Object,
    [ 1] AggregateRoot::AggregateMethods,
    [ 2] #<Module:0x007f91ad57c790>,
    [ 3] #<Module:0x007f91ad57c920>,
    [ 4] AggregateRoot,
    [ 5] Object < BasicObject,
    [ 6] Commands::Execute,
    [ 7] Rake::DSL,
    [ 8] Rake::FileUtilsExt,
    [ 9] FileUtils,
    [10] FileUtils::StreamUtils_,
    [11] PP::ObjectMixin,
    [12] ActiveSupport::Dependencies::Loadable,
    [13] V8::Conversion::Object,
    [14] JSON::Ext::Generator::GeneratorMethods::Object,
    [15] Kernel,
    [16] BasicObject
]
```

**Comment by mpraglowski** [comment]
The `load` & `store` method on AggregateRoot have been deprecated i 0.37.0 version and later removed in `0.40.0` version of RES. (see commit https://github.com/RailsEventStore/rails_event_store/commit/1ea7d2ff7e74bbb29e9092e1d3325c06b5149ff6 )

To load the aggregate now you need to:

```
repository = AggregateRoot::Repository.new
deal = repository.load(Domain::Deal.new, stream)
```

Please check the https://railseventstore.org/docs/app/ for more information. The `Simplify loading/storing aggregates` section might be also interesting for you as the repository will handle loading & storing events for you.

**Comment by alexandrule** [comment]
@mpraglowski Thanks! I will check it out.

I think need to update README file [https://github.com/RailsEventStore/rails_event_store/blob/master/aggregate_root/README.md](url)
