### ISSUE TITLE
Pulling sinatra as a dependency

### ISSUE THREAD

**Issue by MicMicMon** [RailsEventStore/rails_event_store#715]
When installing just the `rails_event_store` gem, it pulls some dependencies - as should be - but also full Sinatra.

Is it really needed? As far as I can tell (didn't start using the gem yet), it's just for the browser in dev-mode. Shouldn't it be a development dependency only?

[This line](https://github.com/RailsEventStore/rails_event_store/blob/2114813fbb887ee49b18a1403a05b47a0e385861/ruby_event_store-browser/ruby_event_store-browser.gemspec#L25) sets it as a full dependency.

I'm a bit relunctant to pull that dependency into my Rails API-only app.

**Comment by fidel** [comment]
Hi!

Thanks for your input. 

> it's just for the browser in dev-mode.

Not really, it's meant to be used in production too: 
https://railseventstore.org/docs/browser/#usage-in-production

I understand that it might be odd to have it in API-only app. However it's not a development dependency, but fully usable part of RailsEventStore.

rails_event_store is meant to be a complete package with all the features. Nevertheless, you can cherry-pick only the parts which are interesting to you:

https://railseventstore.org/docs/api/

Good starting point would probably be ruby_even_store with ruby_event_store_active_record repository.

Anyway, rails_event_store itself composes everything and exposes all the blocks as a Client, which is easy to use.

All the features used from Sinatra are probably replaceable with Rack code. Maybe you would want to contribute? 

Sidenote: maybe it's a good idea to extract rails_event_store-core from rails_event_store and made it a wrapper for core, browser and future stuff.

**Comment by MicMicMon** [comment]
Hi,
Thanks for your detailed answer.
Ok I understand, makes perfect sense.

Unfortunately, I'm not familiar enough with Rack & stuff to contribute at this level :(

I've not been investigating further actually, I went with the `dry-events` gem which fits my needs better because of my situation (would like to move out of Rails in the medium term).

Thanks!

Do you want me to leave this open or we close it?

**Comment by fidel** [comment]
No problem.

>  would like to move out of Rails in the medium term)

That's why we provide ruby_event_store gem which is Rails-free

> I went with the dry-events gem which fits my needs better

Speaking of pub-sub only: https://railseventstore.org/docs/pubsub/
The example shows use of `RailsEventStore` but one can be swapped with `RubyEvenStore`
