### ISSUE TITLE
Does rails_event_store support Redis or RabbitMQ as message broker instead of database?

### ISSUE THREAD

**Issue by knd** [RailsEventStore/rails_event_store#718]
I'm not sure because I couldn't find the documentation where it talks about this. 

The reason is we may use Redis/RabbitMQ as message broker in the future for microservices and it may be good to use it now with Rails Even Store, instead of database with Rails Event Store. 

Any thoughts is appreciated.

**Comment by paneq** [comment]
What you are looking for is a different `dispatcher` in RES codebase:

https://github.com/RailsEventStore/rails_event_store/blob/87b13101ed22bb8acd0c1b7cece520088cbb4e00/rails_event_store/lib/rails_event_store/client.rb#L10-L12

Saving in DB is handled in the `repository`: https://github.com/RailsEventStore/rails_event_store/blob/87b13101ed22bb8acd0c1b7cece520088cbb4e00/rails_event_store/lib/rails_event_store/client.rb#L7

You could substitute these with different implementations. Repository which does nothing, dispatcher which sends to a message queue.

**Comment by knd** [comment]
thanks!
