### ISSUE TITLE
Generating new application fails

### ISSUE THREAD

**Issue by paskudnyprogramista** [RailsEventStore/rails_event_store#739]
I came across an issue when I was generating new application:

```bash
       rails  webpacker:install
rails aborted!
NameError: uninitialized constant URI::Generic
/Code/rails/orange_orenburg/config/application.rb:3:in `<top (required)>'
/Code/rails/orange_orenburg/Rakefile:4:in `<top (required)>'
/Code/rails/orange_orenburg/bin/rails:9:in `<top (required)>'
/Code/rails/orange_orenburg/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'

Caused by:
NameError: uninitialized constant URI::Generic
/Code/rails/orange_orenburg/config/application.rb:3:in `<top (required)>'
/Code/rails/orange_orenburg/Rakefile:4:in `<top (required)>'
/Code/rails/orange_orenburg/bin/rails:9:in `<top (required)>'
/Code/rails/orange_orenburg/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
(See full trace by running task with --trace)
```

*EDIT*

@mpraglowski , @fidel I've used following command:

```bash
rails new -m https://railseventstore.org/new orange_orenburg
```

```bash
> ruby -v
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin19]
```

```bash
> rails -v
Rails 6.0.3.1
```

**Comment by mpraglowski** [comment]
Hi, thanks for reporting this. Could you post here exact command you have used to generate your application and Rails version you are using?

**Comment by fidel** [comment]
Ruby version would be helpful too.

**Comment by paskudnyprogramista** [comment]
Sorry, I've updated description :)

Moreover, I've found that when I:
- changed Ruby version inside my project from `2.5.0` to `2.7.0`
- run webpacker installer
- adding `RailsEventStore::Browser` to `routes.rb`

It started to work.

Apparently, my initial issue maybe related to Ruby version.

**Comment by fidel** [comment]
It's a Ruby bug, not existing in most recent 2.5 version, so I'm closing the issue.
Running command on 2.5.7 works without issues.
```
✨  Done in 8.81s.
Webpacker successfully installed 🎉 🍰
```

More to read: https://github.com/rails/rails/issues/38649
