### ISSUE TITLE
Merge all repos into one

### ISSUE THREAD

**Issue by mlomnicki** [RailsEventStore/rails_event_store#74]
Problem:

RES is made up of 5 repos
* ruby_event_store
* rails_event_store
* rails_event_store_active_record
* aggregate_root
* railseventstore.org (website/docs)

Pros:
* clean separation. You can use ruby_event_store without rails_event_store and its dependencies
* faster tests. You can test aggregate_root without running tests for rails_event_store_active_record
* 5 repos look and feel more fancy than one. The project looks more enterprisey

Cons:
* the code is hard to navigate and understand. You have to jump between multiple repos and gems
* if you make a change you don't know how it affects other components/gems. Unless you create a metarepo you can't run tests for all components at once
* bigger changes that touch multiple components must be split into very small commits, one per repo. You can't easily see the correlation between changes.
* Commits in separate repos force you to open separate pull requests. This makes code review a pain
* People are less likely to contribute because the code isn't straightforward to navigate and understand

Solution:

Maybe it makes sense to split the code into gems but separate repos are pain in the ass. How about we adapt the same approach as Rails and put all the gems into one repo? https://github.com/rails/rails

Thoughts?

**Comment by paneq** [comment]
I generally agree that 

* one repo
* multiple gems
* simultaneous releases (don't support new RailsEventStore but older RubyEventStore, or mixing RES and AggregateRoot)

could be very beneficial and easier to mantain.

**Comment by pawelpacana** [comment]
Changes across repos would be easier. Also releasing many gems at once for related change.

How do you see the migration to preserve existing commit history?

**Comment by mlomnicki** [comment]
> How do you see the migration to preserve existing commit history?

great point. It's a challenge and I don't know the answer...

**Comment by pawelpacana** [comment]
I guess it might involve https://git-scm.com/docs/git-filter-branch

**Comment by pawelpacana** [comment]
I've created https://github.com/RailsEventStore/res for this experiment, let's see how it can look/work

**Comment by pawelpacana** [comment]
I've used `git subtree add --prefix ruby_event_store https://github.com/RailsEventStore/ruby_event_store.git master` so far. Have a look on results, it seems that history and original commit ids are preserved.

**Comment by mlomnicki** [comment]
LGTM! :clap:

**Comment by pawelpacana** [comment]
Not to so fast, how would CI and tests work in a scenario where all lands in one repo?

**Comment by mpraglowski** [comment]
Even better - now we could have some changes in RubyEventStore that might cause issues in RESActiveRecord or AggregateRoot - of course we need to change how tests will be executed.

**Comment by mlomnicki** [comment]
> how would CI and tests work in a scenario where all lands in one repo

https://docs.travis-ci.com/user/speeding-up-the-build/#Parallelizing-your-builds-across-virtual-machines

We don't need parallel builds so the title of this article is a bit misleading but we can still utilize the matrix feature.

> For instance, the Rails project uses the build matrix feature [...] One set runs tests only for the railties, another one for actionpack, actionmailer, activesupport, and a whole bunch of sets runs the activerecord tests against multiple databases. See their .travis.yml file for more examples.

> now we could have some changes in RubyEventStore that might cause issues in RESActiveRecord or AggregateRoot 

Yep, it is a perfect example of why are doing this. If a change to RubyES breaks RailsES then you want the CI to catch it as soon as possible

**Comment by paneq** [comment]
> Not to so fast, how would CI and tests work in a scenario where all lands in one repo?

What's the problem? All tests from all repos are executed and that's it. Makes sense?

**Comment by mpraglowski** [comment]
Just another doubts here: how to define gems dependencies to avoid releasing gem with dependency before I could run tests in `rails_event_store` to validate changes made in `ruby_event_store` ?

**Comment by mlomnicki** [comment]
@mpraglowski good point. See https://github.com/RailsEventStore/res/pull/1 In particular the "dev" mode

**Comment by pawelpacana** [comment]
Next thing I've noticed: the way we do releases involves tagging particular commit SHA with version of the release. That worked for individual repo per gem so far. It might be problematic to retain when all gems live in one repo - what Rails does is common version for all gems and releasing them together (even when some of them have no changes).

**Comment by pawelpacana** [comment]
Regarding join strategy for repositories, there are pros and cons. Below strategies I've considered:

### subtree merge
- showcased in https://github.com/RailsEventStore/res-subtree
- original commit SHA retained (refering to SHA from commit messages and refering to existing tags should work)  
- on a graph it is several roots going into one HEAD
- breaks file history as the paths after merge are different and it shows only the merge commit 

### filter-branch and pull --allow-unrelated-histories
- showcased in https://github.com/RailsEventStore/res-filter
- commit SHA changed as this is modifying history 
- on a graph it is several roots going into one HEAD
- file history works as paths are rewritten in commits

### mv and pull --allow-unrelated-histories
- showcased in https://github.com/RailsEventStore/res-mv
- original commit SHA retained (refering to SHA from commit messages and refering to existing tags should work)  
- on a graph it is several roots going into one HEAD
- file history works (with --follow flag that tracks renames)

Whatever we decide I'd opt for https://github.com/RailsEventStore/rails_event_store as a destination repository where other joined repositories land (as it's the most popular one).

**Comment by pawelpacana** [comment]
My choice would be `mv and pull --allow-unrelated-histories` - least odd, history preserved. Opinion @mlomnicki @paneq @mpraglowski @fmwr?

**Comment by paneq** [comment]
I prioritize file history much more than original commit SHAs being retained.

As viewing history on github seems not to use the `--follow` flag I am more inclined towards

* `filter-branch and pull --allow-unrelated-histories`
* over `mv and pull --allow-unrelated-histories`
* `subtree merge` sounds worst for me.

Very good research into our options!

**Comment by mpraglowski** [comment]
Agree with @paneq 
Browsable history on Github is a big + for me for `filter-branch and pull --allow-unrelated-histories`

**Comment by pawelpacana** [comment]
Merge has been forced-pushed to `master` branch. This effectively close pending pull requests which need some love after such radical history change. I'll repoen them when appropriate.

Let's focus now on follow-up to this merge:
- [ ] transitioning CI to work for monorepo
- [ ] releasing v0.15.0 for all gems as if #75 happened (no changes beyond numbering scheme)
- [ ] documenting "Why we follow the Rails repo structure with RailsEventStore" as a blogpost and clarification what happened and why

**Comment by pawelpacana** [comment]
Also worth checking if still valid - tags from past releases.

**Comment by mlomnicki** [comment]
Overall, everything looks good to me. Just found one very minor issue though.
Github says [this PR](https://github.com/RailsEventStore/rails_event_store/pull/73) includes 250+ commits and that 19 devs contributed. :smile: 

Other PRs looks correct

**Comment by pawelpacana** [comment]
> Github says this PR includes 250+ commits 

This PR was not rebased on new, rewritten tree yet.

> and that 19 devs contributed. 😄

Same for `master` branch. Yesterday it was 18, correctly. Right after the merge it was 16 though (original number of just rails_event_store gem contributors). I assume this is some kind of cache that will eventually show correct number.

**Comment by mlomnicki** [comment]
> This PR was not rebased on new, rewritten tree yet.

Thanks for explaining. Not a big deal. I think we can leave it as it is

**Comment by pawelpacana** [comment]
Thanks for helping in this transtion! A quick summary for the future: http://blog.arkency.com/why-we-follow-rails-repo-structure-in-rails-event-store/
