### ISSUE TITLE
New release scheme

### ISSUE THREAD

**Issue by pawelpacana** [RailsEventStore/rails_event_store#75]
Right now we have different version numbers for indiviudal gems, that is each gem has individual versioning and changelog. Currently released:
- `rails_event_store` 0.14.5
- `ruby_event_store` 0.14.0
- `rails_event_store_active_record` 0.6.13
- `aggregate_root` 0.4.0

Then there's `rails_event_store` gem that depends on the rest. Given that dependencies are defined with `~>` it is not unusual to bump its version because of the dependency change.

On the other hand there's Rails way of doing releases - each gem included in `rails` gets the same version number of Rails release, even with no changes. 
That makes it slightly easier to push related chanegs across all gems with less confusion and to prepare single changelog of what's included with each release. It might be also more convenient with monorepo (see #74) to git tag releases where each component has the same version.

Proposal: release `rails_event_store`, `ruby_event_store`, `rails_event_store_active_record` and `aggregate_root` together starting with 0.15.0 version.

**Comment by mpraglowski** [comment]
:+1:

**Comment by paneq** [comment]
> together starting with 0.15.0 version.

makes sense

**Comment by paneq** [comment]
I would even consider doing it as soon as we have a new testing environment. No need to add new features or bugfixes.

**Comment by pawelpacana** [comment]
Assuming we'll release `0.15.0` for all gems once release infrastructure is ready. Thanks for discussion!
