### ISSUE TITLE
Sending event id to Sidekiq instead of serialized event

### ISSUE THREAD

**Issue by matiasgarcia** [RailsEventStore/rails_event_store#755]
In the docs, there is some suggested code to manage async handlers on Sidekiq.

The Scheduler is as follows:

```
module RailsEventStore
  class SidekiqScheduler
    def call(klass, serialized_event)
      klass.perform_async(serialized_event.to_h)
    end

    def verify(subscriber)
      subscriber.is_a?(Class) && subscriber < Sidekiq::Worker
    end
  end
end
```

And the AsyncHandler from the library is:

```
module RailsEventStore
  module AsyncHandler
    def perform(payload)
      super(Rails.configuration.event_store.deserialize(payload.symbolize_keys))
    end
  end
end
```

This works perfectly fine but we found ourselves hitting max memory error on Redis under heavy load. This is when I realized that the Scheduler serializes the whole event.

I was wondering if it's possible to provide just the `event_id` and write a custom AsyncHandler to retrieve it.

Like this:

```
module RailsEventStore
  class SidekiqScheduler
    def call(klass, serialized_event)
      klass.perform_async(serialized_event.event_id)
    end

    def verify(subscriber)
      subscriber.is_a?(Class) && subscriber < Sidekiq::Worker
    end
  end
end
```

```
module RailsEventStore
  module AsyncHandler
    def perform(payload)
      event = RailsEventStoreActiveRecord::Event.find(payload)
      super(event)
    end
  end
end
```

Or is there any problem on doing so?

**Comment by pawelpacana** [comment]
@matiasgarcia with RailsEventStore::AfterCommitAsyncDispatcher you're fine — the dispatcher would not schedule anything before commit or after rollback

```ruby
ApplicationRecord.transaction do
   # do something
   event_store.publish(...) # not scheduling yet, as others might not see uncommitted changes from this transaction or it might be rolledback
end
# scheduling now
```

**Comment by matiasgarcia** [comment]
Thanks @pawelpacana.

I was wondering if maybe a maintained version of this AsyncHandler should be in the gem? I am saving 92% of my Redis storage with this change.

**Comment by pawelpacana** [comment]
It's an interesting tradeoff to save on redis memory in exchange for additional query on a database. I'm not sure yet what is better as a default choice in AsyncHandler.

I'd accept PR with and alternative or configurable strategy for AsyncHandler for now :+1:

**Comment by paneq** [comment]
@pawelpacana I like the idea!

I think we could change the implementation but keep the dispatcher/scheduler contract of `(event, serialized_event)` the same so that if someone wants to use the serialized version they can still do it. It's beneficial in case the consumer does not have access to RES storage.

**Comment by matiasgarcia** [comment]
> It's an interesting tradeoff to save on Redis memory in exchange for an additional query on a database. I'm not sure yet what is better as a default choice in AsyncHandler.
> 
> I'd accept PR with and alternative or configurable strategy for AsyncHandler for now

In our case, we were firing around 200k events in a short time span (10 minutes) and we have a Redis DB of 100MB storage. This made it quickly reach the maximum threshold, because in our events we were tracking changes to AR models, making the payload quite big. So in this specific use case, it paid off to just send the event id. The additional query to fetch the event should be fairly quick since they are ids, although I don't have a benchmark to guarantee this :)

**Comment by pawelpacana** [comment]
For the record and anyone looking for clear transition path:

- following handler mixin works well both with full payload and just an `event_id` 

```ruby
module EventFromEventId
  def perform(payload)
    event_id = payload.symbolize_keys.fetch(:event_id)
    super(event_store.read.event(event_id))
  end
end
```

- passing slice of the event payload containing `event_id`, for one-way compatibility

```ruby
class Scheduler
  def call(klass, serialized_event)
    klass.perform_later({ event_id: serialized_event.event_id })
  end
  def verify(subscriber)
    Class === subscriber && !!(subscriber < ActiveJob::Base)
  end
end
```
