### ISSUE TITLE
Error when decrypting event with new cipher key

### ISSUE THREAD

**Issue by casiodk** [RailsEventStore/rails_event_store#758]
Hi guys, I think I found another issue

So the use case is this - we have some events that are encrypted using a cipher key with an identifier

When we delete that cipher key from the database, similar events being encrypted after the cipher key has been deleted, will result in creating a new cipher key in our db with an identical identifier.

So when we try to decrypt the old events with the new cipher key, this happens:

```
2020-08-31 13:21:43 - Psych::SyntaxError - (<unknown>): invalid leading UTF-8 octet at line 1 column 1:
	/Users/nicolaiseerup/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/psych.rb:456:in `parse'
	/Users/nicolaiseerup/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/psych.rb:456:in `parse_stream'
	/Users/nicolaiseerup/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/psych.rb:390:in `parse'
	/Users/nicolaiseerup/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/psych.rb:277:in `load'
	/Users/nicolaiseerup/.rvm/gems/ruby-2.6.5@smart-workspaces/gems/ruby_event_store-1.1.1/lib/ruby_event_store/mappers/transformation/encryption.rb:117:in `decrypt_attribute'
```

https://github.com/RailsEventStore/rails_event_store/blob/master/ruby_event_store/lib/ruby_event_store/mappers/transformation/encryption.rb#L117

Maybe [this line](https://github.com/RailsEventStore/rails_event_store/blob/master/ruby_event_store/lib/ruby_event_store/mappers/transformation/encryption.rb#L121) should also rescue from `Psych::SyntaxError` ?

**Comment by casiodk** [comment]
I added this monkey patch in an initializer, and now everything works as expected

# frozen_string_literal: true
```
module RubyEventStore
  module Mappers
    module Transformation
      class Encryption
        def decrypt_attribute(data, attribute, meta)
          case meta
          when Leaf
            cryptogram = data.fetch(attribute)
            return unless cryptogram

            encryption_key = key_repository.key_of(meta.fetch(:identifier), cipher: meta.fetch(:cipher)) or return forgotten_data
            serializer.load(encryption_key.decrypt(cryptogram, meta.fetch(:iv)))
          when Hash
            decrypt_data(data.fetch(attribute), meta)
          end
        rescue OpenSSL::Cipher::CipherError, Psych::SyntaxError
          forgotten_data
        end
      end
    end
  end
end

```

**Comment by mpraglowski** [comment]
Could you provide a failing test case for this issue?
This https://github.com/RailsEventStore/rails_event_store/blob/master/ruby_event_store/lib/ruby_event_store/mappers/transformation/encryption.rb#L116 should return `forgotten_data` when key has been removed.
The in memory implementation of key repository does not create keys implicitly https://github.com/RailsEventStore/rails_event_store/blob/master/ruby_event_store/lib/ruby_event_store/mappers/in_memory_encryption_key_repository.rb - you need to explicte call the `create` method.

I think `rescue Psych::SyntaxError` is not the desired behaviour - could lead to nasty investigations when serializer will raise some issues.

**Comment by casiodk** [comment]
Maybe I am doing something wrong?

```
# frozen_string_literal: true

class EncryptionKeyRepository
  DEFAULT_CIPHER = "aes-256-cbc".freeze
  attr_reader :keys

  def initialize
    @keys = {}
  end

  def key_of(identifier, cipher: DEFAULT_CIPHER)
    encryption_key = keys[[identifier, cipher]] || create(identifier)

    RubyEventStore::Mappers::EncryptionKey.new(
      cipher: cipher,
      key: Base64.decode64(encryption_key)
    )
  end

  def create(identifier, cipher: DEFAULT_CIPHER)
    cipher_key = ::CipherKey.where(identifier: identifier, cipher: cipher).first_or_create(
      key: Base64.encode64(random_key(cipher))
    )

    @keys[[identifier, cipher]] = cipher_key.key
  end

  def forget(identifiers)
    identifiers = [*identifiers]
    @keys = keys.reject { |(id, _)| identifiers.include?(id) }
    ::CipherKey.where("identifier IN(?)", identifiers).destroy_all
  end

  private

  def random_key(cipher)
    crypto = OpenSSL::Cipher.new(cipher)
    crypto.encrypt
    crypto.random_key
  end
end

```

**Comment by mpraglowski** [comment]
`encryption_key = keys[[identifier, cipher]] || create(identifier)` you should not create a new key here - this should be explicit operation

**Comment by casiodk** [comment]
Where do I perform that operation? - because if I just define my encryption_schema in my event and leave `|| create(identifier)` out - my events are not being encrypted?

**Comment by casiodk** [comment]
Can you give me an example on how you are implementing .create when publishing an event?

**Comment by mpraglowski** [comment]
It depends what the `identifier` is. In most cases we encrypt personal information so the identifier is a user's id. In this case the encryption key must be created as part of new user's registration process before first domain events with his/hers personal data will be published - this does not have to be first domain event in user's registration process.

**Comment by casiodk** [comment]
I am just thinking where ever and how the cipher key is created - if its deleted and a new one with an identical identifier is created - the bug will still be there

**Comment by casiodk** [comment]
so we have a stream of properties coming in from an IoT device - and we are creating the identifier based on the date and the IoT Device ID

"SomeEventName$2020-31-08$some-iot-device-id"

That way we can regularly forget property events that are older than 1 week related to a specific iot device - but if we delete the cipher keys - and new events are coming in - an identical identifier will be created

**Comment by mpraglowski** [comment]
> if its deleted and a new one with an identical identifier is created - the bug will still be there

```
        specify '#serialized_record_to_event returns event instance with forgotten data when a new key is created' do
          record = SerializedRecord.new(
            event_id:   domain_event.event_id,
            data:       YAML.dump(encrypted_item.data),
            metadata:   YAML.dump(encrypted_item.metadata),
            event_type: SomeEventWithPersonalInfo.name
          )
          key_repository.forget(123)
          key_repository.create(123)
          event = subject.serialized_record_to_event(record)
          expected_event = SomeEventWithPersonalInfo.new(
            data: build_data.merge(personal_info: ForgottenData.new),
            metadata: metadata,
            event_id: event_id
          )
          expect(event).to                      eq(expected_event)
          expect(event.metadata.to_h).to        eq(metadata)
          expect(event.data[:personal_info]).to eq('FORGOTTEN_DATA')
        end
```

I've added that test and this works as expected - the result is forgotten data.

**Comment by casiodk** [comment]
Ok, let me try to reproduce our case somehow - please leave this issue open a bit

**Comment by casiodk** [comment]
I have looked at the issue - and it seems sometimes the key repository returns a random string when the cipher key has been replaced

```
serializer = YAML
cipher = "aes-256-cbc"

# Case 1
# Successful decrypting
iv = "\xBAC\xAFW\xCC\xC7\xEAK\xCF\x05\x18g\xB1xb\xF5"
cryptogram = "Q\x1A\xAE\x9D\x18\r\xDC\xB3\x02\xC1/W\xBDn0a\xC3\xF5$<\xCA=\xAFm\x12I\x849\xB0Fw\x1DV\xE8\x12ScX\t\xE2\x87\xA7K\xBF\xCA\xA4\xB3\xFE"
key = "\xB0K]\xB0\xE7\xFD\xF5G\xEBd\x8D\x89\xF0\xAA\x85[\xF5\xD7$\xB8\xFD\a\xE7*\xE7p\r\xB9g \xF4\xD5"
encryption_key = RubyEventStore::Mappers::EncryptionKey.new(cipher: cipher, key: key)
yaml = encryption_key.decrypt(cryptogram, iv)
# this return the expected value
# => "--- !ruby/object:BigDecimal 45:0.58765387563e0\n"
serializer.load(yaml)
# => 0.58765387563e0

# Case 2
# Successful OpenSSL::Cipher::CipherError
iv = "w7\xBA\x95\x1C\xF0M\xFA\xF6V#>\x88\x86\x89\x14"
cryptogram = "\xD8i\xD8\xAAY\xC58s\xF7\xC9\xDB\x1F\xF49\xE7;"
key = "\xA0\x95 8\xF9\x90\xABo-\xA2m\xC1\x1C\xBC\xD2\x99K\xCE}i\xE0e+\xE8\xA3\xD6V\xF4\xA7U\x03\r"
encryption_key = RubyEventStore::Mappers::EncryptionKey.new(cipher: cipher, key: key)
yaml = encryption_key.decrypt(cryptogram, iv)
# this returns the expected error
# => OpenSSL::Cipher::CipherError: bad decrypt


# Case 3
# Unexpected Psych::SyntaxError
iv = "\x9C\x91t\xD2\x99\xC3\xCAQ\x7F\xA8\xADV\xA9\xB6X\x8D"
cryptogram = "}E\x7F\xBA\xF9\t\x80@O\xC8\xC6q<4\x9B\xFBZ\xBB\xFC\xCE\x83\x16\xAAdv\xBE\a\x869l\x8C\x91"
key = "\xE8\xB5\x0E\x89\xF1\x98\xBA\xDBkI9\x05\x90\xAD\\\xFF\xB6\xE3An\x86^\xF0lI\x92\xF8b\x02*\x90\xAE"
encryption_key = RubyEventStore::Mappers::EncryptionKey.new(cipher: cipher, key: key)
yaml = encryption_key.decrypt(cryptogram, iv)
# this returns non valid yaml string
# => "{M]\xEAμ\xEA\x99\xE5\"ЮF\xE6bM)C\xA1݃\x96\xBC_\xB2\xD7DN\"\x80i"
serializer.load(yaml)
# resulting in unexpected error
# => Psych::SyntaxError: (<unknown>): invalid trailing UTF-8 octet at line 1 column 1
```

Try to look at this @mpraglowski and let me know what you think

**Comment by casiodk** [comment]
It is only sometimes this error occurs, so must be this method

```
def random_key(cipher)
    crypto = OpenSSL::Cipher.new(cipher)
    crypto.encrypt
    crypto.random_key
  end
```
that returns a key that somehow returns a random string instead of the expected open ssl error ..?

**Comment by mpraglowski** [comment]
```
require 'openssl'

cipher = "aes-256-cbc"
iv = "\x9C\x91t\xD2\x99\xC3\xCAQ\x7F\xA8\xADV\xA9\xB6X\x8D"
cryptogram = "}E\x7F\xBA\xF9\t\x80@O\xC8\xC6q<4\x9B\xFBZ\xBB\xFC\xCE\x83\x16\xAAdv\xBE\a\x869l\x8C\x91"
key = "\xE8\xB5\x0E\x89\xF1\x98\xBA\xDBkI9\x05\x90\xAD\\\xFF\xB6\xE3An\x86^\xF0lI\x92\xF8b\x02*\x90\xAE"

crypto = OpenSSL::Cipher.new(cipher)
crypto.decrypt
crypto.iv  = iv
crypto.key = key
(crypto.update(cryptogram) + crypto.final).force_encoding("UTF-8")
=> "{M]\xEAμ\xEA\x99\xE5\"ЮF\xE6bM)C\xA1݃\x96\xBC_\xB2\xD7DN\"\x80i"

# and then

require 'yaml'
YAML.load("{M]\xEAμ\xEA\x99\xE5\"ЮF\xE6bM)C\xA1݃\x96\xBC_\xB2\xD7DN\"\x80i")
=> Psych::SyntaxError ((<unknown>): invalid trailing UTF-8 octet at line 1 column 1)
```

With that set of cryptogram, iv & key you will get a `{M]\xEAμ\xEA\x99\xE5\"ЮF\xE6bM)C\xA1݃\x96\xBC_\xB2\xD7DN\"\x80i` as decrypted message, of course later when we try to parse it to as YAML it fails.

This seems like not RES related problem - I think you should verify your keys management.

**Comment by mpraglowski** [comment]
@casiodk any update here? Closing it. Please reopen if any you will find anything more related.
