### ISSUE TITLE
Add CodeClimate metrics

### ISSUE THREAD

**Issue by pawelpacana** [RailsEventStore/rails_event_store#79]
While merging repositories the source repo for metrics change as well. Before re-adding these metrics it's worth validating that we actually need them.

We already strive for 100% mutant coverage. That gives:
- better code coverage metric
- quite a pressure to refactor code to pass mutant and so far that has been great driver for quality

I've never actually looked into CC hints and I also remember that getting 4.0 score isn't hard.

Thoughts?

**Comment by mlomnicki** [comment]
agreed, let's get rid of CC

**Comment by mpraglowski** [comment]
👍

**Comment by pawelpacana** [comment]
Cool, not re-adding then.
