### ISSUE TITLE
Link an event to a stream that has the same event already

### ISSUE THREAD

**Issue by kazu9su** [RailsEventStore/rails_event_store#793]
I tried to link against a stream that already has the same event, and then got `RubyEventStore::EventDuplicatedInStream` error.

```ruby
event_store = RailsEventStore::Client.new
stream_name = "order_1"
event = OrderPlaced.new(data: {
  order_id: 1,
  order_data: "sample",
  festival_id: "b2d506fd-409d-4ec7-b02f-c6d2295c7edd"
})
#publishing an event for a specific stream
event_store.publish(event, stream_name: stream_name)
event_store.link(event.event_id, stream_name: stream_name) # => raise RubyEventStore::EventDuplicatedInStream error
```

In my opinion, when a user uses the `link` method, they don't intend to publish the event into the same stream,
so that it has benefits for users if the library automatically ignores if the link method got a stream-name that already has the same event(or raises ArgumentError, like that)
I'd appreciate it if anyone can let me know that this issue has already been discussed or what do committers feel against my opinion.

Thank you!

**Comment by pawelpacana** [comment]
Thank you for sharing your thoughts!

Just to clarify:
- `append` adds an event to global stream (and also named stream if such provided via `stream_name:`)
- `publish` does what an `append` does and also broadcasts the event to its subscribers
- `link` takes an existing event and puts it in given named stream
- an appended event is always present in global stream
- an appended event can be present in multiple named streams

> In my opinion, when a user uses the link method, they don't intend to publish the event into the same stream,

I agree it is very rare to see append/publish followed by link to the same stream. It is more common to see linking to the same stream performed twice in message queues with at-least-once delivery. 

Can you please tell me more about your usecase? Is it the documentation that can be made a bit clearer on this topic?

I'm not convinced that getting rid of the feedback from `link` is desired. In my opinion it rather hides the underlying issues (if any) rather than exposing them early.

It is perfectly fine to wrap customize `RailsEventStore::Client` to match your needs:

```ruby
class EventStoreAdapter
  extend Forwardable 

  def_delegators :@res_client,  
    :publish, 
    :append, 
    # :link, 
    :delete_stream, 
    :read, 
    :streams_of, 
    :subscribe, 
    :subscribe_to_all_events, 
    :within, 
    :with_metadata, 
    :deserialize, 
    :metadata, 
    :overwrite, 
    :inspect

  def initialize
    @res_client = RailsEventStore::Client.new(...) 
   end

  def link(*args, **kwargs)
    @res_client.link(*args, **kwargs)
  rescue RubyEventStore::EventDuplicatedInStream
  end
end

```

**Comment by kazu9su** [comment]
Thank you @pawelpacana for your illustration and understanding of my opinion!

Let me share my use case.
As a prerequisite, my current project is an E-commerce app and we develop an event-based system that is mainly related to "Order".
And, we have a job which publishes the arbitrary event asynchronously like below

```ruby
class DelayedEventPostJob < ActiveJob::Base
  def perform(event_name:, event_payload:, stream_name:)
    event = event_name.constantize.strict(event_payload)
    event_store.publish(event, stream_name: stream_name)
    order_id = event_payload[:order_id]

    if order_event?(event)
      event_store.link(event.event_id, stream_name: "Order-#{order_id}")
    end
  end
end
```

The stream named `Order-#{order_id}` is our main order stream.
This is a general job within the product, and originally designed to get `specific` stream_name except for `Order-#{order_id}` as a stream_name argument and publish an event to that stream, and then link to the main order stream.
But we had a new use case. Just want to publish the event to the main order stream.
For sure we can do that by an easy change like

```ruby
    .
    .
    .
    if order_event?(order) && stream_name != "Order-#{order_id}"
      event_store.link(event.event_id, stream_name: "Order-#{order_id}")
    end
```

However, as I proposed, when we use `link` method, if the event store ignores to link(publish) the event to the stream which has the duplicated event, we don't need to care whether the event is published on the specified stream and I felt it could be reasonable behavior of `link` method.
And I also thought it is not a very specific issue for my project so that I wanted to share and ask my thought to the community.

**Comment by mpraglowski** [comment]
> However, as I proposed, when we use link method, if the event store ignores to link(publish) the event to the stream which has the duplicated event, we don't need to care whether the event is published on the specified stream and I felt it could be reasonable behavior of link method.

I understand your use case, however I feel this behaviour of `link` method could be misleading for others.
We do not allow the same event to be stored twice in RES data store (this is enforced by a database constraint and handled by append/publish methods). The `link` method works in similar way. It does not allow the same event to be linked twice in the stream. Linking the same event several times to the stream might led to hard to investigate issues. Also this is not viable solution in my opinion - you could not have the same fact happened several times.

BTW I would model your solution a little differently. 

```ruby
class DelayedEventPostJob < ActiveJob::Base
  def perform(event_name:, event_payload:, stream_name:)
    event = event_name.constantize.strict(event_payload)
    event_store.publish(event, stream_name: stream_name)
  end
end
```

and then have separate handler:

```ruby
class LinkToOrder
  def initialize(event_store = Rails.configuration.event_store)
    @event_store = event_store
  end
  
  def call(event)
    order_id = event.data[:order_id]
    @event_store.link(event.event_id, stream_name: "Order-#{order_id}")
  end
end
```

with an explicit list of domain events that should be linked to order's stream:

```ruby
  event_store = Rails.configuration.event_store
  event_store.subscribe(LinkToOrder.new(event_store), to: [... here a list of domain events...])
```
