### ISSUE TITLE
Sidekiq workers support

### ISSUE THREAD

**Issue by kirylpl** [RailsEventStore/rails_event_store#817]
Any plans to support plain sidekiq workers without ActiveJob ? :)

**Comment by pawelpacana** [comment]
Sidekiq is already supported and used in some RES in projects that I know of.

What you're looking for is replacing a scheduler. For `v1.1.1` that could look like this:

```ruby
class SidekiqScheduler
  def call(klass, serialized_event)
    klass.perform_async(serialized_event.to_h)
  end

  def verify(subscriber)
    subscriber.is_a?(Class) && subscriber < Sidekiq::Worker
  end
end

event_store = RailsEventStore::Client.new(
  dispatcher: RubyEventStore::ComposedDispatcher.new(
                     RubyEventStore::ImmediateAsyncDispatcher.new(scheduler: SidekiqScheduler.new),
                     RubyEventStore::Dispatcher.new
  )
)
```

That would be a great contribution for someone willing to do so. Given it isn't a rails dependency, a separate gem would be ideal — similar to `rails_event_store-rspec`, which adds `rspec` interoperability to RES.
