### ISSUE TITLE
Documenting changes for each release

### ISSUE THREAD

**Issue by pawelpacana** [RailsEventStore/rails_event_store#82]
So far we've used `CHANGELOG.md` in each gem to document changes. We also seem to track documentation changes separately in http://railseventstore.org/docs/changelog/.

From an end-user perspective I'm not that interested in looking for what were the changes in dependencies of `rails_event_store`, I'd expect to have single place to figure out what changed once I update the top-level `rails_event_store` gem. 

Yet some gems make sense to be used on it's own (`ruby_event_store`, `aggregate_root`). So per-gem changelogs are not bad after all.

Last but not least - github offers a feature to document release changes. See how https://github.com/webpack/webpack/releases is structured. The advantage of having release descriptions outside of published code atrifact (pushed gem) has an advantage of ability to fix it post-release.

What are your thoughts on changelogs?

**Comment by mlomnicki** [comment]
> I'd expect to have single place to figure out what changed once I update the top-level rails_event_store gem.

+1 I don't like it in Rails that you have to browse activerecord, actionpack, activesupport, etc separately to find out what has changed

**Comment by paneq** [comment]
>'d expect to have single place to figure out what changed once I update the top-level rails_event_store gem.

+1 from me as well.

We can always group the changes per repository under given release.

**Comment by pawelpacana** [comment]
My proposal:

1. Prepare changelogs on github releases page like this:

<img width="971" alt="zrzut ekranu 2017-08-30 o 12 57 45" src="https://user-images.githubusercontent.com/116740/29869350-e54f17ec-8d82-11e7-85ef-fd8e8db6c73f.png">

2. Clarify in individual `CHANGELOG.md` files that we no longer update them and new release changes can be found at https://github.com/RailsEventStore/rails_event_store/releases

**Comment by mlomnicki** [comment]
Nice one. Let's release 0.15.0 :boom:

**Comment by pawelpacana** [comment]
Follow-up in #92
