### ISSUE TITLE
Run mutant on one Ruby version only

### ISSUE THREAD

**Issue by pawelpacana** [RailsEventStore/rails_event_store#83]
Testing with mutant takes time (a lot of it). Yet mutating on each Ruby version in matrix doesn't uncover new facts about missing code coverage. Unit tests should be enough to verify that functionality works on given Ruby verison.

Proposal: run `make mutate` on latest Ruby only

**Comment by paneq** [comment]
I will work on this as I need it anyway for making `locking_friendly` pass.

**Comment by mlomnicki** [comment]
I already started working on this here https://github.com/mlomnicki/rails_event_store/blob/20d0e2e6db0949a1025d58be6340a73b1ceb126d/.travis.yml

Feel free to use this config if you find it valuable
