### ISSUE TITLE
Phase out ROM event repository to contrib

### ISSUE THREAD

**Issue by pawelpacana** [RailsEventStore/rails_event_store#834]
Splitting work across two quite similar event repositories is time consuming and takes a lot of effort. It would have been easier with a contributor well-invested in ROM ecosystem.

Short list of things missing in ROM on upcoming v2.0.0 release:
* there is new indexed `valid_at` column for bi-temporal event sourcing, changes querying and sorting a bit and requires migration
* we're dropping global stream entries in `event_store_events_in_streams`, this again requires migration
* we're making more use of `created_at` columns which uncovered some bugs — wrong time being passed to sequel (utc vs local) and `update_messages` messing with `created_at`
* we're increasing timestamp precision, which again requires migration on mysql/sqlite
* we're adding time filtering on `created_at`, which changes querying a bit again

Mutation coverage is something to improve as well.

Looking forward to bring it back anytime, at the moment and without a maintainer it grabs too much attention.

**Comment by joelvh** [comment]
hi @pawelpacana, sorry I haven't had the bandwidth to get things caught up yet! If this gets moved to contrib, how can parity be maintained with the AR version?

**Comment by pawelpacana** [comment]
> If this gets moved to contrib, how can parity be maintained with the AR version?

Gems moved to contrib are out of RES release cycle, so naturally that would incur setting different version dependencies in gemspecs. Releases of contrib gems happen independently of RES.

They're still in the repo with all benefits of testing against master version.

This change is more about ROM catching up with RES when there's capacity to do instead of inhibiting all releases
