### ISSUE TITLE
Issue created a new rails application following the doc instruction

### ISSUE THREAD

**Issue by freiden** [RailsEventStore/rails_event_store#839]
Hi,

I wanted to the follow the documentation to build a new rails project using RES and I had the bad surprise to see the init of the project stuck on the first command to execute: `rails new -m https://railseventstore.org/new YOUR-APP-NAME`. I was trying to create a project named `train-res` and the process was stuck at the init of RES after those lines
```
 initializer  rails_event_store.rb
    generate  rails_event_store_active_record:migration
       rails  generate rails_event_store_active_record:migration
```

I tried naming my new project`train_res` and the setup worked.
At first it seemed like the issue was coming from the `-` I used in the name so before creating this issue I tested to create a project name `training-res` and it worked.

I don't know where the issue is coming from but I wanted to report it, maybe some others users will meet the same problem by using an other naming.

**Comment by pawelpacana** [comment]
For completeness, here are the steps after:

```
 initializer  rails_event_store.rb
    generate  rails_event_store_active_record:migration
       rails  generate rails_event_store_active_record:migration 
Running via Spring preloader in process 98220
      create  db/migrate/20201123095434_create_event_store_events.rb
       rails  db:migrate
== 20201123095434 CreateEventStoreEvents: migrating ===========================
-- create_table(:event_store_events_in_streams, {:force=>false, :id=>:integer})
   -> 0.0017s
-- add_index(:event_store_events_in_streams, [:stream, :position], {:unique=>true})
   -> 0.0008s
-- add_index(:event_store_events_in_streams, [:created_at])
   -> 0.0009s
-- add_index(:event_store_events_in_streams, [:stream, :event_id], {:unique=>true})
   -> 0.0010s
-- create_table(:event_store_events, {:id=>false, :force=>false})
   -> 0.0007s
-- add_index(:event_store_events, :created_at)
   -> 0.0007s
-- add_index(:event_store_events, :event_type)
   -> 0.0008s
== 20201123095434 CreateEventStoreEvents: migrated (0.0068s) ==================

       route  mount RailsEventStore::Browser => '/res' if Rails.env.development?
```

Perhaps it was Spring preloader that contributed to this. I would advise to skip Spring next time such issues arise.

**Comment by freiden** [comment]
@pawelpacana `spring` is disabled on my computer by default.

**Comment by pawelpacana** [comment]
@freiden did you have anything else configured that diverges from `rails new` defaults besides `spring`?

**Comment by freiden** [comment]
Nothing else.

**Comment by pawelpacana** [comment]
I've managed to recreate this situation with following steps:
https://twitter.com/pawelpacana/status/1347875144316952576

Specifically this involved `spring` with following cmdline:

```
rails new -m URL_TO_APP_TEMPLATE train-res
rm -rf train-res
rails new -m URL_TO_APP_TEMPLATE train-res
```

I can see spring server running from first `rails new`
```
26717 s000  S      0:00.61 spring server | train-res | started 7 mins ago   
```

Also the migration process is hanging:
```
27513 s000  S      0:01.18 /Users/pawelpacana/.rubies/ruby-2.7.2/bin/ruby bin/rails generate rails_event_store_active_record:migration
```
