### ISSUE TITLE
How can I check that my handler subscribed to an event?

### ISSUE THREAD

**Issue by StanisLove** [RailsEventStore/rails_event_store#842]
I can access current subscriptions, but it's a pretty ugly approach
```ruby
event_store
  .send(:broker)
  .instance_variable_get(:@subscriptions)
  .send(:local)
  .instance_variable_get(:@subscriptions)
```
Do we need a public interface to get current subscriptions or a method to be sure that a handler subscribed to an event?

**Comment by pawelpacana** [comment]
> Do we need a public interface to get current subscriptions or a method to be sure that a handler subscribed to an event?

Out of the two — a method does not expose internals thus is better. Would a method returning subscribers for given event type help? 

I'd love to know more about your usecase. Is it mostly for debugging?

**Comment by StanisLove** [comment]
> Is it mostly for debugging?

No. I just want to write a test.
`rails_event_store-rspec` provides a matcher to be sure that the event was published.
Also, I can write a test for my handler.
And want to have a test in case when I forgot to subscribe for the event or somebody remove the subscription.

It is not a big problem. I can write something like that

```ruby
  specify do
    expect_any_instance_of(MyHandler).to receive(:handle_event)
    event_store.publish(event, stream_name: stream_name)
  end
```
But here I get dealing with a database, that I think is not mandatory. So I'm looking for a cheaper way to check this.

> Would a method returning subscribers for given event type help?

Yes. Maybe another matcher in `rails_event_store-rspec` will be useful...

**Comment by pawelpacana** [comment]
> And want to have a test in case when I forgot to subscribe for the event or somebody remove the subscription.
> Maybe another matcher in rails_event_store-rspec will be useful

Good idea, I'd gladly accept this contribution! 

To recap what'll be needed:
-  public API to return known handlers for given event type
- matcher to verify that given handlers subscribes for given event type

**Comment by pawelpacana** [comment]
Let me know if you need any help on this or have further questions
