### ISSUE TITLE
Question: How can i easily add additional columns to the events and streams table?

### ISSUE THREAD

**Issue by butsjoh** [RailsEventStore/rails_event_store#845]
Hi,

Maybe an obvious question to answer but would one add an additional column to the event_store_events and event_store_events_in_streams tables? 

We are currently using ruby event store with rom and i am aware of custom mapper and serialise logic (https://railseventstore.org/docs/v1/mapping_serialization/)  but i cannot accomplish my goal with that. We have a multitenant app and i want to be able to separate events per tenant using an additional column (tenant_id). I guess i would need to write my own repository implementation todo that (like described here: https://railseventstore.org/docs/v1/repository/)? Or is there something i am missing and could use todo this easily without monkeypatching the rom repository.

**Comment by pawelpacana** [comment]
If you need to support your own table structure (i.e. adding additional columns and behaviour around that) going with custom repository is the best. 

There is a set of shared examples we run against repositories (active_record, in-memory, rom): https://github.com/RailsEventStore/rails_event_store/blob/master/ruby_event_store/lib/ruby_event_store/spec/event_repository_lint.rb. Those are distributed with `ruby_event_store` gem:

```ruby
require 'ruby_event_store/spec/event_repository_lint'

RSpec.describe MyRepository do
  include_examples :event_repository
end
```

**Comment by pawelpacana** [comment]
> We have a multitenant app and i want to be able to separate events per tenant using an additional column (tenant_id)

Maybe a viable alternative could be to have separate event tables per tenant?
https://blog.arkency.com/rails-multiple-databases-support-in-rails-event-store/

**Comment by pawelpacana** [comment]
> We are currently using ruby event store with rom 

I'd love to know which ruby event store version are you on!

**Comment by pawelpacana** [comment]
btw. we're looking for ROM repository contributor — https://github.com/RailsEventStore/rails_event_store/issues/834

**Comment by butsjoh** [comment]
Hi, i will discuss this internally here about becoming a ROM repository contributor related to RES. Our use case is without using rails at all so we cannot use anything rails or active record specific. So i guess making a custom repository is what we will need todo eventually. I will need to look into the event store implementation a bit deeper to see what needs to be changed and how it can be maintained.

**Comment by butsjoh** [comment]
> > We are currently using ruby event store with rom
> 
> I'd love to know which ruby event store version are you on!

We are on 1.1.1
