### ISSUE TITLE
Consider using prepend module pattern to set constructor values in AggregateRoot

### ISSUE THREAD

**Issue by paneq** [RailsEventStore/rails_event_store#87]
Consider this code:

```
module AggregateRoot
  def apply(event)
    apply_strategy.(self, event)
    unpublished_events << event
  end

  def load(stream_name, event_store: default_event_store)
    @loaded_from_stream_name = stream_name
    events = event_store.read_stream_events_forward(stream_name)
    events.each do |event|
      apply(event)
    end
    @version = events.size - 1
    @unpublished_events = nil
    self
  end

  def store(stream_name = loaded_from_stream_name, event_store: default_event_store)
    event_store.publish_events(unpublished_events, stream_name: stream_name, expected_version: version)
    @version += unpublished_events.size
    @unpublished_events = nil
  end

  private
  attr_reader :loaded_from_stream_name

  def unpublished_events
    @unpublished_events ||= []
  end

  def version
    @version ||= -1
  end
```

It uses lazy methods to create instance variables at first usage:

```
  def unpublished_events
    @unpublished_events ||= []
  end

  def version
    @version ||= -1
  end
```

But that's because we don't have a constructor because our logic is implemented as module.

What if we did something like:

```
module X
  module Constructor
    def initialize
      puts "C"
      super if defined?(super)
    end
  end
  def self.included(klass)
    klass.prepend(Constructor)
  end
end

class A
  include X

  def initialize
    puts "A"
  end
end

A.new
```

to initialize defaults such as:

```
@unpublished_events = []
@version = -1
```

Would that make sense or make things more convoluted?

Inspired by mutation testing:

```
evil:AggregateRoot#store:/home/travis/build/RailsEventStore/rails_event_store/aggregate_root/lib/aggregate_root.rb:23:b9e31
@@ -1,6 +1,6 @@
 def store(stream_name = loaded_from_stream_name, event_store: default_event_store)
   event_store.publish_events(unpublished_events, stream_name: stream_name, expected_version: version)
   @version += unpublished_events.size
-  @unpublished_events = []
+  @unpublished_events = nil
 end
```

Current `master` brach does not have `@version` but after https://github.com/RailsEventStore/rails_event_store/pull/86 it will have

**Comment by paneq** [comment]
Alternatively if we implement `@loaded_events` then `version` could be just `@loaded_events.size -1` and `store` should append `unpublished_events` to `@loaded_events` and `version` getter would continue to work. But in such case we would have 2 instance variables to initialize `@loaded_events` and `@unpublished_events` so the discussion is still relevant.

**Comment by mlomnicki** [comment]
```ruby
  def self.included(klass)
    klass.prepend(Constructor)
  end
```

This is both brilliant and scary at the same time. Mutant usually gives excellent hints and enforces good code but sometimes it asks [for too much](https://github.com/RailsEventStore/rails_event_store/pull/73#discussion_r135056151). To me the lazy-loaded version is a perfectly reasonable and idomatic Ruby code
