### ISSUE TITLE
Setup full mutation runs, daily

### ISSUE THREAD

**Issue by pawelpacana** [RailsEventStore/rails_event_store#872]
We've recently moved to incremental mutation testing. It is assumed that master is fully covered at this point, we're muation testing only additions on CI. This is orders of magnitude faster, given typical change.

Yet ignored subjects change, mutant gets new transformations and some bugs in MRI uncover. We need daily builds, ideally on linux and macos to help triage source of issue.

**Comment by pawelpacana** [comment]
https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#onschedule

Full mutant run is triggered by `make mutate`. We need it for each gem.

**Comment by mbj** [comment]
I'd also love to enable you to use mutants remote persistence features so you can drive a badge from them indicating the master coverage.

I've yet to publish the code (so far its all client specific) and make it ready for public repos. Lets talk in discord later once you are fully on GH-Actions.

**Comment by pawelpacana** [comment]
For some reason this did not work: https://github.com/RailsEventStore/rails_event_store/pull/873/commits/f097e08a92c69d2efcf81f44e685f86c474706b1#diff-a2115d277b5ca5a2f09a999e53440839cf332b94da177f3d1766334555b0f7c6R4

**Comment by pawelpacana** [comment]
@mbj got it going for initial gems and results are interesting: https://github.com/RailsEventStore/rails_event_store/actions/runs/408118537 

on average linux is almost twice as much slower than macos

**Comment by pawelpacana** [comment]
ah, nevermind — difference in number of jobs, 2 vs 4

**Comment by mbj** [comment]
haha, was about to say that ;)

BTW: On "large runs" mutant has a drop off in speed, this is due "trashing" the COW mechanism on forks. The new external runner changes the process model fixes this.

**Comment by mbj** [comment]
BTW: Would you be interested in having coverage batch(es) for this project? Happy to hook you up with a beta.
