### ISSUE TITLE
Disable CodeClimate checks integration

### ISSUE THREAD

**Issue by pawelpacana** [RailsEventStore/rails_event_store#878]
I don't mind reports and suggestions from CodeClimate. I find it very disturbing when it wants to be decisive and fails otherwise good, mutation-reviewed build.

**Comment by pawelpacana** [comment]
I cannot see how it can be disabled, perhaps we have to remove CodeCilmate for greater good 🤷 

Ideas @fidel?

**Comment by fidel** [comment]
@pawelpacana I've disabled this: https://docs.codeclimate.com/docs/github-pull-requests#pull-request-statuses

If it's not enough, I can fully remove it. Feedback appreciated.

**Comment by pawelpacana** [comment]
That should do.
