### ISSUE TITLE
Proposal: Make `make install` also `bundle install` on alternative `Gemfiles`.

### ISSUE THREAD

**Issue by mbj** [RailsEventStore/rails_event_store#906]
Currently when manually bumping mutant, one has to manually traverse the subprojects and possible gemfiles like `bundle install --gemfile Gemfile.rails_5_0`.

In making `bundle install` executing each individual combination this time could be spared.

**Comment by pawelpacana** [comment]
started that direction earlier today:
https://github.com/RailsEventStore/rails_event_store/commit/a7ff539e5c55dc3e86a3719f09a8c08559981c7b

**Comment by mbj** [comment]
@pawelpacana Feel free to close this one, unsure about policies here. In my projects I'd keep issues open unless clearly a duplicate till fixed.
