### ISSUE TITLE
Expiration/cleanup of events

### ISSUE THREAD

**Issue by acetinick** [RailsEventStore/rails_event_store#915]
Hi,

Firstly great project, I am really excited to use this library and we are currently testing it out within our SaaS platform.

I see that overtime we would be adding thousands/millions of rows added to the event_store_events and event_store_events_in_stream tables, on events that we publish.  

I don't see a need for us to persistantly store these events forever, so is is common to build a rake task or something to clean these events up events older than a period of time? eg.  14 days.

I usually familiar with Kinesis which typcially stores events for up to 7 days.

**Comment by mpraglowski** [comment]
Hi

> Firstly great project, I am really excited to use this library and we are currently testing it out within our SaaS platform.

💚 Thanks! We will be happy to learn more about your experiences and use cases.


> I see that overtime we would be adding thousands/millions of rows added to the event_store_events and event_store_events_in_stream tables, on events that we publish.

What are your expectations? How many events will you store per time unit? (day/week/month)

> I don't see a need for us to persistantly store these events forever, so is is common to build a rake task or something to clean these events up events older than a period of time? eg. 14 days.

RES does not have that API now. There is an option to `delete_stream` however this will not delete any events from events table, just the assignments of an events to removed stream. 

The scavenging API is not something we have in our roadmap but will be happy to see your solution for that, PR maybe?
Things to consider:

* some events might be linked to several streams, removing only events could potentially break ordering of the stream
* projections that rely on stream or several streams might give different results after removal of events
