### ISSUE TITLE
Cleanup ruby_event_store repo

### ISSUE THREAD

**Issue by pawelpacana** [RailsEventStore/rails_event_store#93]
This [repository](https://github.com/RailsEventStore/ruby_event_store) is now a placeholder to redirect to the monorepo (via link in README). There are however some discussions and branches to take care of:
- [x] migrate (or close) issues
- [x] migrate (or close) pull requests
- [x] rebase (or not) and remove branches

**Comment by mlomnicki** [comment]
There is my branch in this repo but I don't have permissions to remove it. Anyway, it's not needed so feel free to get rid of it

https://github.com/RailsEventStore/ruby_event_store/tree/locking
