### ISSUE TITLE
Consider (re)moving git tags < 0.15.0

### ISSUE THREAD

**Issue by pawelpacana** [RailsEventStore/rails_event_store#96]
Since rewriting commit SHAs tags before rewrite point to wrong commits. This might be confusing at least.

We could probably remove those tags (no value from them now). 

Additionally (if that makes sense) I could imagine adjusting (re-adding) them to point to new SHAs.

**Comment by mlomnicki** [comment]
> Additionally (if that makes sense) I could imagine adjusting (re-adding) them to point to new SHAs.

I think it's a waste of time. +1 for  removing them

**Comment by pawelpacana** [comment]
Tags seen as "unmerged" have been removed.

**Comment by pawelpacana** [comment]
```
git tag -l --no-merged | while read -l line                                                                                %1 1s 113ms 
                               git push --delete origin $line
                               git tag -d $line
                         end
```

**Comment by paneq** [comment]
`error: unknown option `no-merged'` I guess i need to upgrade git :)
