### ISSUE TITLE
Move sample apps from contrib to separate repositories

### ISSUE THREAD

**Issue by pawelpacana** [RailsEventStore/rails_event_store#992]
Probably needs cross-checking with arkency/posts repository.

**Comment by pawelpacana** [comment]
* dres/sample_producer
* dres/sample_consumer
* multiple databases sample

**Comment by swistak35** [comment]
@mpraglowski @pawelpacana maybe it would make sense to have one monorepo `rails_event_store-examples`? So one could check what are interesting things doable with RES by inspecting this one repository. Sounds good? I think it follows the practice of many (ex. [elastic], [algolia], [kubernetes]) open source ecosystems to have a single repo with examples, doesn't it?

[elastic]: https://github.com/elastic/examples
[algolia]: https://github.com/algolia/examples
[kubernetes]: https://github.com/kubernetes/examples

**Comment by pawelpacana** [comment]
Sounds good to me from discoverability POV. Could be more tricky to clone just the  single example. Dependabot could work with both approaches (provided no shared-Gemfile-as-a-file parts).

**Comment by swistak35** [comment]
- [ ] create `examples/` repo
- [ ] add license
- [ ] move multiple databases repo app
- [ ] add github workflow for multiple databases repo app
- [ ] move dres sample consumer app
- [ ] move dres sample producer app
- [ ] ensure that dres sample apps work together

**Comment by swistak35** [comment]
re: dependabot -- it looks that it works by default because it's connected to the whole organization.
